// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: dashboard.sql

package dbgen

import (
	"context"
)

const actorFreshnessByKind = `-- name: ActorFreshnessByKind :many
SELECT
    resource_kind,
    fetch_state,
    COUNT(*) AS count,
    MAX(last_fetched_at) AS last_fetched
FROM cache_metadata
WHERE actor = ?
GROUP BY resource_kind, fetch_state
ORDER BY resource_kind, fetch_state
`

type ActorFreshnessByKindRow struct {
	ResourceKind string
	FetchState   string
	Count        int64
	LastFetched  interface{}
}

// ActorFreshnessByKind summarizes cache_metadata for one actor, grouped by
// resource kind and fetch state, with the most recent fetch time per group.
func (q *Queries) ActorFreshnessByKind(ctx context.Context, actor string) ([]ActorFreshnessByKindRow, error) {
	rows, err := q.db.QueryContext(ctx, actorFreshnessByKind, actor)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ActorFreshnessByKindRow
	for rows.Next() {
		var i ActorFreshnessByKindRow
		if err := rows.Scan(
			&i.ResourceKind,
			&i.FetchState,
			&i.Count,
			&i.LastFetched,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const actorRecentRefreshes = `-- name: ActorRecentRefreshes :many
SELECT id, actor, resource_kind, resource_key, triggered_by, started_at, completed_at, success, records_changed, error_message FROM cache_refresh_log
WHERE actor = ?
ORDER BY id DESC
LIMIT ?
`

type ActorRecentRefreshesParams struct {
	Actor string
	Limit int64
}

// ActorRecentRefreshes returns the most recent refresh-log entries for one actor.
func (q *Queries) ActorRecentRefreshes(ctx context.Context, arg ActorRecentRefreshesParams) ([]CacheRefreshLog, error) {
	rows, err := q.db.QueryContext(ctx, actorRecentRefreshes, arg.Actor, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CacheRefreshLog
	for rows.Next() {
		var i CacheRefreshLog
		if err := rows.Scan(
			&i.ID,
			&i.Actor,
			&i.ResourceKind,
			&i.ResourceKey,
			&i.TriggeredBy,
			&i.StartedAt,
			&i.CompletedAt,
			&i.Success,
			&i.RecordsChanged,
			&i.ErrorMessage,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countBranchComparisonsByActor = `-- name: CountBranchComparisonsByActor :one
SELECT COUNT(*) FROM branch_comparisons WHERE actor = ?
`

func (q *Queries) CountBranchComparisonsByActor(ctx context.Context, actor string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countBranchComparisonsByActor, actor)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countCommitChecksByActor = `-- name: CountCommitChecksByActor :one
SELECT COUNT(*) FROM commit_checks WHERE actor = ?
`

func (q *Queries) CountCommitChecksByActor(ctx context.Context, actor string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countCommitChecksByActor, actor)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countOrgsByActor = `-- name: CountOrgsByActor :one
SELECT COUNT(*) FROM orgs WHERE actor = ?
`

func (q *Queries) CountOrgsByActor(ctx context.Context, actor string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countOrgsByActor, actor)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countPRFilesByActor = `-- name: CountPRFilesByActor :one
SELECT COUNT(*) FROM pr_files WHERE actor = ?
`

func (q *Queries) CountPRFilesByActor(ctx context.Context, actor string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countPRFilesByActor, actor)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countPullRequestsByActor = `-- name: CountPullRequestsByActor :one
SELECT COUNT(*) FROM pull_requests WHERE actor = ?
`

func (q *Queries) CountPullRequestsByActor(ctx context.Context, actor string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countPullRequestsByActor, actor)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countReposByActor = `-- name: CountReposByActor :one
SELECT COUNT(*) FROM repos WHERE actor = ?
`

// Per-table cached-row counts for one actor. Kept as separate single-table
// queries (rather than one multi-table statement) because sqlc's SQLite analyzer
// treats the shared `actor` column name across tables as ambiguous otherwise.
func (q *Queries) CountReposByActor(ctx context.Context, actor string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countReposByActor, actor)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUsersByActor = `-- name: CountUsersByActor :one
SELECT COUNT(*) FROM users WHERE actor = ?
`

func (q *Queries) CountUsersByActor(ctx context.Context, actor string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countUsersByActor, actor)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const listActorIdentities = `-- name: ListActorIdentities :many
SELECT actor, login, first_seen, last_seen FROM actor_identities ORDER BY login, actor
`

func (q *Queries) ListActorIdentities(ctx context.Context) ([]ActorIdentity, error) {
	rows, err := q.db.QueryContext(ctx, listActorIdentities)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ActorIdentity
	for rows.Next() {
		var i ActorIdentity
		if err := rows.Scan(
			&i.Actor,
			&i.Login,
			&i.FirstSeen,
			&i.LastSeen,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCachedActors = `-- name: ListCachedActors :many

SELECT DISTINCT actor FROM cache_metadata ORDER BY actor
`

// ============================================================================
// Cross-actor cache statistics (dashboard only)
// ============================================================================
// ListCachedActors returns every distinct actor that has any cache metadata,
// so the admin view can attribute even scopes with no identity row (e.g. the
// background service token before it is recorded).
func (q *Queries) ListCachedActors(ctx context.Context) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listCachedActors)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var actor string
		if err := rows.Scan(&actor); err != nil {
			return nil, err
		}
		items = append(items, actor)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertActorIdentity = `-- name: UpsertActorIdentity :exec

INSERT INTO actor_identities (actor, login, first_seen, last_seen)
VALUES (?, ?, ?, ?)
ON CONFLICT (actor) DO UPDATE SET
    login = excluded.login,
    last_seen = excluded.last_seen
`

type UpsertActorIdentityParams struct {
	Actor     string
	Login     string
	FirstSeen string
	LastSeen  string
}

// ============================================================================
// Actor Identities (dashboard only)
// ============================================================================
func (q *Queries) UpsertActorIdentity(ctx context.Context, arg UpsertActorIdentityParams) error {
	_, err := q.db.ExecContext(ctx, upsertActorIdentity,
		arg.Actor,
		arg.Login,
		arg.FirstSeen,
		arg.LastSeen,
	)
	return err
}
