// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: dashboard.sql

package dbgen

import (
	"context"
	"database/sql"
)

const actorErrorMessagesByKind = `-- name: ActorErrorMessagesByKind :many
SELECT resource_kind, resource_key, error_message
FROM cache_metadata
WHERE actor = ? AND fetch_state = 'error' AND error_message IS NOT NULL AND error_message <> ''
ORDER BY resource_kind, resource_key
`

type ActorErrorMessagesByKindRow struct {
	ResourceKind string
	ResourceKey  string
	ErrorMessage sql.NullString
}

// ActorErrorMessagesByKind returns the captured failure reason for every
// resource currently in the 'error' state for one actor, so the dashboard can
// show *why* a kind is erroring (not just that it is). One row per errored
// resource key.
func (q *Queries) ActorErrorMessagesByKind(ctx context.Context, actor string) ([]ActorErrorMessagesByKindRow, error) {
	rows, err := q.db.QueryContext(ctx, actorErrorMessagesByKind, actor)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ActorErrorMessagesByKindRow
	for rows.Next() {
		var i ActorErrorMessagesByKindRow
		if err := rows.Scan(&i.ResourceKind, &i.ResourceKey, &i.ErrorMessage); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const actorFreshnessByKind = `-- name: ActorFreshnessByKind :many
SELECT
    resource_kind,
    fetch_state,
    COUNT(*) AS count,
    MAX(last_fetched_at) AS last_fetched
FROM cache_metadata
WHERE actor = ?
GROUP BY resource_kind, fetch_state
ORDER BY resource_kind, fetch_state
`

type ActorFreshnessByKindRow struct {
	ResourceKind string
	FetchState   string
	Count        int64
	LastFetched  interface{}
}

// ActorFreshnessByKind summarizes cache_metadata for one actor, grouped by
// resource kind and fetch state, with the most recent fetch time per group.
func (q *Queries) ActorFreshnessByKind(ctx context.Context, actor string) ([]ActorFreshnessByKindRow, error) {
	rows, err := q.db.QueryContext(ctx, actorFreshnessByKind, actor)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ActorFreshnessByKindRow
	for rows.Next() {
		var i ActorFreshnessByKindRow
		if err := rows.Scan(
			&i.ResourceKind,
			&i.FetchState,
			&i.Count,
			&i.LastFetched,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const actorRecentRefreshes = `-- name: ActorRecentRefreshes :many
SELECT id, actor, resource_kind, resource_key, triggered_by, started_at, completed_at, success, records_changed, error_message FROM cache_refresh_log
WHERE actor = ?
ORDER BY id DESC
LIMIT ?
`

type ActorRecentRefreshesParams struct {
	Actor string
	Limit int64
}

// ActorRecentRefreshes returns the most recent refresh-log entries for one actor.
func (q *Queries) ActorRecentRefreshes(ctx context.Context, arg ActorRecentRefreshesParams) ([]CacheRefreshLog, error) {
	rows, err := q.db.QueryContext(ctx, actorRecentRefreshes, arg.Actor, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CacheRefreshLog
	for rows.Next() {
		var i CacheRefreshLog
		if err := rows.Scan(
			&i.ID,
			&i.Actor,
			&i.ResourceKind,
			&i.ResourceKey,
			&i.TriggeredBy,
			&i.StartedAt,
			&i.CompletedAt,
			&i.Success,
			&i.RecordsChanged,
			&i.ErrorMessage,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countBranchComparisonsByActor = `-- name: CountBranchComparisonsByActor :one
SELECT COUNT(*) FROM branch_comparisons WHERE actor = ?
`

func (q *Queries) CountBranchComparisonsByActor(ctx context.Context, actor string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countBranchComparisonsByActor, actor)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countCommitChecksByActor = `-- name: CountCommitChecksByActor :one
SELECT COUNT(*) FROM commit_checks WHERE actor = ?
`

func (q *Queries) CountCommitChecksByActor(ctx context.Context, actor string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countCommitChecksByActor, actor)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countOrgsByActor = `-- name: CountOrgsByActor :one
SELECT COUNT(*) FROM orgs WHERE actor = ?
`

func (q *Queries) CountOrgsByActor(ctx context.Context, actor string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countOrgsByActor, actor)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countPRFilesByActor = `-- name: CountPRFilesByActor :one
SELECT COUNT(*) FROM pr_files WHERE actor = ?
`

func (q *Queries) CountPRFilesByActor(ctx context.Context, actor string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countPRFilesByActor, actor)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countPullRequestsByActor = `-- name: CountPullRequestsByActor :one
SELECT COUNT(*) FROM pull_requests WHERE actor = ?
`

func (q *Queries) CountPullRequestsByActor(ctx context.Context, actor string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countPullRequestsByActor, actor)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countReposByActor = `-- name: CountReposByActor :one
SELECT COUNT(*) FROM repos WHERE actor = ?
`

// Per-table cached-row counts for one actor. Kept as separate single-table
// queries (rather than one multi-table statement) because sqlc's SQLite analyzer
// treats the shared `actor` column name across tables as ambiguous otherwise.
func (q *Queries) CountReposByActor(ctx context.Context, actor string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countReposByActor, actor)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUsersByActor = `-- name: CountUsersByActor :one
SELECT COUNT(*) FROM users WHERE actor = ?
`

func (q *Queries) CountUsersByActor(ctx context.Context, actor string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countUsersByActor, actor)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const listActorIdentities = `-- name: ListActorIdentities :many
SELECT actor, login, first_seen, last_seen FROM actor_identities ORDER BY login, actor
`

func (q *Queries) ListActorIdentities(ctx context.Context) ([]ActorIdentity, error) {
	rows, err := q.db.QueryContext(ctx, listActorIdentities)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ActorIdentity
	for rows.Next() {
		var i ActorIdentity
		if err := rows.Scan(
			&i.Actor,
			&i.Login,
			&i.FirstSeen,
			&i.LastSeen,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBranchComparisonsByActor = `-- name: ListBranchComparisonsByActor :many
SELECT actor, owner, repo, base_ref, head_ref, ahead_by, behind_by FROM branch_comparisons WHERE actor = ? ORDER BY owner, repo, base_ref, head_ref
`

func (q *Queries) ListBranchComparisonsByActor(ctx context.Context, actor string) ([]BranchComparison, error) {
	rows, err := q.db.QueryContext(ctx, listBranchComparisonsByActor, actor)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BranchComparison
	for rows.Next() {
		var i BranchComparison
		if err := rows.Scan(
			&i.Actor,
			&i.Owner,
			&i.Repo,
			&i.BaseRef,
			&i.HeadRef,
			&i.AheadBy,
			&i.BehindBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCachedActors = `-- name: ListCachedActors :many

SELECT DISTINCT actor FROM cache_metadata ORDER BY actor
`

// ============================================================================
// Cross-actor cache statistics (dashboard only)
// ============================================================================
// ListCachedActors returns every distinct actor that has any cache metadata,
// so the admin view can attribute even scopes with no identity row (e.g. the
// background service token before it is recorded).
func (q *Queries) ListCachedActors(ctx context.Context) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listCachedActors)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var actor string
		if err := rows.Scan(&actor); err != nil {
			return nil, err
		}
		items = append(items, actor)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCommitChecksByActor = `-- name: ListCommitChecksByActor :many
SELECT actor, owner, repo, sha, context, state FROM commit_checks WHERE actor = ? ORDER BY owner, repo, sha, context
`

func (q *Queries) ListCommitChecksByActor(ctx context.Context, actor string) ([]CommitCheck, error) {
	rows, err := q.db.QueryContext(ctx, listCommitChecksByActor, actor)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CommitCheck
	for rows.Next() {
		var i CommitCheck
		if err := rows.Scan(
			&i.Actor,
			&i.Owner,
			&i.Repo,
			&i.Sha,
			&i.Context,
			&i.State,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDistinctOwnersByActor = `-- name: ListDistinctOwnersByActor :many
SELECT DISTINCT owner FROM repos WHERE actor = ? ORDER BY owner
`

// ListDistinctOwnersByActor returns the distinct repo owners cached for an actor,
// so the consistency check knows which orgs to re-fetch from GitHub.
func (q *Queries) ListDistinctOwnersByActor(ctx context.Context, actor string) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listDistinctOwnersByActor, actor)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var owner string
		if err := rows.Scan(&owner); err != nil {
			return nil, err
		}
		items = append(items, owner)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOpenPullRequestsByActor = `-- name: ListOpenPullRequestsByActor :many
SELECT actor, owner, repo, number, title, url, is_draft, state, created_at, updated_at, additions, deletions, mergeable, author_login, author_avatar, author_url, head_ref_name, base_ref_name, head_ref_oid, review_request_count, last_commit_status FROM pull_requests WHERE actor = ? AND state = 'OPEN' ORDER BY owner, repo, number
`

// ListOpenPullRequestsByActor returns only OPEN PRs for an actor. The
// consistency check compares these against GitHub's live open-PR set (the cache
// only retains open PRs; closed ones are deleted by the webhook dispatcher).
func (q *Queries) ListOpenPullRequestsByActor(ctx context.Context, actor string) ([]PullRequest, error) {
	rows, err := q.db.QueryContext(ctx, listOpenPullRequestsByActor, actor)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PullRequest
	for rows.Next() {
		var i PullRequest
		if err := rows.Scan(
			&i.Actor,
			&i.Owner,
			&i.Repo,
			&i.Number,
			&i.Title,
			&i.Url,
			&i.IsDraft,
			&i.State,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Additions,
			&i.Deletions,
			&i.Mergeable,
			&i.AuthorLogin,
			&i.AuthorAvatar,
			&i.AuthorUrl,
			&i.HeadRefName,
			&i.BaseRefName,
			&i.HeadRefOid,
			&i.ReviewRequestCount,
			&i.LastCommitStatus,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrgsByActor = `-- name: ListOrgsByActor :many
SELECT actor, login, avatar_url, url FROM orgs WHERE actor = ? ORDER BY login
`

func (q *Queries) ListOrgsByActor(ctx context.Context, actor string) ([]Org, error) {
	rows, err := q.db.QueryContext(ctx, listOrgsByActor, actor)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Org
	for rows.Next() {
		var i Org
		if err := rows.Scan(
			&i.Actor,
			&i.Login,
			&i.AvatarUrl,
			&i.Url,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPRFilesByActor = `-- name: ListPRFilesByActor :many
SELECT actor, owner, repo, pr_number, path, additions, deletions FROM pr_files WHERE actor = ? ORDER BY owner, repo, pr_number, path
`

func (q *Queries) ListPRFilesByActor(ctx context.Context, actor string) ([]PrFile, error) {
	rows, err := q.db.QueryContext(ctx, listPRFilesByActor, actor)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PrFile
	for rows.Next() {
		var i PrFile
		if err := rows.Scan(
			&i.Actor,
			&i.Owner,
			&i.Repo,
			&i.PrNumber,
			&i.Path,
			&i.Additions,
			&i.Deletions,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPRLabelsByActor = `-- name: ListPRLabelsByActor :many
SELECT actor, owner, repo, pr_number, name, color FROM pr_labels WHERE actor = ? ORDER BY owner, repo, pr_number, name
`

func (q *Queries) ListPRLabelsByActor(ctx context.Context, actor string) ([]PrLabel, error) {
	rows, err := q.db.QueryContext(ctx, listPRLabelsByActor, actor)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PrLabel
	for rows.Next() {
		var i PrLabel
		if err := rows.Scan(
			&i.Actor,
			&i.Owner,
			&i.Repo,
			&i.PrNumber,
			&i.Name,
			&i.Color,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPullRequestsByActor = `-- name: ListPullRequestsByActor :many
SELECT actor, owner, repo, number, title, url, is_draft, state, created_at, updated_at, additions, deletions, mergeable, author_login, author_avatar, author_url, head_ref_name, base_ref_name, head_ref_oid, review_request_count, last_commit_status FROM pull_requests WHERE actor = ? ORDER BY owner, repo, number
`

func (q *Queries) ListPullRequestsByActor(ctx context.Context, actor string) ([]PullRequest, error) {
	rows, err := q.db.QueryContext(ctx, listPullRequestsByActor, actor)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PullRequest
	for rows.Next() {
		var i PullRequest
		if err := rows.Scan(
			&i.Actor,
			&i.Owner,
			&i.Repo,
			&i.Number,
			&i.Title,
			&i.Url,
			&i.IsDraft,
			&i.State,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Additions,
			&i.Deletions,
			&i.Mergeable,
			&i.AuthorLogin,
			&i.AuthorAvatar,
			&i.AuthorUrl,
			&i.HeadRefName,
			&i.BaseRefName,
			&i.HeadRefOid,
			&i.ReviewRequestCount,
			&i.LastCommitStatus,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReposByActor = `-- name: ListReposByActor :many

SELECT actor, owner, name, name_with_owner, url, is_disabled, is_archived, pushed_at, default_branch, default_branch_status, owner_login, owner_avatar, owner_url FROM repos WHERE actor = ? ORDER BY owner, name
`

// ============================================================================
// Admin cache browse (dashboard, admin only)
// ============================================================================
//
// These dump the actual cached rows for ONE explicit actor (cache scope). Unlike
// the per-context reads in store.go (which take the actor from the request
// context), these take the actor as a parameter so an admin can inspect any
// scope. They are gated to admins in the API layer; the data tables remain keyed
// by the opaque fingerprint, so this does not change the storage model -- it only
// lets the operator read what is already there.
func (q *Queries) ListReposByActor(ctx context.Context, actor string) ([]Repo, error) {
	rows, err := q.db.QueryContext(ctx, listReposByActor, actor)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Repo
	for rows.Next() {
		var i Repo
		if err := rows.Scan(
			&i.Actor,
			&i.Owner,
			&i.Name,
			&i.NameWithOwner,
			&i.Url,
			&i.IsDisabled,
			&i.IsArchived,
			&i.PushedAt,
			&i.DefaultBranch,
			&i.DefaultBranchStatus,
			&i.OwnerLogin,
			&i.OwnerAvatar,
			&i.OwnerUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsersByActor = `-- name: ListUsersByActor :many
SELECT actor, login, avatar_url, url FROM users WHERE actor = ? ORDER BY login
`

func (q *Queries) ListUsersByActor(ctx context.Context, actor string) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, listUsersByActor, actor)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.Actor,
			&i.Login,
			&i.AvatarUrl,
			&i.Url,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertActorIdentity = `-- name: UpsertActorIdentity :exec

INSERT INTO actor_identities (actor, login, first_seen, last_seen)
VALUES (?, ?, ?, ?)
ON CONFLICT (actor) DO UPDATE SET
    login = excluded.login,
    last_seen = excluded.last_seen
`

type UpsertActorIdentityParams struct {
	Actor     string
	Login     string
	FirstSeen string
	LastSeen  string
}

// ============================================================================
// Actor Identities (dashboard only)
// ============================================================================
func (q *Queries) UpsertActorIdentity(ctx context.Context, arg UpsertActorIdentityParams) error {
	_, err := q.db.ExecContext(ctx, upsertActorIdentity,
		arg.Actor,
		arg.Login,
		arg.FirstSeen,
		arg.LastSeen,
	)
	return err
}
