// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: dashboard.sql

package dbgen

import (
	"context"
	"database/sql"
)

const actorErrorMessagesByKind = `-- name: ActorErrorMessagesByKind :many
SELECT resource_kind, resource_key, error_message
FROM cache_metadata
WHERE actor = ? AND fetch_state = 'error' AND error_message IS NOT NULL AND error_message <> ''
ORDER BY resource_kind, resource_key
`

type ActorErrorMessagesByKindRow struct {
	ResourceKind string
	ResourceKey  string
	ErrorMessage sql.NullString
}

// ActorErrorMessagesByKind returns the captured failure reason for every
// resource currently in the 'error' state for one actor, so the dashboard can
// show *why* a kind is erroring (not just that it is). One row per errored
// resource key.
func (q *Queries) ActorErrorMessagesByKind(ctx context.Context, actor string) ([]ActorErrorMessagesByKindRow, error) {
	rows, err := q.db.QueryContext(ctx, actorErrorMessagesByKind, actor)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ActorErrorMessagesByKindRow
	for rows.Next() {
		var i ActorErrorMessagesByKindRow
		if err := rows.Scan(&i.ResourceKind, &i.ResourceKey, &i.ErrorMessage); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const actorFreshnessByKind = `-- name: ActorFreshnessByKind :many
SELECT
    resource_kind,
    fetch_state,
    COUNT(*) AS count,
    MAX(last_fetched_at) AS last_fetched
FROM cache_metadata
WHERE actor = ?
GROUP BY resource_kind, fetch_state
ORDER BY resource_kind, fetch_state
`

type ActorFreshnessByKindRow struct {
	ResourceKind string
	FetchState   string
	Count        int64
	LastFetched  interface{}
}

// ActorFreshnessByKind summarizes cache_metadata for one actor (a principal's
// grant-sync markers, or 'global' truth markers), grouped by resource kind and
// fetch state, with the most recent fetch time per group.
func (q *Queries) ActorFreshnessByKind(ctx context.Context, actor string) ([]ActorFreshnessByKindRow, error) {
	rows, err := q.db.QueryContext(ctx, actorFreshnessByKind, actor)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ActorFreshnessByKindRow
	for rows.Next() {
		var i ActorFreshnessByKindRow
		if err := rows.Scan(
			&i.ResourceKind,
			&i.FetchState,
			&i.Count,
			&i.LastFetched,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const actorRecentRefreshes = `-- name: ActorRecentRefreshes :many
SELECT id, actor, resource_kind, resource_key, triggered_by, started_at, completed_at, success, records_changed, error_message FROM cache_refresh_log
WHERE actor = ?
ORDER BY id DESC
LIMIT ?
`

type ActorRecentRefreshesParams struct {
	Actor string
	Limit int64
}

// ActorRecentRefreshes returns the most recent refresh-log entries for one actor.
func (q *Queries) ActorRecentRefreshes(ctx context.Context, arg ActorRecentRefreshesParams) ([]CacheRefreshLog, error) {
	rows, err := q.db.QueryContext(ctx, actorRecentRefreshes, arg.Actor, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CacheRefreshLog
	for rows.Next() {
		var i CacheRefreshLog
		if err := rows.Scan(
			&i.ID,
			&i.Actor,
			&i.ResourceKind,
			&i.ResourceKey,
			&i.TriggeredBy,
			&i.StartedAt,
			&i.CompletedAt,
			&i.Success,
			&i.RecordsChanged,
			&i.ErrorMessage,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countAccessGrants = `-- name: CountAccessGrants :one
SELECT COUNT(*) FROM access_grants
`

func (q *Queries) CountAccessGrants(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countAccessGrants)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countCommitChecks = `-- name: CountCommitChecks :one
SELECT COUNT(*) FROM commit_checks
`

func (q *Queries) CountCommitChecks(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countCommitChecks)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countContentsCache = `-- name: CountContentsCache :one
SELECT COUNT(*) FROM contents_cache
`

func (q *Queries) CountContentsCache(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countContentsCache)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countGitCommitsCache = `-- name: CountGitCommitsCache :one
SELECT COUNT(*) FROM git_commits_cache
`

func (q *Queries) CountGitCommitsCache(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countGitCommitsCache)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countPullRequests = `-- name: CountPullRequests :one
SELECT COUNT(*) FROM pull_requests
`

func (q *Queries) CountPullRequests(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countPullRequests)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countRepos = `-- name: CountRepos :one
SELECT COUNT(*) FROM repos
`

// Global (whole-truth-store) row counts. Kept as separate single-table
// queries: sqlc's SQLite analyzer handles them more reliably than one
// multi-table statement.
func (q *Queries) CountRepos(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countRepos)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const listActorIdentities = `-- name: ListActorIdentities :many
SELECT actor, login, first_seen, last_seen FROM actor_identities ORDER BY login, actor
`

func (q *Queries) ListActorIdentities(ctx context.Context) ([]ActorIdentity, error) {
	rows, err := q.db.QueryContext(ctx, listActorIdentities)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ActorIdentity
	for rows.Next() {
		var i ActorIdentity
		if err := rows.Scan(
			&i.Actor,
			&i.Login,
			&i.FirstSeen,
			&i.LastSeen,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllCommitChecks = `-- name: ListAllCommitChecks :many
SELECT owner, repo, sha, context, state FROM commit_checks ORDER BY owner, repo, sha, context
`

func (q *Queries) ListAllCommitChecks(ctx context.Context) ([]CommitCheck, error) {
	rows, err := q.db.QueryContext(ctx, listAllCommitChecks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CommitCheck
	for rows.Next() {
		var i CommitCheck
		if err := rows.Scan(
			&i.Owner,
			&i.Repo,
			&i.Sha,
			&i.Context,
			&i.State,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllOpenPullRequests = `-- name: ListAllOpenPullRequests :many
SELECT owner, repo, number, title, url, is_draft, state, created_at, updated_at, additions, deletions, mergeable, author_login, author_avatar, author_url, head_ref_name, base_ref_name, head_ref_oid, review_request_count, last_commit_status, node_id, body, auto_merge, mergeable_state, merge_commit_sha, base_sha, head_repo_full_name, touched_at FROM pull_requests WHERE state = 'OPEN' ORDER BY owner, repo, number
`

// ListAllOpenPullRequests returns only OPEN PRs. The consistency check compares
// these against GitHub's live open-PR set (the cache only retains open PRs;
// closed ones are deleted by the webhook dispatcher).
func (q *Queries) ListAllOpenPullRequests(ctx context.Context) ([]PullRequest, error) {
	rows, err := q.db.QueryContext(ctx, listAllOpenPullRequests)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PullRequest
	for rows.Next() {
		var i PullRequest
		if err := rows.Scan(
			&i.Owner,
			&i.Repo,
			&i.Number,
			&i.Title,
			&i.Url,
			&i.IsDraft,
			&i.State,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Additions,
			&i.Deletions,
			&i.Mergeable,
			&i.AuthorLogin,
			&i.AuthorAvatar,
			&i.AuthorUrl,
			&i.HeadRefName,
			&i.BaseRefName,
			&i.HeadRefOid,
			&i.ReviewRequestCount,
			&i.LastCommitStatus,
			&i.NodeID,
			&i.Body,
			&i.AutoMerge,
			&i.MergeableState,
			&i.MergeCommitSha,
			&i.BaseSha,
			&i.HeadRepoFullName,
			&i.TouchedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllPRLabels = `-- name: ListAllPRLabels :many
SELECT owner, repo, pr_number, name, color FROM pr_labels ORDER BY owner, repo, pr_number, name
`

func (q *Queries) ListAllPRLabels(ctx context.Context) ([]PrLabel, error) {
	rows, err := q.db.QueryContext(ctx, listAllPRLabels)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PrLabel
	for rows.Next() {
		var i PrLabel
		if err := rows.Scan(
			&i.Owner,
			&i.Repo,
			&i.PrNumber,
			&i.Name,
			&i.Color,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllPullRequests = `-- name: ListAllPullRequests :many
SELECT owner, repo, number, title, url, is_draft, state, created_at, updated_at, additions, deletions, mergeable, author_login, author_avatar, author_url, head_ref_name, base_ref_name, head_ref_oid, review_request_count, last_commit_status, node_id, body, auto_merge, mergeable_state, merge_commit_sha, base_sha, head_repo_full_name, touched_at FROM pull_requests ORDER BY owner, repo, number
`

func (q *Queries) ListAllPullRequests(ctx context.Context) ([]PullRequest, error) {
	rows, err := q.db.QueryContext(ctx, listAllPullRequests)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PullRequest
	for rows.Next() {
		var i PullRequest
		if err := rows.Scan(
			&i.Owner,
			&i.Repo,
			&i.Number,
			&i.Title,
			&i.Url,
			&i.IsDraft,
			&i.State,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Additions,
			&i.Deletions,
			&i.Mergeable,
			&i.AuthorLogin,
			&i.AuthorAvatar,
			&i.AuthorUrl,
			&i.HeadRefName,
			&i.BaseRefName,
			&i.HeadRefOid,
			&i.ReviewRequestCount,
			&i.LastCommitStatus,
			&i.NodeID,
			&i.Body,
			&i.AutoMerge,
			&i.MergeableState,
			&i.MergeCommitSha,
			&i.BaseSha,
			&i.HeadRepoFullName,
			&i.TouchedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllRepos = `-- name: ListAllRepos :many

SELECT owner, name, name_with_owner, url, is_disabled, is_archived, visibility, pushed_at, default_branch, default_branch_status, owner_login, owner_avatar, owner_url FROM repos ORDER BY owner, name
`

// ============================================================================
// Admin cache browse (dashboard, admin only)
// ============================================================================
//
// These dump the actual global-truth rows for the operator. Admin-gated in the
// API layer; the consistency check compares them against GitHub.
func (q *Queries) ListAllRepos(ctx context.Context) ([]Repo, error) {
	rows, err := q.db.QueryContext(ctx, listAllRepos)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Repo
	for rows.Next() {
		var i Repo
		if err := rows.Scan(
			&i.Owner,
			&i.Name,
			&i.NameWithOwner,
			&i.Url,
			&i.IsDisabled,
			&i.IsArchived,
			&i.Visibility,
			&i.PushedAt,
			&i.DefaultBranch,
			&i.DefaultBranchStatus,
			&i.OwnerLogin,
			&i.OwnerAvatar,
			&i.OwnerUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDistinctRepoOwners = `-- name: ListDistinctRepoOwners :many
SELECT DISTINCT owner FROM repos ORDER BY owner
`

func (q *Queries) ListDistinctRepoOwners(ctx context.Context) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listDistinctRepoOwners)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var owner string
		if err := rows.Scan(&owner); err != nil {
			return nil, err
		}
		items = append(items, owner)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listKnownPrincipals = `-- name: ListKnownPrincipals :many

SELECT DISTINCT actor FROM cache_metadata WHERE actor != 'global' ORDER BY actor
`

// ============================================================================
// Global cache statistics (dashboard only)
// ============================================================================
// ListKnownPrincipals returns every principal that holds freshness metadata,
// so the admin view can attribute even principals with no identity row (e.g.
// the background app-installation sessions). 'global' rows are truth
// freshness, not a principal.
func (q *Queries) ListKnownPrincipals(ctx context.Context) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listKnownPrincipals)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var actor string
		if err := rows.Scan(&actor); err != nil {
			return nil, err
		}
		items = append(items, actor)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertActorIdentity = `-- name: UpsertActorIdentity :exec

INSERT INTO actor_identities (actor, login, first_seen, last_seen)
VALUES (?, ?, ?, ?)
ON CONFLICT (actor) DO UPDATE SET
    login = excluded.login,
    last_seen = excluded.last_seen
`

type UpsertActorIdentityParams struct {
	Actor     string
	Login     string
	FirstSeen string
	LastSeen  string
}

// ============================================================================
// Principal Identities (dashboard only)
// ============================================================================
func (q *Queries) UpsertActorIdentity(ctx context.Context, arg UpsertActorIdentityParams) error {
	_, err := q.db.ExecContext(ctx, upsertActorIdentity,
		arg.Actor,
		arg.Login,
		arg.FirstSeen,
		arg.LastSeen,
	)
	return err
}
