// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: freshness.sql

package dbgen

import (
	"context"
	"database/sql"
)

const completeRefreshLog = `-- name: CompleteRefreshLog :exec
UPDATE cache_refresh_log SET
    completed_at = ?,
    success = ?,
    records_changed = ?,
    error_message = ?
WHERE id = ?
`

type CompleteRefreshLogParams struct {
	CompletedAt    sql.NullString
	Success        sql.NullInt64
	RecordsChanged sql.NullInt64
	ErrorMessage   sql.NullString
	ID             int64
}

func (q *Queries) CompleteRefreshLog(ctx context.Context, arg CompleteRefreshLogParams) error {
	_, err := q.db.ExecContext(ctx, completeRefreshLog,
		arg.CompletedAt,
		arg.Success,
		arg.RecordsChanged,
		arg.ErrorMessage,
		arg.ID,
	)
	return err
}

const deleteCacheMetadata = `-- name: DeleteCacheMetadata :exec
DELETE FROM cache_metadata
WHERE actor = ? AND resource_kind = ? AND resource_key = ?
`

type DeleteCacheMetadataParams struct {
	Actor        string
	ResourceKind string
	ResourceKey  string
}

func (q *Queries) DeleteCacheMetadata(ctx context.Context, arg DeleteCacheMetadataParams) error {
	_, err := q.db.ExecContext(ctx, deleteCacheMetadata, arg.Actor, arg.ResourceKind, arg.ResourceKey)
	return err
}

const getCacheMetadata = `-- name: GetCacheMetadata :one
SELECT actor, resource_kind, resource_key, last_fetched_at, last_changed_at, etag, expires_at, fetch_state, error_message, retry_after FROM cache_metadata
WHERE actor = ? AND resource_kind = ? AND resource_key = ?
`

type GetCacheMetadataParams struct {
	Actor        string
	ResourceKind string
	ResourceKey  string
}

func (q *Queries) GetCacheMetadata(ctx context.Context, arg GetCacheMetadataParams) (CacheMetadatum, error) {
	row := q.db.QueryRowContext(ctx, getCacheMetadata, arg.Actor, arg.ResourceKind, arg.ResourceKey)
	var i CacheMetadatum
	err := row.Scan(
		&i.Actor,
		&i.ResourceKind,
		&i.ResourceKey,
		&i.LastFetchedAt,
		&i.LastChangedAt,
		&i.Etag,
		&i.ExpiresAt,
		&i.FetchState,
		&i.ErrorMessage,
		&i.RetryAfter,
	)
	return i, err
}

const insertRefreshLog = `-- name: InsertRefreshLog :one
INSERT INTO cache_refresh_log (actor, resource_kind, resource_key, triggered_by, started_at)
VALUES (?, ?, ?, ?, ?)
RETURNING id
`

type InsertRefreshLogParams struct {
	Actor        string
	ResourceKind string
	ResourceKey  string
	TriggeredBy  string
	StartedAt    string
}

func (q *Queries) InsertRefreshLog(ctx context.Context, arg InsertRefreshLogParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, insertRefreshLog,
		arg.Actor,
		arg.ResourceKind,
		arg.ResourceKey,
		arg.TriggeredBy,
		arg.StartedAt,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const listByKind = `-- name: ListByKind :many
SELECT actor, resource_kind, resource_key, last_fetched_at, last_changed_at, etag, expires_at, fetch_state, error_message, retry_after FROM cache_metadata
WHERE actor = ? AND resource_kind = ?
`

type ListByKindParams struct {
	Actor        string
	ResourceKind string
}

func (q *Queries) ListByKind(ctx context.Context, arg ListByKindParams) ([]CacheMetadatum, error) {
	rows, err := q.db.QueryContext(ctx, listByKind, arg.Actor, arg.ResourceKind)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CacheMetadatum
	for rows.Next() {
		var i CacheMetadatum
		if err := rows.Scan(
			&i.Actor,
			&i.ResourceKind,
			&i.ResourceKey,
			&i.LastFetchedAt,
			&i.LastChangedAt,
			&i.Etag,
			&i.ExpiresAt,
			&i.FetchState,
			&i.ErrorMessage,
			&i.RetryAfter,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStale = `-- name: ListStale :many
SELECT actor, resource_kind, resource_key, last_fetched_at, last_changed_at, etag, expires_at, fetch_state, error_message, retry_after FROM cache_metadata
WHERE actor = ? AND (
    fetch_state IN ('stale', 'unknown')
    OR (fetch_state = 'fresh' AND expires_at < ?)
)
`

type ListStaleParams struct {
	Actor     string
	ExpiresAt sql.NullString
}

func (q *Queries) ListStale(ctx context.Context, arg ListStaleParams) ([]CacheMetadatum, error) {
	rows, err := q.db.QueryContext(ctx, listStale, arg.Actor, arg.ExpiresAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CacheMetadatum
	for rows.Next() {
		var i CacheMetadatum
		if err := rows.Scan(
			&i.Actor,
			&i.ResourceKind,
			&i.ResourceKey,
			&i.LastFetchedAt,
			&i.LastChangedAt,
			&i.Etag,
			&i.ExpiresAt,
			&i.FetchState,
			&i.ErrorMessage,
			&i.RetryAfter,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markError = `-- name: MarkError :exec
UPDATE cache_metadata SET
    fetch_state = 'error',
    error_message = ?,
    retry_after = ?
WHERE actor = ? AND resource_kind = ? AND resource_key = ?
`

type MarkErrorParams struct {
	ErrorMessage sql.NullString
	RetryAfter   sql.NullString
	Actor        string
	ResourceKind string
	ResourceKey  string
}

func (q *Queries) MarkError(ctx context.Context, arg MarkErrorParams) error {
	_, err := q.db.ExecContext(ctx, markError,
		arg.ErrorMessage,
		arg.RetryAfter,
		arg.Actor,
		arg.ResourceKind,
		arg.ResourceKey,
	)
	return err
}

const markFetching = `-- name: MarkFetching :exec
UPDATE cache_metadata SET fetch_state = 'fetching'
WHERE actor = ? AND resource_kind = ? AND resource_key = ?
`

type MarkFetchingParams struct {
	Actor        string
	ResourceKind string
	ResourceKey  string
}

func (q *Queries) MarkFetching(ctx context.Context, arg MarkFetchingParams) error {
	_, err := q.db.ExecContext(ctx, markFetching, arg.Actor, arg.ResourceKind, arg.ResourceKey)
	return err
}

const markFresh = `-- name: MarkFresh :exec
UPDATE cache_metadata SET
    fetch_state = 'fresh',
    last_fetched_at = ?,
    etag = ?,
    expires_at = ?,
    error_message = NULL,
    retry_after = NULL
WHERE actor = ? AND resource_kind = ? AND resource_key = ?
`

type MarkFreshParams struct {
	LastFetchedAt sql.NullString
	Etag          sql.NullString
	ExpiresAt     sql.NullString
	Actor         string
	ResourceKind  string
	ResourceKey   string
}

func (q *Queries) MarkFresh(ctx context.Context, arg MarkFreshParams) error {
	_, err := q.db.ExecContext(ctx, markFresh,
		arg.LastFetchedAt,
		arg.Etag,
		arg.ExpiresAt,
		arg.Actor,
		arg.ResourceKind,
		arg.ResourceKey,
	)
	return err
}

const markStale = `-- name: MarkStale :exec
UPDATE cache_metadata SET fetch_state = 'stale'
WHERE actor = ? AND resource_kind = ? AND resource_key = ?
`

type MarkStaleParams struct {
	Actor        string
	ResourceKind string
	ResourceKey  string
}

func (q *Queries) MarkStale(ctx context.Context, arg MarkStaleParams) error {
	_, err := q.db.ExecContext(ctx, markStale, arg.Actor, arg.ResourceKind, arg.ResourceKey)
	return err
}

const markStaleByKindKey = `-- name: MarkStaleByKindKey :exec
UPDATE cache_metadata SET fetch_state = 'stale'
WHERE resource_kind = ? AND resource_key = ?
`

type MarkStaleByKindKeyParams struct {
	ResourceKind string
	ResourceKey  string
}

func (q *Queries) MarkStaleByKindKey(ctx context.Context, arg MarkStaleByKindKeyParams) error {
	_, err := q.db.ExecContext(ctx, markStaleByKindKey, arg.ResourceKind, arg.ResourceKey)
	return err
}

const markStaleByKindKeyPrefix = `-- name: MarkStaleByKindKeyPrefix :exec
UPDATE cache_metadata SET fetch_state = 'stale'
WHERE resource_kind = ?1 AND substr(resource_key, 1, length(?2)) = ?2
`

type MarkStaleByKindKeyPrefixParams struct {
	ResourceKind string
	KeyPrefix    interface{}
}

func (q *Queries) MarkStaleByKindKeyPrefix(ctx context.Context, arg MarkStaleByKindKeyPrefixParams) error {
	_, err := q.db.ExecContext(ctx, markStaleByKindKeyPrefix, arg.ResourceKind, arg.KeyPrefix)
	return err
}

const upsertCacheMetadata = `-- name: UpsertCacheMetadata :exec
INSERT INTO cache_metadata (actor, resource_kind, resource_key, last_fetched_at, last_changed_at, etag, expires_at, fetch_state, error_message, retry_after)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT (actor, resource_kind, resource_key) DO UPDATE SET
    last_fetched_at = excluded.last_fetched_at,
    last_changed_at = excluded.last_changed_at,
    etag = excluded.etag,
    expires_at = excluded.expires_at,
    fetch_state = excluded.fetch_state,
    error_message = excluded.error_message,
    retry_after = excluded.retry_after
`

type UpsertCacheMetadataParams struct {
	Actor         string
	ResourceKind  string
	ResourceKey   string
	LastFetchedAt sql.NullString
	LastChangedAt sql.NullString
	Etag          sql.NullString
	ExpiresAt     sql.NullString
	FetchState    string
	ErrorMessage  sql.NullString
	RetryAfter    sql.NullString
}

func (q *Queries) UpsertCacheMetadata(ctx context.Context, arg UpsertCacheMetadataParams) error {
	_, err := q.db.ExecContext(ctx, upsertCacheMetadata,
		arg.Actor,
		arg.ResourceKind,
		arg.ResourceKey,
		arg.LastFetchedAt,
		arg.LastChangedAt,
		arg.Etag,
		arg.ExpiresAt,
		arg.FetchState,
		arg.ErrorMessage,
		arg.RetryAfter,
	)
	return err
}
