// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: ghdata.sql

package dbgen

import (
	"context"
	"database/sql"
)

const deleteBranchComparison = `-- name: DeleteBranchComparison :exec
DELETE FROM branch_comparisons
WHERE actor = ? AND owner = ? AND repo = ? AND base_ref = ? AND head_ref = ?
`

type DeleteBranchComparisonParams struct {
	Actor   string
	Owner   string
	Repo    string
	BaseRef string
	HeadRef string
}

func (q *Queries) DeleteBranchComparison(ctx context.Context, arg DeleteBranchComparisonParams) error {
	_, err := q.db.ExecContext(ctx, deleteBranchComparison,
		arg.Actor,
		arg.Owner,
		arg.Repo,
		arg.BaseRef,
		arg.HeadRef,
	)
	return err
}

const deletePRFiles = `-- name: DeletePRFiles :exec
DELETE FROM pr_files WHERE actor = ? AND owner = ? AND repo = ? AND pr_number = ?
`

type DeletePRFilesParams struct {
	Actor    string
	Owner    string
	Repo     string
	PrNumber int64
}

func (q *Queries) DeletePRFiles(ctx context.Context, arg DeletePRFilesParams) error {
	_, err := q.db.ExecContext(ctx, deletePRFiles,
		arg.Actor,
		arg.Owner,
		arg.Repo,
		arg.PrNumber,
	)
	return err
}

const deletePRLabels = `-- name: DeletePRLabels :exec
DELETE FROM pr_labels WHERE actor = ? AND owner = ? AND repo = ? AND pr_number = ?
`

type DeletePRLabelsParams struct {
	Actor    string
	Owner    string
	Repo     string
	PrNumber int64
}

func (q *Queries) DeletePRLabels(ctx context.Context, arg DeletePRLabelsParams) error {
	_, err := q.db.ExecContext(ctx, deletePRLabels,
		arg.Actor,
		arg.Owner,
		arg.Repo,
		arg.PrNumber,
	)
	return err
}

const deletePRLabelsByRepo = `-- name: DeletePRLabelsByRepo :exec
DELETE FROM pr_labels WHERE actor = ? AND owner = ? AND repo = ?
`

type DeletePRLabelsByRepoParams struct {
	Actor string
	Owner string
	Repo  string
}

func (q *Queries) DeletePRLabelsByRepo(ctx context.Context, arg DeletePRLabelsByRepoParams) error {
	_, err := q.db.ExecContext(ctx, deletePRLabelsByRepo, arg.Actor, arg.Owner, arg.Repo)
	return err
}

const deletePullRequest = `-- name: DeletePullRequest :exec
DELETE FROM pull_requests WHERE actor = ? AND owner = ? AND repo = ? AND number = ?
`

type DeletePullRequestParams struct {
	Actor  string
	Owner  string
	Repo   string
	Number int64
}

func (q *Queries) DeletePullRequest(ctx context.Context, arg DeletePullRequestParams) error {
	_, err := q.db.ExecContext(ctx, deletePullRequest,
		arg.Actor,
		arg.Owner,
		arg.Repo,
		arg.Number,
	)
	return err
}

const deletePullRequestsByRepo = `-- name: DeletePullRequestsByRepo :exec
DELETE FROM pull_requests WHERE actor = ? AND owner = ? AND repo = ?
`

type DeletePullRequestsByRepoParams struct {
	Actor string
	Owner string
	Repo  string
}

func (q *Queries) DeletePullRequestsByRepo(ctx context.Context, arg DeletePullRequestsByRepoParams) error {
	_, err := q.db.ExecContext(ctx, deletePullRequestsByRepo, arg.Actor, arg.Owner, arg.Repo)
	return err
}

const deleteReposByOwner = `-- name: DeleteReposByOwner :exec
DELETE FROM repos WHERE actor = ? AND owner = ?
`

type DeleteReposByOwnerParams struct {
	Actor string
	Owner string
}

func (q *Queries) DeleteReposByOwner(ctx context.Context, arg DeleteReposByOwnerParams) error {
	_, err := q.db.ExecContext(ctx, deleteReposByOwner, arg.Actor, arg.Owner)
	return err
}

const deleteUserOrgMemberships = `-- name: DeleteUserOrgMemberships :exec
DELETE FROM user_org_memberships WHERE actor = ? AND user_login = ?
`

type DeleteUserOrgMembershipsParams struct {
	Actor     string
	UserLogin string
}

func (q *Queries) DeleteUserOrgMemberships(ctx context.Context, arg DeleteUserOrgMembershipsParams) error {
	_, err := q.db.ExecContext(ctx, deleteUserOrgMemberships, arg.Actor, arg.UserLogin)
	return err
}

const getBranchComparison = `-- name: GetBranchComparison :one
SELECT actor, owner, repo, base_ref, head_ref, ahead_by, behind_by FROM branch_comparisons
WHERE actor = ? AND owner = ? AND repo = ? AND base_ref = ? AND head_ref = ?
`

type GetBranchComparisonParams struct {
	Actor   string
	Owner   string
	Repo    string
	BaseRef string
	HeadRef string
}

func (q *Queries) GetBranchComparison(ctx context.Context, arg GetBranchComparisonParams) (BranchComparison, error) {
	row := q.db.QueryRowContext(ctx, getBranchComparison,
		arg.Actor,
		arg.Owner,
		arg.Repo,
		arg.BaseRef,
		arg.HeadRef,
	)
	var i BranchComparison
	err := row.Scan(
		&i.Actor,
		&i.Owner,
		&i.Repo,
		&i.BaseRef,
		&i.HeadRef,
		&i.AheadBy,
		&i.BehindBy,
	)
	return i, err
}

const getFirstUser = `-- name: GetFirstUser :one
SELECT actor, login, avatar_url, url FROM users WHERE actor = ? LIMIT 1
`

func (q *Queries) GetFirstUser(ctx context.Context, actor string) (User, error) {
	row := q.db.QueryRowContext(ctx, getFirstUser, actor)
	var i User
	err := row.Scan(
		&i.Actor,
		&i.Login,
		&i.AvatarUrl,
		&i.Url,
	)
	return i, err
}

const getOrg = `-- name: GetOrg :one
SELECT actor, login, avatar_url, url FROM orgs WHERE actor = ? AND login = ?
`

type GetOrgParams struct {
	Actor string
	Login string
}

func (q *Queries) GetOrg(ctx context.Context, arg GetOrgParams) (Org, error) {
	row := q.db.QueryRowContext(ctx, getOrg, arg.Actor, arg.Login)
	var i Org
	err := row.Scan(
		&i.Actor,
		&i.Login,
		&i.AvatarUrl,
		&i.Url,
	)
	return i, err
}

const getPullRequest = `-- name: GetPullRequest :one
SELECT actor, owner, repo, number, title, url, is_draft, state, created_at, updated_at, additions, deletions, mergeable, author_login, author_avatar, author_url, head_ref_name, base_ref_name, head_ref_oid, review_request_count, last_commit_status FROM pull_requests WHERE actor = ? AND owner = ? AND repo = ? AND number = ?
`

type GetPullRequestParams struct {
	Actor  string
	Owner  string
	Repo   string
	Number int64
}

func (q *Queries) GetPullRequest(ctx context.Context, arg GetPullRequestParams) (PullRequest, error) {
	row := q.db.QueryRowContext(ctx, getPullRequest,
		arg.Actor,
		arg.Owner,
		arg.Repo,
		arg.Number,
	)
	var i PullRequest
	err := row.Scan(
		&i.Actor,
		&i.Owner,
		&i.Repo,
		&i.Number,
		&i.Title,
		&i.Url,
		&i.IsDraft,
		&i.State,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Additions,
		&i.Deletions,
		&i.Mergeable,
		&i.AuthorLogin,
		&i.AuthorAvatar,
		&i.AuthorUrl,
		&i.HeadRefName,
		&i.BaseRefName,
		&i.HeadRefOid,
		&i.ReviewRequestCount,
		&i.LastCommitStatus,
	)
	return i, err
}

const getRepo = `-- name: GetRepo :one
SELECT actor, owner, name, name_with_owner, url, is_disabled, is_archived, pushed_at, default_branch, default_branch_status, owner_login, owner_avatar, owner_url FROM repos WHERE actor = ? AND owner = ? AND name = ?
`

type GetRepoParams struct {
	Actor string
	Owner string
	Name  string
}

func (q *Queries) GetRepo(ctx context.Context, arg GetRepoParams) (Repo, error) {
	row := q.db.QueryRowContext(ctx, getRepo, arg.Actor, arg.Owner, arg.Name)
	var i Repo
	err := row.Scan(
		&i.Actor,
		&i.Owner,
		&i.Name,
		&i.NameWithOwner,
		&i.Url,
		&i.IsDisabled,
		&i.IsArchived,
		&i.PushedAt,
		&i.DefaultBranch,
		&i.DefaultBranchStatus,
		&i.OwnerLogin,
		&i.OwnerAvatar,
		&i.OwnerUrl,
	)
	return i, err
}

const getUser = `-- name: GetUser :one
SELECT actor, login, avatar_url, url FROM users WHERE actor = ? AND login = ?
`

type GetUserParams struct {
	Actor string
	Login string
}

func (q *Queries) GetUser(ctx context.Context, arg GetUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, getUser, arg.Actor, arg.Login)
	var i User
	err := row.Scan(
		&i.Actor,
		&i.Login,
		&i.AvatarUrl,
		&i.Url,
	)
	return i, err
}

const insertPRFile = `-- name: InsertPRFile :exec

INSERT INTO pr_files (actor, owner, repo, pr_number, path, additions, deletions)
VALUES (?, ?, ?, ?, ?, ?, ?)
ON CONFLICT (actor, owner, repo, pr_number, path) DO UPDATE SET
    additions = excluded.additions,
    deletions = excluded.deletions
`

type InsertPRFileParams struct {
	Actor     string
	Owner     string
	Repo      string
	PrNumber  int64
	Path      string
	Additions int64
	Deletions int64
}

// ============================================================================
// PR Files
// ============================================================================
func (q *Queries) InsertPRFile(ctx context.Context, arg InsertPRFileParams) error {
	_, err := q.db.ExecContext(ctx, insertPRFile,
		arg.Actor,
		arg.Owner,
		arg.Repo,
		arg.PrNumber,
		arg.Path,
		arg.Additions,
		arg.Deletions,
	)
	return err
}

const insertPRLabel = `-- name: InsertPRLabel :exec

INSERT INTO pr_labels (actor, owner, repo, pr_number, name, color)
VALUES (?, ?, ?, ?, ?, ?)
ON CONFLICT (actor, owner, repo, pr_number, name) DO UPDATE SET
    color = excluded.color
`

type InsertPRLabelParams struct {
	Actor    string
	Owner    string
	Repo     string
	PrNumber int64
	Name     string
	Color    string
}

// ============================================================================
// PR Labels
// ============================================================================
func (q *Queries) InsertPRLabel(ctx context.Context, arg InsertPRLabelParams) error {
	_, err := q.db.ExecContext(ctx, insertPRLabel,
		arg.Actor,
		arg.Owner,
		arg.Repo,
		arg.PrNumber,
		arg.Name,
		arg.Color,
	)
	return err
}

const listOpenPullRequestsByOwner = `-- name: ListOpenPullRequestsByOwner :many
SELECT actor, owner, repo, number, title, url, is_draft, state, created_at, updated_at, additions, deletions, mergeable, author_login, author_avatar, author_url, head_ref_name, base_ref_name, head_ref_oid, review_request_count, last_commit_status FROM pull_requests
WHERE actor = ? AND owner = ? AND state = 'OPEN'
ORDER BY repo, number
`

type ListOpenPullRequestsByOwnerParams struct {
	Actor string
	Owner string
}

func (q *Queries) ListOpenPullRequestsByOwner(ctx context.Context, arg ListOpenPullRequestsByOwnerParams) ([]PullRequest, error) {
	rows, err := q.db.QueryContext(ctx, listOpenPullRequestsByOwner, arg.Actor, arg.Owner)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PullRequest
	for rows.Next() {
		var i PullRequest
		if err := rows.Scan(
			&i.Actor,
			&i.Owner,
			&i.Repo,
			&i.Number,
			&i.Title,
			&i.Url,
			&i.IsDraft,
			&i.State,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Additions,
			&i.Deletions,
			&i.Mergeable,
			&i.AuthorLogin,
			&i.AuthorAvatar,
			&i.AuthorUrl,
			&i.HeadRefName,
			&i.BaseRefName,
			&i.HeadRefOid,
			&i.ReviewRequestCount,
			&i.LastCommitStatus,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOpenPullRequestsByRepo = `-- name: ListOpenPullRequestsByRepo :many
SELECT actor, owner, repo, number, title, url, is_draft, state, created_at, updated_at, additions, deletions, mergeable, author_login, author_avatar, author_url, head_ref_name, base_ref_name, head_ref_oid, review_request_count, last_commit_status FROM pull_requests
WHERE actor = ? AND owner = ? AND repo = ? AND state = 'OPEN'
ORDER BY number
`

type ListOpenPullRequestsByRepoParams struct {
	Actor string
	Owner string
	Repo  string
}

func (q *Queries) ListOpenPullRequestsByRepo(ctx context.Context, arg ListOpenPullRequestsByRepoParams) ([]PullRequest, error) {
	rows, err := q.db.QueryContext(ctx, listOpenPullRequestsByRepo, arg.Actor, arg.Owner, arg.Repo)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PullRequest
	for rows.Next() {
		var i PullRequest
		if err := rows.Scan(
			&i.Actor,
			&i.Owner,
			&i.Repo,
			&i.Number,
			&i.Title,
			&i.Url,
			&i.IsDraft,
			&i.State,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Additions,
			&i.Deletions,
			&i.Mergeable,
			&i.AuthorLogin,
			&i.AuthorAvatar,
			&i.AuthorUrl,
			&i.HeadRefName,
			&i.BaseRefName,
			&i.HeadRefOid,
			&i.ReviewRequestCount,
			&i.LastCommitStatus,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrgs = `-- name: ListOrgs :many
SELECT actor, login, avatar_url, url FROM orgs WHERE actor = ? ORDER BY login
`

func (q *Queries) ListOrgs(ctx context.Context, actor string) ([]Org, error) {
	rows, err := q.db.QueryContext(ctx, listOrgs, actor)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Org
	for rows.Next() {
		var i Org
		if err := rows.Scan(
			&i.Actor,
			&i.Login,
			&i.AvatarUrl,
			&i.Url,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPRFiles = `-- name: ListPRFiles :many
SELECT actor, owner, repo, pr_number, path, additions, deletions FROM pr_files WHERE actor = ? AND owner = ? AND repo = ? AND pr_number = ?
`

type ListPRFilesParams struct {
	Actor    string
	Owner    string
	Repo     string
	PrNumber int64
}

func (q *Queries) ListPRFiles(ctx context.Context, arg ListPRFilesParams) ([]PrFile, error) {
	rows, err := q.db.QueryContext(ctx, listPRFiles,
		arg.Actor,
		arg.Owner,
		arg.Repo,
		arg.PrNumber,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PrFile
	for rows.Next() {
		var i PrFile
		if err := rows.Scan(
			&i.Actor,
			&i.Owner,
			&i.Repo,
			&i.PrNumber,
			&i.Path,
			&i.Additions,
			&i.Deletions,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPRLabels = `-- name: ListPRLabels :many
SELECT actor, owner, repo, pr_number, name, color FROM pr_labels WHERE actor = ? AND owner = ? AND repo = ? AND pr_number = ?
`

type ListPRLabelsParams struct {
	Actor    string
	Owner    string
	Repo     string
	PrNumber int64
}

func (q *Queries) ListPRLabels(ctx context.Context, arg ListPRLabelsParams) ([]PrLabel, error) {
	rows, err := q.db.QueryContext(ctx, listPRLabels,
		arg.Actor,
		arg.Owner,
		arg.Repo,
		arg.PrNumber,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PrLabel
	for rows.Next() {
		var i PrLabel
		if err := rows.Scan(
			&i.Actor,
			&i.Owner,
			&i.Repo,
			&i.PrNumber,
			&i.Name,
			&i.Color,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReposByOwner = `-- name: ListReposByOwner :many
SELECT actor, owner, name, name_with_owner, url, is_disabled, is_archived, pushed_at, default_branch, default_branch_status, owner_login, owner_avatar, owner_url FROM repos WHERE actor = ? AND owner = ? ORDER BY name
`

type ListReposByOwnerParams struct {
	Actor string
	Owner string
}

func (q *Queries) ListReposByOwner(ctx context.Context, arg ListReposByOwnerParams) ([]Repo, error) {
	rows, err := q.db.QueryContext(ctx, listReposByOwner, arg.Actor, arg.Owner)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Repo
	for rows.Next() {
		var i Repo
		if err := rows.Scan(
			&i.Actor,
			&i.Owner,
			&i.Name,
			&i.NameWithOwner,
			&i.Url,
			&i.IsDisabled,
			&i.IsArchived,
			&i.PushedAt,
			&i.DefaultBranch,
			&i.DefaultBranchStatus,
			&i.OwnerLogin,
			&i.OwnerAvatar,
			&i.OwnerUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserOrgMemberships = `-- name: ListUserOrgMemberships :many
SELECT org_login FROM user_org_memberships WHERE actor = ? AND user_login = ?
`

type ListUserOrgMembershipsParams struct {
	Actor     string
	UserLogin string
}

func (q *Queries) ListUserOrgMemberships(ctx context.Context, arg ListUserOrgMembershipsParams) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listUserOrgMemberships, arg.Actor, arg.UserLogin)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var org_login string
		if err := rows.Scan(&org_login); err != nil {
			return nil, err
		}
		items = append(items, org_login)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setUserOrgMembership = `-- name: SetUserOrgMembership :exec

INSERT INTO user_org_memberships (actor, user_login, org_login)
VALUES (?, ?, ?)
ON CONFLICT (actor, user_login, org_login) DO NOTHING
`

type SetUserOrgMembershipParams struct {
	Actor     string
	UserLogin string
	OrgLogin  string
}

// ============================================================================
// User Org Memberships
// ============================================================================
func (q *Queries) SetUserOrgMembership(ctx context.Context, arg SetUserOrgMembershipParams) error {
	_, err := q.db.ExecContext(ctx, setUserOrgMembership, arg.Actor, arg.UserLogin, arg.OrgLogin)
	return err
}

const upsertBranchComparison = `-- name: UpsertBranchComparison :exec

INSERT INTO branch_comparisons (actor, owner, repo, base_ref, head_ref, ahead_by, behind_by)
VALUES (?, ?, ?, ?, ?, ?, ?)
ON CONFLICT (actor, owner, repo, base_ref, head_ref) DO UPDATE SET
    ahead_by = excluded.ahead_by,
    behind_by = excluded.behind_by
`

type UpsertBranchComparisonParams struct {
	Actor    string
	Owner    string
	Repo     string
	BaseRef  string
	HeadRef  string
	AheadBy  int64
	BehindBy int64
}

// ============================================================================
// Branch Comparisons
// ============================================================================
func (q *Queries) UpsertBranchComparison(ctx context.Context, arg UpsertBranchComparisonParams) error {
	_, err := q.db.ExecContext(ctx, upsertBranchComparison,
		arg.Actor,
		arg.Owner,
		arg.Repo,
		arg.BaseRef,
		arg.HeadRef,
		arg.AheadBy,
		arg.BehindBy,
	)
	return err
}

const upsertOrg = `-- name: UpsertOrg :exec

INSERT INTO orgs (actor, login, avatar_url, url)
VALUES (?, ?, ?, ?)
ON CONFLICT (actor, login) DO UPDATE SET
    avatar_url = excluded.avatar_url,
    url = excluded.url
`

type UpsertOrgParams struct {
	Actor     string
	Login     string
	AvatarUrl sql.NullString
	Url       sql.NullString
}

// ============================================================================
// Orgs
// ============================================================================
func (q *Queries) UpsertOrg(ctx context.Context, arg UpsertOrgParams) error {
	_, err := q.db.ExecContext(ctx, upsertOrg,
		arg.Actor,
		arg.Login,
		arg.AvatarUrl,
		arg.Url,
	)
	return err
}

const upsertPullRequest = `-- name: UpsertPullRequest :exec

INSERT INTO pull_requests (actor, owner, repo, number, title, url, is_draft, state, created_at, updated_at, additions, deletions, mergeable, author_login, author_avatar, author_url, head_ref_name, base_ref_name, head_ref_oid, review_request_count, last_commit_status)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT (actor, owner, repo, number) DO UPDATE SET
    title = excluded.title,
    url = excluded.url,
    is_draft = excluded.is_draft,
    state = excluded.state,
    created_at = excluded.created_at,
    updated_at = excluded.updated_at,
    additions = excluded.additions,
    deletions = excluded.deletions,
    mergeable = excluded.mergeable,
    author_login = excluded.author_login,
    author_avatar = excluded.author_avatar,
    author_url = excluded.author_url,
    head_ref_name = excluded.head_ref_name,
    base_ref_name = excluded.base_ref_name,
    head_ref_oid = excluded.head_ref_oid,
    review_request_count = excluded.review_request_count,
    last_commit_status = excluded.last_commit_status
`

type UpsertPullRequestParams struct {
	Actor              string
	Owner              string
	Repo               string
	Number             int64
	Title              string
	Url                string
	IsDraft            int64
	State              string
	CreatedAt          string
	UpdatedAt          string
	Additions          sql.NullInt64
	Deletions          sql.NullInt64
	Mergeable          sql.NullString
	AuthorLogin        sql.NullString
	AuthorAvatar       sql.NullString
	AuthorUrl          sql.NullString
	HeadRefName        sql.NullString
	BaseRefName        sql.NullString
	HeadRefOid         sql.NullString
	ReviewRequestCount sql.NullInt64
	LastCommitStatus   sql.NullString
}

// ============================================================================
// Pull Requests
// ============================================================================
func (q *Queries) UpsertPullRequest(ctx context.Context, arg UpsertPullRequestParams) error {
	_, err := q.db.ExecContext(ctx, upsertPullRequest,
		arg.Actor,
		arg.Owner,
		arg.Repo,
		arg.Number,
		arg.Title,
		arg.Url,
		arg.IsDraft,
		arg.State,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.Additions,
		arg.Deletions,
		arg.Mergeable,
		arg.AuthorLogin,
		arg.AuthorAvatar,
		arg.AuthorUrl,
		arg.HeadRefName,
		arg.BaseRefName,
		arg.HeadRefOid,
		arg.ReviewRequestCount,
		arg.LastCommitStatus,
	)
	return err
}

const upsertRepo = `-- name: UpsertRepo :exec

INSERT INTO repos (actor, owner, name, name_with_owner, url, is_disabled, is_archived, pushed_at, default_branch, default_branch_status, owner_login, owner_avatar, owner_url)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT (actor, owner, name) DO UPDATE SET
    name_with_owner = excluded.name_with_owner,
    url = excluded.url,
    is_disabled = excluded.is_disabled,
    is_archived = excluded.is_archived,
    pushed_at = excluded.pushed_at,
    default_branch = excluded.default_branch,
    default_branch_status = excluded.default_branch_status,
    owner_login = excluded.owner_login,
    owner_avatar = excluded.owner_avatar,
    owner_url = excluded.owner_url
`

type UpsertRepoParams struct {
	Actor               string
	Owner               string
	Name                string
	NameWithOwner       string
	Url                 string
	IsDisabled          int64
	IsArchived          int64
	PushedAt            sql.NullString
	DefaultBranch       sql.NullString
	DefaultBranchStatus sql.NullString
	OwnerLogin          sql.NullString
	OwnerAvatar         sql.NullString
	OwnerUrl            sql.NullString
}

// ============================================================================
// Repos
// ============================================================================
func (q *Queries) UpsertRepo(ctx context.Context, arg UpsertRepoParams) error {
	_, err := q.db.ExecContext(ctx, upsertRepo,
		arg.Actor,
		arg.Owner,
		arg.Name,
		arg.NameWithOwner,
		arg.Url,
		arg.IsDisabled,
		arg.IsArchived,
		arg.PushedAt,
		arg.DefaultBranch,
		arg.DefaultBranchStatus,
		arg.OwnerLogin,
		arg.OwnerAvatar,
		arg.OwnerUrl,
	)
	return err
}

const upsertUser = `-- name: UpsertUser :exec

INSERT INTO users (actor, login, avatar_url, url)
VALUES (?, ?, ?, ?)
ON CONFLICT (actor, login) DO UPDATE SET
    avatar_url = excluded.avatar_url,
    url = excluded.url
`

type UpsertUserParams struct {
	Actor     string
	Login     string
	AvatarUrl string
	Url       string
}

// ============================================================================
// Users
// ============================================================================
func (q *Queries) UpsertUser(ctx context.Context, arg UpsertUserParams) error {
	_, err := q.db.ExecContext(ctx, upsertUser,
		arg.Actor,
		arg.Login,
		arg.AvatarUrl,
		arg.Url,
	)
	return err
}
