// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package dbgen

import (
	"database/sql"
)

type AccessGrant struct {
	Principal string
	Owner     string
	Repo      string
	GrantedAt string
	ExpiresAt string
	Source    string
}

type ActorIdentity struct {
	Actor     string
	Login     string
	FirstSeen string
	LastSeen  string
}

type BranchesListCache struct {
	ID         int64
	Owner      string
	Repo       string
	PerPage    int64
	Page       int64
	Doc        string
	FetchedAt  string
	ExpiresAt  string
	LastUsedAt string
}

type CacheMetadatum struct {
	Actor         string
	ResourceKind  string
	ResourceKey   string
	LastFetchedAt sql.NullString
	LastChangedAt sql.NullString
	Etag          sql.NullString
	ExpiresAt     sql.NullString
	FetchState    string
	ErrorMessage  sql.NullString
	RetryAfter    sql.NullString
}

type CacheRefreshLog struct {
	ID             int64
	Actor          string
	ResourceKind   string
	ResourceKey    string
	TriggeredBy    string
	StartedAt      string
	CompletedAt    sql.NullString
	Success        sql.NullInt64
	RecordsChanged sql.NullInt64
	ErrorMessage   sql.NullString
}

type ClosedPullCache struct {
	ID         int64
	Owner      string
	Repo       string
	Number     int64
	Doc        string
	FetchedAt  string
	ExpiresAt  string
	LastUsedAt string
}

type CommitCheck struct {
	Owner   string
	Repo    string
	Sha     string
	Context string
	State   string
}

type CommitCiCache struct {
	ID         int64
	Owner      string
	Repo       string
	Ref        string
	Kind       string
	PerPage    int64
	Page       int64
	Doc        string
	FetchedAt  string
	ExpiresAt  string
	LastUsedAt string
}

type CommitsListCache struct {
	ID         int64
	Owner      string
	Repo       string
	RefParam   string
	PerPage    int64
	Page       int64
	Shas       string
	FetchedAt  string
	ExpiresAt  string
	LastUsedAt string
}

type CompareCache struct {
	ID         int64
	Owner      string
	Repo       string
	Basehead   string
	BaseRef    string
	HeadRef    string
	Status     int64
	Doc        string
	FetchedAt  string
	ExpiresAt  string
	LastUsedAt string
}

type ContentsCache struct {
	ID         int64
	Owner      string
	Repo       string
	Path       string
	Ref        string
	Kind       string
	Name       string
	Sha        string
	Size       int64
	Encoding   string
	Content    string
	Entries    string
	Message    string
	FetchedAt  string
	ExpiresAt  string
	LastUsedAt string
}

type DenyCache struct {
	Principal    string
	ResourceKind string
	ResourceKey  string
	Owner        string
	Repo         string
	Status       int64
	Message      string
	DeniedAt     string
	ExpiresAt    string
}

type GitCommitMissCache struct {
	ID         int64
	Owner      string
	Repo       string
	Sha        string
	Doc        string
	FetchedAt  string
	ExpiresAt  string
	LastUsedAt string
}

type GitCommitsCache struct {
	ID             int64
	Owner          string
	Repo           string
	Sha            string
	Message        string
	AuthorName     string
	AuthorEmail    string
	AuthorDate     string
	CommitterName  string
	CommitterEmail string
	CommitterDate  string
	TreeSha        string
	Parents        string
	FetchedAt      string
	LastUsedAt     string
}

type InstallTokenCache struct {
	ID                  int64
	Actor               string
	InstallationID      string
	BodyHash            string
	Token               string
	TokenExpiresAt      string
	Permissions         string
	RepositorySelection string
	FetchedAt           string
	ExpiresAt           string
	LastUsedAt          string
}

type PrLabel struct {
	Owner    string
	Repo     string
	PrNumber int64
	Name     string
	Color    string
}

type PullDiff406Cache struct {
	ID         int64
	Owner      string
	Repo       string
	Number     int64
	Doc        string
	FetchedAt  string
	ExpiresAt  string
	LastUsedAt string
}

type PullFilesCache struct {
	ID         int64
	Owner      string
	Repo       string
	Number     int64
	PerPage    int64
	Page       int64
	Doc        string
	FetchedAt  string
	ExpiresAt  string
	LastUsedAt string
}

type PullRequest struct {
	Owner              string
	Repo               string
	Number             int64
	Title              string
	Url                string
	IsDraft            int64
	State              string
	CreatedAt          string
	UpdatedAt          string
	Additions          sql.NullInt64
	Deletions          sql.NullInt64
	Mergeable          sql.NullString
	AuthorLogin        sql.NullString
	AuthorAvatar       sql.NullString
	AuthorUrl          sql.NullString
	HeadRefName        sql.NullString
	BaseRefName        sql.NullString
	HeadRefOid         sql.NullString
	ReviewRequestCount sql.NullInt64
	LastCommitStatus   sql.NullString
	NodeID             sql.NullString
	Body               sql.NullString
	AuthorType         sql.NullString
	BaseRefOid         sql.NullString
	HeadRepoFullName   sql.NullString
	AutoMergeMethod    sql.NullString
	MergeCommitSha     sql.NullString
	TouchedAt          string
}

type PullsListCache struct {
	ID         int64
	Owner      string
	Repo       string
	FetchedAt  string
	ExpiresAt  string
	LastUsedAt string
}

type Repo struct {
	Owner               string
	Name                string
	NameWithOwner       string
	Url                 string
	IsDisabled          int64
	IsArchived          int64
	Visibility          string
	PushedAt            sql.NullString
	DefaultBranch       sql.NullString
	DefaultBranchStatus sql.NullString
	OwnerLogin          sql.NullString
	OwnerAvatar         sql.NullString
	OwnerUrl            sql.NullString
}

type RepoInstallationCache struct {
	ID                  int64
	Actor               string
	Owner               string
	Repo                string
	InstallationID      int64
	AccountLogin        string
	AccountType         string
	RepositorySelection string
	AppID               int64
	AppSlug             string
	TargetType          string
	FetchedAt           string
	ExpiresAt           string
	LastUsedAt          string
}

type SchemaVersion struct {
	Version int64
}

type WebhookDelivery struct {
	ID          int64
	DeliveryID  string
	EventType   string
	Action      string
	Repo        string
	ReceivedAt  string
	Disposition string
	Detail      string
}

type WorkflowJob struct {
	Owner        string
	Repo         string
	JobID        int64
	RunID        int64
	RunAttempt   int64
	Name         string
	WorkflowName string
	Status       string
	Conclusion   string
	HeadSha      string
	HeadBranch   string
	HtmlUrl      string
	StartedAt    string
	CompletedAt  string
	RunnerName   string
	UpdatedAt    string
}

type WorkflowRunsCache struct {
	ID         int64
	Owner      string
	Repo       string
	HeadSha    string
	PerPage    int64
	Page       int64
	Doc        string
	FetchedAt  string
	ExpiresAt  string
	LastUsedAt string
}
