// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package dbgen

import (
	"database/sql"
)

type BranchComparison struct {
	Owner    string
	Repo     string
	BaseRef  string
	HeadRef  string
	AheadBy  int64
	BehindBy int64
}

type CacheMetadatum struct {
	ResourceKind  string
	ResourceKey   string
	LastFetchedAt sql.NullString
	LastChangedAt sql.NullString
	Etag          sql.NullString
	ExpiresAt     sql.NullString
	FetchState    string
	ErrorMessage  sql.NullString
	RetryAfter    sql.NullString
}

type CacheRefreshLog struct {
	ID             int64
	ResourceKind   string
	ResourceKey    string
	TriggeredBy    string
	StartedAt      string
	CompletedAt    sql.NullString
	Success        sql.NullInt64
	RecordsChanged sql.NullInt64
	ErrorMessage   sql.NullString
}

type Org struct {
	Login     string
	AvatarUrl sql.NullString
	Url       sql.NullString
}

type PrFile struct {
	Owner     string
	Repo      string
	PrNumber  int64
	Path      string
	Additions int64
	Deletions int64
}

type PrLabel struct {
	Owner    string
	Repo     string
	PrNumber int64
	Name     string
	Color    string
}

type PullRequest struct {
	Owner              string
	Repo               string
	Number             int64
	Title              string
	Url                string
	IsDraft            int64
	State              string
	CreatedAt          string
	UpdatedAt          string
	Additions          sql.NullInt64
	Deletions          sql.NullInt64
	Mergeable          sql.NullString
	AuthorLogin        sql.NullString
	AuthorAvatar       sql.NullString
	AuthorUrl          sql.NullString
	HeadRefName        sql.NullString
	BaseRefName        sql.NullString
	HeadRefOid         sql.NullString
	ReviewRequestCount sql.NullInt64
	LastCommitStatus   sql.NullString
}

type Repo struct {
	Owner               string
	Name                string
	NameWithOwner       string
	Url                 string
	IsDisabled          int64
	IsArchived          int64
	PushedAt            sql.NullString
	DefaultBranch       sql.NullString
	DefaultBranchStatus sql.NullString
	OwnerLogin          sql.NullString
	OwnerAvatar         sql.NullString
	OwnerUrl            sql.NullString
}

type SchemaVersion struct {
	Version int64
}

type User struct {
	Login     string
	AvatarUrl string
	Url       string
}

type UserOrgMembership struct {
	UserLogin string
	OrgLogin  string
}
