// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: respcache.sql

package dbgen

import (
	"context"
)

const deleteCommitsListCacheByRepo = `-- name: DeleteCommitsListCacheByRepo :exec
DELETE FROM commits_list_cache WHERE owner = ? AND repo = ?
`

type DeleteCommitsListCacheByRepoParams struct {
	Owner string
	Repo  string
}

// DeleteCommitsListCacheByRepo drops a repo's snapshots -- the push/repository
// webhook flush (a push moves every ref-relative listing). The absorbed
// git_commits_cache rows are immutable and stay.
func (q *Queries) DeleteCommitsListCacheByRepo(ctx context.Context, arg DeleteCommitsListCacheByRepoParams) error {
	_, err := q.db.ExecContext(ctx, deleteCommitsListCacheByRepo, arg.Owner, arg.Repo)
	return err
}

const deleteCompareCacheByRepo = `-- name: DeleteCompareCacheByRepo :exec
DELETE FROM compare_cache WHERE owner = ? AND repo = ?
`

type DeleteCompareCacheByRepoParams struct {
	Owner string
	Repo  string
}

// DeleteCompareCacheByRepo drops a repo's compare docs -- the push/repository
// webhook flush (a push to either side of any basehead can change the
// comparison, so the whole repo flushes).
func (q *Queries) DeleteCompareCacheByRepo(ctx context.Context, arg DeleteCompareCacheByRepoParams) error {
	_, err := q.db.ExecContext(ctx, deleteCompareCacheByRepo, arg.Owner, arg.Repo)
	return err
}

const deleteContentsCacheByRepo = `-- name: DeleteContentsCacheByRepo :exec
DELETE FROM contents_cache WHERE owner = ? AND repo = ?
`

type DeleteContentsCacheByRepoParams struct {
	Owner string
	Repo  string
}

func (q *Queries) DeleteContentsCacheByRepo(ctx context.Context, arg DeleteContentsCacheByRepoParams) error {
	_, err := q.db.ExecContext(ctx, deleteContentsCacheByRepo, arg.Owner, arg.Repo)
	return err
}

const deleteExpiredCommitsListCache = `-- name: DeleteExpiredCommitsListCache :exec
DELETE FROM commits_list_cache WHERE expires_at <= ?
`

func (q *Queries) DeleteExpiredCommitsListCache(ctx context.Context, expiresAt string) error {
	_, err := q.db.ExecContext(ctx, deleteExpiredCommitsListCache, expiresAt)
	return err
}

const deleteExpiredCompareCache = `-- name: DeleteExpiredCompareCache :exec
DELETE FROM compare_cache WHERE expires_at <= ?
`

func (q *Queries) DeleteExpiredCompareCache(ctx context.Context, expiresAt string) error {
	_, err := q.db.ExecContext(ctx, deleteExpiredCompareCache, expiresAt)
	return err
}

const deleteExpiredContentsCache = `-- name: DeleteExpiredContentsCache :exec
DELETE FROM contents_cache WHERE expires_at <= ?
`

func (q *Queries) DeleteExpiredContentsCache(ctx context.Context, expiresAt string) error {
	_, err := q.db.ExecContext(ctx, deleteExpiredContentsCache, expiresAt)
	return err
}

const deleteExpiredInstallTokenCache = `-- name: DeleteExpiredInstallTokenCache :exec
DELETE FROM install_token_cache WHERE expires_at <= ?
`

func (q *Queries) DeleteExpiredInstallTokenCache(ctx context.Context, expiresAt string) error {
	_, err := q.db.ExecContext(ctx, deleteExpiredInstallTokenCache, expiresAt)
	return err
}

const deleteExpiredPullsListMarkers = `-- name: DeleteExpiredPullsListMarkers :exec
DELETE FROM pulls_list_cache WHERE expires_at <= ?
`

func (q *Queries) DeleteExpiredPullsListMarkers(ctx context.Context, expiresAt string) error {
	_, err := q.db.ExecContext(ctx, deleteExpiredPullsListMarkers, expiresAt)
	return err
}

const deleteExpiredRepoInstallationCache = `-- name: DeleteExpiredRepoInstallationCache :exec
DELETE FROM repo_installation_cache WHERE expires_at <= ?
`

func (q *Queries) DeleteExpiredRepoInstallationCache(ctx context.Context, expiresAt string) error {
	_, err := q.db.ExecContext(ctx, deleteExpiredRepoInstallationCache, expiresAt)
	return err
}

const deleteInstallTokenCacheByInstallation = `-- name: DeleteInstallTokenCacheByInstallation :exec
DELETE FROM install_token_cache WHERE installation_id = ?
`

func (q *Queries) DeleteInstallTokenCacheByInstallation(ctx context.Context, installationID string) error {
	_, err := q.db.ExecContext(ctx, deleteInstallTokenCacheByInstallation, installationID)
	return err
}

const deletePullsListMarkersByRepo = `-- name: DeletePullsListMarkersByRepo :exec
DELETE FROM pulls_list_cache WHERE owner = ? AND repo = ?
`

type DeletePullsListMarkersByRepoParams struct {
	Owner string
	Repo  string
}

// DeletePullsListMarkersByRepo drops the marker on structural events
// (repository renamed/deleted/etc.), NOT on pull_request events (those
// maintain rows and leave the marker).
func (q *Queries) DeletePullsListMarkersByRepo(ctx context.Context, arg DeletePullsListMarkersByRepoParams) error {
	_, err := q.db.ExecContext(ctx, deletePullsListMarkersByRepo, arg.Owner, arg.Repo)
	return err
}

const deleteRepoInstallationCacheByInstallation = `-- name: DeleteRepoInstallationCacheByInstallation :exec
DELETE FROM repo_installation_cache WHERE installation_id = ?
`

func (q *Queries) DeleteRepoInstallationCacheByInstallation(ctx context.Context, installationID int64) error {
	_, err := q.db.ExecContext(ctx, deleteRepoInstallationCacheByInstallation, installationID)
	return err
}

const getCommitsListCache = `-- name: GetCommitsListCache :one

SELECT id, owner, repo, ref_param, per_page, page, shas, fetched_at, expires_at, last_used_at FROM commits_list_cache
WHERE owner = ? AND repo = ? AND ref_param = ? AND per_page = ? AND page = ?
`

type GetCommitsListCacheParams struct {
	Owner    string
	Repo     string
	RefParam string
	PerPage  int64
	Page     int64
}

// ---- commits_list_cache (per-page snapshots for the commits LIST route) ----
func (q *Queries) GetCommitsListCache(ctx context.Context, arg GetCommitsListCacheParams) (CommitsListCache, error) {
	row := q.db.QueryRowContext(ctx, getCommitsListCache,
		arg.Owner,
		arg.Repo,
		arg.RefParam,
		arg.PerPage,
		arg.Page,
	)
	var i CommitsListCache
	err := row.Scan(
		&i.ID,
		&i.Owner,
		&i.Repo,
		&i.RefParam,
		&i.PerPage,
		&i.Page,
		&i.Shas,
		&i.FetchedAt,
		&i.ExpiresAt,
		&i.LastUsedAt,
	)
	return i, err
}

const getCompareCache = `-- name: GetCompareCache :one

SELECT id, owner, repo, basehead, doc, fetched_at, expires_at, last_used_at FROM compare_cache
WHERE owner = ? AND repo = ? AND basehead = ?
`

type GetCompareCacheParams struct {
	Owner    string
	Repo     string
	Basehead string
}

// ---- compare_cache (GET /repos/{owner}/{repo}/compare/{basehead}) ----
func (q *Queries) GetCompareCache(ctx context.Context, arg GetCompareCacheParams) (CompareCache, error) {
	row := q.db.QueryRowContext(ctx, getCompareCache, arg.Owner, arg.Repo, arg.Basehead)
	var i CompareCache
	err := row.Scan(
		&i.ID,
		&i.Owner,
		&i.Repo,
		&i.Basehead,
		&i.Doc,
		&i.FetchedAt,
		&i.ExpiresAt,
		&i.LastUsedAt,
	)
	return i, err
}

const getContentsCache = `-- name: GetContentsCache :one


SELECT id, owner, repo, path, ref, kind, name, sha, size, encoding, content, entries, message, fetched_at, expires_at, last_used_at FROM contents_cache
WHERE owner = ? AND repo = ? AND path = ? AND ref = ?
`

type GetContentsCacheParams struct {
	Owner string
	Repo  string
	Path  string
	Ref   string
}

// ============================================================================
// Cached-route response state (contents / git commits / installation tokens)
// ============================================================================
//
// contents_cache and git_commits_cache are GLOBAL truth (one row per resource);
// whether a caller may read a row is the reveal layer's job (see the
// access_grants queries in ghdata.sql). install_token_cache and
// repo_installations stay keyed by the verified app identity: they cache
// app-specific answers (a minted credential; which installation covers a
// repo), not shared GitHub state.
// ---- contents_cache ----
func (q *Queries) GetContentsCache(ctx context.Context, arg GetContentsCacheParams) (ContentsCache, error) {
	row := q.db.QueryRowContext(ctx, getContentsCache,
		arg.Owner,
		arg.Repo,
		arg.Path,
		arg.Ref,
	)
	var i ContentsCache
	err := row.Scan(
		&i.ID,
		&i.Owner,
		&i.Repo,
		&i.Path,
		&i.Ref,
		&i.Kind,
		&i.Name,
		&i.Sha,
		&i.Size,
		&i.Encoding,
		&i.Content,
		&i.Entries,
		&i.Message,
		&i.FetchedAt,
		&i.ExpiresAt,
		&i.LastUsedAt,
	)
	return i, err
}

const getGitCommitCache = `-- name: GetGitCommitCache :one

SELECT id, owner, repo, sha, message, author_name, author_email, author_date, committer_name, committer_email, committer_date, tree_sha, parents, fetched_at, last_used_at FROM git_commits_cache
WHERE owner = ? AND repo = ? AND sha = ?
`

type GetGitCommitCacheParams struct {
	Owner string
	Repo  string
	Sha   string
}

// ---- git_commits_cache ----
func (q *Queries) GetGitCommitCache(ctx context.Context, arg GetGitCommitCacheParams) (GitCommitsCache, error) {
	row := q.db.QueryRowContext(ctx, getGitCommitCache, arg.Owner, arg.Repo, arg.Sha)
	var i GitCommitsCache
	err := row.Scan(
		&i.ID,
		&i.Owner,
		&i.Repo,
		&i.Sha,
		&i.Message,
		&i.AuthorName,
		&i.AuthorEmail,
		&i.AuthorDate,
		&i.CommitterName,
		&i.CommitterEmail,
		&i.CommitterDate,
		&i.TreeSha,
		&i.Parents,
		&i.FetchedAt,
		&i.LastUsedAt,
	)
	return i, err
}

const getInstallTokenCache = `-- name: GetInstallTokenCache :one

SELECT id, actor, installation_id, body_hash, token, token_expires_at, permissions, repository_selection, fetched_at, expires_at, last_used_at FROM install_token_cache
WHERE actor = ? AND installation_id = ? AND body_hash = ?
`

type GetInstallTokenCacheParams struct {
	Actor          string
	InstallationID string
	BodyHash       string
}

// ---- install_token_cache ----
func (q *Queries) GetInstallTokenCache(ctx context.Context, arg GetInstallTokenCacheParams) (InstallTokenCache, error) {
	row := q.db.QueryRowContext(ctx, getInstallTokenCache, arg.Actor, arg.InstallationID, arg.BodyHash)
	var i InstallTokenCache
	err := row.Scan(
		&i.ID,
		&i.Actor,
		&i.InstallationID,
		&i.BodyHash,
		&i.Token,
		&i.TokenExpiresAt,
		&i.Permissions,
		&i.RepositorySelection,
		&i.FetchedAt,
		&i.ExpiresAt,
		&i.LastUsedAt,
	)
	return i, err
}

const getPullsListMarker = `-- name: GetPullsListMarker :one

SELECT id, owner, repo, fetched_at, expires_at, last_used_at FROM pulls_list_cache
WHERE owner = ? AND repo = ?
`

type GetPullsListMarkerParams struct {
	Owner string
	Repo  string
}

// ---- pulls_list_cache (the "open-PR list complete" markers) ----
func (q *Queries) GetPullsListMarker(ctx context.Context, arg GetPullsListMarkerParams) (PullsListCache, error) {
	row := q.db.QueryRowContext(ctx, getPullsListMarker, arg.Owner, arg.Repo)
	var i PullsListCache
	err := row.Scan(
		&i.ID,
		&i.Owner,
		&i.Repo,
		&i.FetchedAt,
		&i.ExpiresAt,
		&i.LastUsedAt,
	)
	return i, err
}

const getRepoInstallationCache = `-- name: GetRepoInstallationCache :one

SELECT id, actor, owner, repo, installation_id, account_login, account_type, repository_selection, app_id, app_slug, target_type, fetched_at, expires_at, last_used_at FROM repo_installation_cache
WHERE actor = ? AND owner = ? AND repo = ?
`

type GetRepoInstallationCacheParams struct {
	Actor string
	Owner string
	Repo  string
}

// ---- repo_installation_cache (GET /repos/{owner}/{repo}/installation) ----
func (q *Queries) GetRepoInstallationCache(ctx context.Context, arg GetRepoInstallationCacheParams) (RepoInstallationCache, error) {
	row := q.db.QueryRowContext(ctx, getRepoInstallationCache, arg.Actor, arg.Owner, arg.Repo)
	var i RepoInstallationCache
	err := row.Scan(
		&i.ID,
		&i.Actor,
		&i.Owner,
		&i.Repo,
		&i.InstallationID,
		&i.AccountLogin,
		&i.AccountType,
		&i.RepositorySelection,
		&i.AppID,
		&i.AppSlug,
		&i.TargetType,
		&i.FetchedAt,
		&i.ExpiresAt,
		&i.LastUsedAt,
	)
	return i, err
}

const pruneCommitsListCacheLRU = `-- name: PruneCommitsListCacheLRU :exec
DELETE FROM commits_list_cache WHERE id IN (
    SELECT id FROM commits_list_cache ORDER BY last_used_at DESC LIMIT -1 OFFSET ?
)
`

func (q *Queries) PruneCommitsListCacheLRU(ctx context.Context, offset int64) error {
	_, err := q.db.ExecContext(ctx, pruneCommitsListCacheLRU, offset)
	return err
}

const pruneCompareCacheLRU = `-- name: PruneCompareCacheLRU :exec
DELETE FROM compare_cache WHERE id IN (
    SELECT id FROM compare_cache ORDER BY last_used_at DESC LIMIT -1 OFFSET ?
)
`

func (q *Queries) PruneCompareCacheLRU(ctx context.Context, offset int64) error {
	_, err := q.db.ExecContext(ctx, pruneCompareCacheLRU, offset)
	return err
}

const pruneContentsCacheLRU = `-- name: PruneContentsCacheLRU :exec
DELETE FROM contents_cache WHERE id IN (
    SELECT id FROM contents_cache ORDER BY last_used_at DESC LIMIT -1 OFFSET ?
)
`

// PruneContentsCacheLRU keeps only the most recently used rows. The subquery
// selects everything beyond the newest `offset` rows by last_used_at; LIMIT -1
// means "no limit" in SQLite, so OFFSET skips the keepers.
func (q *Queries) PruneContentsCacheLRU(ctx context.Context, offset int64) error {
	_, err := q.db.ExecContext(ctx, pruneContentsCacheLRU, offset)
	return err
}

const pruneGitCommitsCacheLRU = `-- name: PruneGitCommitsCacheLRU :exec
DELETE FROM git_commits_cache WHERE id IN (
    SELECT id FROM git_commits_cache ORDER BY last_used_at DESC LIMIT -1 OFFSET ?
)
`

func (q *Queries) PruneGitCommitsCacheLRU(ctx context.Context, offset int64) error {
	_, err := q.db.ExecContext(ctx, pruneGitCommitsCacheLRU, offset)
	return err
}

const pruneInstallTokenCacheLRU = `-- name: PruneInstallTokenCacheLRU :exec
DELETE FROM install_token_cache WHERE id IN (
    SELECT id FROM install_token_cache ORDER BY last_used_at DESC LIMIT -1 OFFSET ?
)
`

func (q *Queries) PruneInstallTokenCacheLRU(ctx context.Context, offset int64) error {
	_, err := q.db.ExecContext(ctx, pruneInstallTokenCacheLRU, offset)
	return err
}

const prunePullsListMarkersLRU = `-- name: PrunePullsListMarkersLRU :exec
DELETE FROM pulls_list_cache WHERE id IN (
    SELECT id FROM pulls_list_cache ORDER BY last_used_at DESC LIMIT -1 OFFSET ?
)
`

func (q *Queries) PrunePullsListMarkersLRU(ctx context.Context, offset int64) error {
	_, err := q.db.ExecContext(ctx, prunePullsListMarkersLRU, offset)
	return err
}

const pruneRepoInstallationCacheLRU = `-- name: PruneRepoInstallationCacheLRU :exec
DELETE FROM repo_installation_cache WHERE id IN (
    SELECT id FROM repo_installation_cache ORDER BY last_used_at DESC LIMIT -1 OFFSET ?
)
`

func (q *Queries) PruneRepoInstallationCacheLRU(ctx context.Context, offset int64) error {
	_, err := q.db.ExecContext(ctx, pruneRepoInstallationCacheLRU, offset)
	return err
}

const touchCommitsListCache = `-- name: TouchCommitsListCache :exec
UPDATE commits_list_cache SET last_used_at = ?
WHERE owner = ? AND repo = ? AND ref_param = ? AND per_page = ? AND page = ?
`

type TouchCommitsListCacheParams struct {
	LastUsedAt string
	Owner      string
	Repo       string
	RefParam   string
	PerPage    int64
	Page       int64
}

func (q *Queries) TouchCommitsListCache(ctx context.Context, arg TouchCommitsListCacheParams) error {
	_, err := q.db.ExecContext(ctx, touchCommitsListCache,
		arg.LastUsedAt,
		arg.Owner,
		arg.Repo,
		arg.RefParam,
		arg.PerPage,
		arg.Page,
	)
	return err
}

const touchCompareCache = `-- name: TouchCompareCache :exec
UPDATE compare_cache SET last_used_at = ?
WHERE owner = ? AND repo = ? AND basehead = ?
`

type TouchCompareCacheParams struct {
	LastUsedAt string
	Owner      string
	Repo       string
	Basehead   string
}

func (q *Queries) TouchCompareCache(ctx context.Context, arg TouchCompareCacheParams) error {
	_, err := q.db.ExecContext(ctx, touchCompareCache,
		arg.LastUsedAt,
		arg.Owner,
		arg.Repo,
		arg.Basehead,
	)
	return err
}

const touchContentsCache = `-- name: TouchContentsCache :exec
UPDATE contents_cache SET last_used_at = ?
WHERE owner = ? AND repo = ? AND path = ? AND ref = ?
`

type TouchContentsCacheParams struct {
	LastUsedAt string
	Owner      string
	Repo       string
	Path       string
	Ref        string
}

func (q *Queries) TouchContentsCache(ctx context.Context, arg TouchContentsCacheParams) error {
	_, err := q.db.ExecContext(ctx, touchContentsCache,
		arg.LastUsedAt,
		arg.Owner,
		arg.Repo,
		arg.Path,
		arg.Ref,
	)
	return err
}

const touchGitCommitCache = `-- name: TouchGitCommitCache :exec
UPDATE git_commits_cache SET last_used_at = ?
WHERE owner = ? AND repo = ? AND sha = ?
`

type TouchGitCommitCacheParams struct {
	LastUsedAt string
	Owner      string
	Repo       string
	Sha        string
}

func (q *Queries) TouchGitCommitCache(ctx context.Context, arg TouchGitCommitCacheParams) error {
	_, err := q.db.ExecContext(ctx, touchGitCommitCache,
		arg.LastUsedAt,
		arg.Owner,
		arg.Repo,
		arg.Sha,
	)
	return err
}

const touchPullsListMarker = `-- name: TouchPullsListMarker :exec
UPDATE pulls_list_cache SET last_used_at = ?
WHERE owner = ? AND repo = ?
`

type TouchPullsListMarkerParams struct {
	LastUsedAt string
	Owner      string
	Repo       string
}

func (q *Queries) TouchPullsListMarker(ctx context.Context, arg TouchPullsListMarkerParams) error {
	_, err := q.db.ExecContext(ctx, touchPullsListMarker, arg.LastUsedAt, arg.Owner, arg.Repo)
	return err
}

const touchRepoInstallationCache = `-- name: TouchRepoInstallationCache :exec
UPDATE repo_installation_cache SET last_used_at = ?
WHERE actor = ? AND owner = ? AND repo = ?
`

type TouchRepoInstallationCacheParams struct {
	LastUsedAt string
	Actor      string
	Owner      string
	Repo       string
}

func (q *Queries) TouchRepoInstallationCache(ctx context.Context, arg TouchRepoInstallationCacheParams) error {
	_, err := q.db.ExecContext(ctx, touchRepoInstallationCache,
		arg.LastUsedAt,
		arg.Actor,
		arg.Owner,
		arg.Repo,
	)
	return err
}

const upsertCommitsListCache = `-- name: UpsertCommitsListCache :exec
INSERT INTO commits_list_cache (owner, repo, ref_param, per_page, page, shas, fetched_at, expires_at, last_used_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT (owner, repo, ref_param, per_page, page) DO UPDATE SET
    shas = excluded.shas,
    fetched_at = excluded.fetched_at,
    expires_at = excluded.expires_at,
    last_used_at = excluded.last_used_at
`

type UpsertCommitsListCacheParams struct {
	Owner      string
	Repo       string
	RefParam   string
	PerPage    int64
	Page       int64
	Shas       string
	FetchedAt  string
	ExpiresAt  string
	LastUsedAt string
}

func (q *Queries) UpsertCommitsListCache(ctx context.Context, arg UpsertCommitsListCacheParams) error {
	_, err := q.db.ExecContext(ctx, upsertCommitsListCache,
		arg.Owner,
		arg.Repo,
		arg.RefParam,
		arg.PerPage,
		arg.Page,
		arg.Shas,
		arg.FetchedAt,
		arg.ExpiresAt,
		arg.LastUsedAt,
	)
	return err
}

const upsertCompareCache = `-- name: UpsertCompareCache :exec
INSERT INTO compare_cache (owner, repo, basehead, doc, fetched_at, expires_at, last_used_at)
VALUES (?, ?, ?, ?, ?, ?, ?)
ON CONFLICT (owner, repo, basehead) DO UPDATE SET
    doc = excluded.doc,
    fetched_at = excluded.fetched_at,
    expires_at = excluded.expires_at,
    last_used_at = excluded.last_used_at
`

type UpsertCompareCacheParams struct {
	Owner      string
	Repo       string
	Basehead   string
	Doc        string
	FetchedAt  string
	ExpiresAt  string
	LastUsedAt string
}

func (q *Queries) UpsertCompareCache(ctx context.Context, arg UpsertCompareCacheParams) error {
	_, err := q.db.ExecContext(ctx, upsertCompareCache,
		arg.Owner,
		arg.Repo,
		arg.Basehead,
		arg.Doc,
		arg.FetchedAt,
		arg.ExpiresAt,
		arg.LastUsedAt,
	)
	return err
}

const upsertContentsCache = `-- name: UpsertContentsCache :exec
INSERT INTO contents_cache (owner, repo, path, ref, kind, name, sha, size, encoding, content, entries, message, fetched_at, expires_at, last_used_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT (owner, repo, path, ref) DO UPDATE SET
    kind = excluded.kind,
    name = excluded.name,
    sha = excluded.sha,
    size = excluded.size,
    encoding = excluded.encoding,
    content = excluded.content,
    entries = excluded.entries,
    message = excluded.message,
    fetched_at = excluded.fetched_at,
    expires_at = excluded.expires_at,
    last_used_at = excluded.last_used_at
`

type UpsertContentsCacheParams struct {
	Owner      string
	Repo       string
	Path       string
	Ref        string
	Kind       string
	Name       string
	Sha        string
	Size       int64
	Encoding   string
	Content    string
	Entries    string
	Message    string
	FetchedAt  string
	ExpiresAt  string
	LastUsedAt string
}

func (q *Queries) UpsertContentsCache(ctx context.Context, arg UpsertContentsCacheParams) error {
	_, err := q.db.ExecContext(ctx, upsertContentsCache,
		arg.Owner,
		arg.Repo,
		arg.Path,
		arg.Ref,
		arg.Kind,
		arg.Name,
		arg.Sha,
		arg.Size,
		arg.Encoding,
		arg.Content,
		arg.Entries,
		arg.Message,
		arg.FetchedAt,
		arg.ExpiresAt,
		arg.LastUsedAt,
	)
	return err
}

const upsertGitCommitCache = `-- name: UpsertGitCommitCache :exec
INSERT INTO git_commits_cache (owner, repo, sha, message, author_name, author_email, author_date, committer_name, committer_email, committer_date, tree_sha, parents, fetched_at, last_used_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT (owner, repo, sha) DO UPDATE SET
    message = excluded.message,
    author_name = excluded.author_name,
    author_email = excluded.author_email,
    author_date = excluded.author_date,
    committer_name = excluded.committer_name,
    committer_email = excluded.committer_email,
    committer_date = excluded.committer_date,
    tree_sha = excluded.tree_sha,
    parents = excluded.parents,
    fetched_at = excluded.fetched_at,
    last_used_at = excluded.last_used_at
`

type UpsertGitCommitCacheParams struct {
	Owner          string
	Repo           string
	Sha            string
	Message        string
	AuthorName     string
	AuthorEmail    string
	AuthorDate     string
	CommitterName  string
	CommitterEmail string
	CommitterDate  string
	TreeSha        string
	Parents        string
	FetchedAt      string
	LastUsedAt     string
}

func (q *Queries) UpsertGitCommitCache(ctx context.Context, arg UpsertGitCommitCacheParams) error {
	_, err := q.db.ExecContext(ctx, upsertGitCommitCache,
		arg.Owner,
		arg.Repo,
		arg.Sha,
		arg.Message,
		arg.AuthorName,
		arg.AuthorEmail,
		arg.AuthorDate,
		arg.CommitterName,
		arg.CommitterEmail,
		arg.CommitterDate,
		arg.TreeSha,
		arg.Parents,
		arg.FetchedAt,
		arg.LastUsedAt,
	)
	return err
}

const upsertInstallTokenCache = `-- name: UpsertInstallTokenCache :exec
INSERT INTO install_token_cache (actor, installation_id, body_hash, token, token_expires_at, permissions, repository_selection, fetched_at, expires_at, last_used_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT (actor, installation_id, body_hash) DO UPDATE SET
    token = excluded.token,
    token_expires_at = excluded.token_expires_at,
    permissions = excluded.permissions,
    repository_selection = excluded.repository_selection,
    fetched_at = excluded.fetched_at,
    expires_at = excluded.expires_at,
    last_used_at = excluded.last_used_at
`

type UpsertInstallTokenCacheParams struct {
	Actor               string
	InstallationID      string
	BodyHash            string
	Token               string
	TokenExpiresAt      string
	Permissions         string
	RepositorySelection string
	FetchedAt           string
	ExpiresAt           string
	LastUsedAt          string
}

func (q *Queries) UpsertInstallTokenCache(ctx context.Context, arg UpsertInstallTokenCacheParams) error {
	_, err := q.db.ExecContext(ctx, upsertInstallTokenCache,
		arg.Actor,
		arg.InstallationID,
		arg.BodyHash,
		arg.Token,
		arg.TokenExpiresAt,
		arg.Permissions,
		arg.RepositorySelection,
		arg.FetchedAt,
		arg.ExpiresAt,
		arg.LastUsedAt,
	)
	return err
}

const upsertPullsListMarker = `-- name: UpsertPullsListMarker :exec
INSERT INTO pulls_list_cache (owner, repo, fetched_at, expires_at, last_used_at)
VALUES (?, ?, ?, ?, ?)
ON CONFLICT (owner, repo) DO UPDATE SET
    fetched_at = excluded.fetched_at,
    expires_at = excluded.expires_at,
    last_used_at = excluded.last_used_at
`

type UpsertPullsListMarkerParams struct {
	Owner      string
	Repo       string
	FetchedAt  string
	ExpiresAt  string
	LastUsedAt string
}

func (q *Queries) UpsertPullsListMarker(ctx context.Context, arg UpsertPullsListMarkerParams) error {
	_, err := q.db.ExecContext(ctx, upsertPullsListMarker,
		arg.Owner,
		arg.Repo,
		arg.FetchedAt,
		arg.ExpiresAt,
		arg.LastUsedAt,
	)
	return err
}

const upsertRepoInstallationCache = `-- name: UpsertRepoInstallationCache :exec
INSERT INTO repo_installation_cache (actor, owner, repo, installation_id, account_login, account_type, repository_selection, app_id, app_slug, target_type, fetched_at, expires_at, last_used_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT (actor, owner, repo) DO UPDATE SET
    installation_id = excluded.installation_id,
    account_login = excluded.account_login,
    account_type = excluded.account_type,
    repository_selection = excluded.repository_selection,
    app_id = excluded.app_id,
    app_slug = excluded.app_slug,
    target_type = excluded.target_type,
    fetched_at = excluded.fetched_at,
    expires_at = excluded.expires_at,
    last_used_at = excluded.last_used_at
`

type UpsertRepoInstallationCacheParams struct {
	Actor               string
	Owner               string
	Repo                string
	InstallationID      int64
	AccountLogin        string
	AccountType         string
	RepositorySelection string
	AppID               int64
	AppSlug             string
	TargetType          string
	FetchedAt           string
	ExpiresAt           string
	LastUsedAt          string
}

func (q *Queries) UpsertRepoInstallationCache(ctx context.Context, arg UpsertRepoInstallationCacheParams) error {
	_, err := q.db.ExecContext(ctx, upsertRepoInstallationCache,
		arg.Actor,
		arg.Owner,
		arg.Repo,
		arg.InstallationID,
		arg.AccountLogin,
		arg.AccountType,
		arg.RepositorySelection,
		arg.AppID,
		arg.AppSlug,
		arg.TargetType,
		arg.FetchedAt,
		arg.ExpiresAt,
		arg.LastUsedAt,
	)
	return err
}
