// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: respcache.sql

package dbgen

import (
	"context"
)

const deleteContentsCacheByRepo = `-- name: DeleteContentsCacheByRepo :exec
DELETE FROM contents_cache WHERE owner = ? AND repo = ?
`

type DeleteContentsCacheByRepoParams struct {
	Owner string
	Repo  string
}

func (q *Queries) DeleteContentsCacheByRepo(ctx context.Context, arg DeleteContentsCacheByRepoParams) error {
	_, err := q.db.ExecContext(ctx, deleteContentsCacheByRepo, arg.Owner, arg.Repo)
	return err
}

const deleteExpiredContentsCache = `-- name: DeleteExpiredContentsCache :exec
DELETE FROM contents_cache WHERE expires_at <= ?
`

func (q *Queries) DeleteExpiredContentsCache(ctx context.Context, expiresAt string) error {
	_, err := q.db.ExecContext(ctx, deleteExpiredContentsCache, expiresAt)
	return err
}

const deleteExpiredInstallTokenCache = `-- name: DeleteExpiredInstallTokenCache :exec
DELETE FROM install_token_cache WHERE expires_at <= ?
`

func (q *Queries) DeleteExpiredInstallTokenCache(ctx context.Context, expiresAt string) error {
	_, err := q.db.ExecContext(ctx, deleteExpiredInstallTokenCache, expiresAt)
	return err
}

const deleteInstallTokenCacheByInstallation = `-- name: DeleteInstallTokenCacheByInstallation :exec
DELETE FROM install_token_cache WHERE installation_id = ?
`

func (q *Queries) DeleteInstallTokenCacheByInstallation(ctx context.Context, installationID string) error {
	_, err := q.db.ExecContext(ctx, deleteInstallTokenCacheByInstallation, installationID)
	return err
}

const getContentsCache = `-- name: GetContentsCache :one


SELECT id, actor, owner, repo, path, ref, kind, name, sha, size, encoding, content, entries, message, fetched_at, expires_at, last_used_at FROM contents_cache
WHERE actor = ? AND owner = ? AND repo = ? AND path = ? AND ref = ?
`

type GetContentsCacheParams struct {
	Actor string
	Owner string
	Repo  string
	Path  string
	Ref   string
}

// ============================================================================
// Cached-route response state (contents / git commits / installation tokens)
// ============================================================================
//
// Reads are keyed by actor (per-credential isolation). Invalidation deletes
// span ALL actors: a webhook is a single global fact (the repo changed, the
// installation changed), so every partition's rows for it are stale.
// ---- contents_cache ----
func (q *Queries) GetContentsCache(ctx context.Context, arg GetContentsCacheParams) (ContentsCache, error) {
	row := q.db.QueryRowContext(ctx, getContentsCache,
		arg.Actor,
		arg.Owner,
		arg.Repo,
		arg.Path,
		arg.Ref,
	)
	var i ContentsCache
	err := row.Scan(
		&i.ID,
		&i.Actor,
		&i.Owner,
		&i.Repo,
		&i.Path,
		&i.Ref,
		&i.Kind,
		&i.Name,
		&i.Sha,
		&i.Size,
		&i.Encoding,
		&i.Content,
		&i.Entries,
		&i.Message,
		&i.FetchedAt,
		&i.ExpiresAt,
		&i.LastUsedAt,
	)
	return i, err
}

const getGitCommitCache = `-- name: GetGitCommitCache :one

SELECT id, actor, owner, repo, sha, message, author_name, author_email, author_date, committer_name, committer_email, committer_date, tree_sha, parents, fetched_at, last_used_at FROM git_commits_cache
WHERE actor = ? AND owner = ? AND repo = ? AND sha = ?
`

type GetGitCommitCacheParams struct {
	Actor string
	Owner string
	Repo  string
	Sha   string
}

// ---- git_commits_cache ----
func (q *Queries) GetGitCommitCache(ctx context.Context, arg GetGitCommitCacheParams) (GitCommitsCache, error) {
	row := q.db.QueryRowContext(ctx, getGitCommitCache,
		arg.Actor,
		arg.Owner,
		arg.Repo,
		arg.Sha,
	)
	var i GitCommitsCache
	err := row.Scan(
		&i.ID,
		&i.Actor,
		&i.Owner,
		&i.Repo,
		&i.Sha,
		&i.Message,
		&i.AuthorName,
		&i.AuthorEmail,
		&i.AuthorDate,
		&i.CommitterName,
		&i.CommitterEmail,
		&i.CommitterDate,
		&i.TreeSha,
		&i.Parents,
		&i.FetchedAt,
		&i.LastUsedAt,
	)
	return i, err
}

const getInstallTokenCache = `-- name: GetInstallTokenCache :one

SELECT id, actor, installation_id, body_hash, token, token_expires_at, permissions, repository_selection, fetched_at, expires_at, last_used_at FROM install_token_cache
WHERE actor = ? AND installation_id = ? AND body_hash = ?
`

type GetInstallTokenCacheParams struct {
	Actor          string
	InstallationID string
	BodyHash       string
}

// ---- install_token_cache ----
func (q *Queries) GetInstallTokenCache(ctx context.Context, arg GetInstallTokenCacheParams) (InstallTokenCache, error) {
	row := q.db.QueryRowContext(ctx, getInstallTokenCache, arg.Actor, arg.InstallationID, arg.BodyHash)
	var i InstallTokenCache
	err := row.Scan(
		&i.ID,
		&i.Actor,
		&i.InstallationID,
		&i.BodyHash,
		&i.Token,
		&i.TokenExpiresAt,
		&i.Permissions,
		&i.RepositorySelection,
		&i.FetchedAt,
		&i.ExpiresAt,
		&i.LastUsedAt,
	)
	return i, err
}

const pruneContentsCacheLRU = `-- name: PruneContentsCacheLRU :exec
DELETE FROM contents_cache WHERE id IN (
    SELECT id FROM contents_cache ORDER BY last_used_at DESC LIMIT -1 OFFSET ?
)
`

// PruneContentsCacheLRU keeps only the most recently used rows. The subquery
// selects everything beyond the newest `offset` rows by last_used_at; LIMIT -1
// means "no limit" in SQLite, so OFFSET skips the keepers.
func (q *Queries) PruneContentsCacheLRU(ctx context.Context, offset int64) error {
	_, err := q.db.ExecContext(ctx, pruneContentsCacheLRU, offset)
	return err
}

const pruneGitCommitsCacheLRU = `-- name: PruneGitCommitsCacheLRU :exec
DELETE FROM git_commits_cache WHERE id IN (
    SELECT id FROM git_commits_cache ORDER BY last_used_at DESC LIMIT -1 OFFSET ?
)
`

func (q *Queries) PruneGitCommitsCacheLRU(ctx context.Context, offset int64) error {
	_, err := q.db.ExecContext(ctx, pruneGitCommitsCacheLRU, offset)
	return err
}

const pruneInstallTokenCacheLRU = `-- name: PruneInstallTokenCacheLRU :exec
DELETE FROM install_token_cache WHERE id IN (
    SELECT id FROM install_token_cache ORDER BY last_used_at DESC LIMIT -1 OFFSET ?
)
`

func (q *Queries) PruneInstallTokenCacheLRU(ctx context.Context, offset int64) error {
	_, err := q.db.ExecContext(ctx, pruneInstallTokenCacheLRU, offset)
	return err
}

const touchContentsCache = `-- name: TouchContentsCache :exec
UPDATE contents_cache SET last_used_at = ?
WHERE actor = ? AND owner = ? AND repo = ? AND path = ? AND ref = ?
`

type TouchContentsCacheParams struct {
	LastUsedAt string
	Actor      string
	Owner      string
	Repo       string
	Path       string
	Ref        string
}

func (q *Queries) TouchContentsCache(ctx context.Context, arg TouchContentsCacheParams) error {
	_, err := q.db.ExecContext(ctx, touchContentsCache,
		arg.LastUsedAt,
		arg.Actor,
		arg.Owner,
		arg.Repo,
		arg.Path,
		arg.Ref,
	)
	return err
}

const touchGitCommitCache = `-- name: TouchGitCommitCache :exec
UPDATE git_commits_cache SET last_used_at = ?
WHERE actor = ? AND owner = ? AND repo = ? AND sha = ?
`

type TouchGitCommitCacheParams struct {
	LastUsedAt string
	Actor      string
	Owner      string
	Repo       string
	Sha        string
}

func (q *Queries) TouchGitCommitCache(ctx context.Context, arg TouchGitCommitCacheParams) error {
	_, err := q.db.ExecContext(ctx, touchGitCommitCache,
		arg.LastUsedAt,
		arg.Actor,
		arg.Owner,
		arg.Repo,
		arg.Sha,
	)
	return err
}

const upsertContentsCache = `-- name: UpsertContentsCache :exec
INSERT INTO contents_cache (actor, owner, repo, path, ref, kind, name, sha, size, encoding, content, entries, message, fetched_at, expires_at, last_used_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT (actor, owner, repo, path, ref) DO UPDATE SET
    kind = excluded.kind,
    name = excluded.name,
    sha = excluded.sha,
    size = excluded.size,
    encoding = excluded.encoding,
    content = excluded.content,
    entries = excluded.entries,
    message = excluded.message,
    fetched_at = excluded.fetched_at,
    expires_at = excluded.expires_at,
    last_used_at = excluded.last_used_at
`

type UpsertContentsCacheParams struct {
	Actor      string
	Owner      string
	Repo       string
	Path       string
	Ref        string
	Kind       string
	Name       string
	Sha        string
	Size       int64
	Encoding   string
	Content    string
	Entries    string
	Message    string
	FetchedAt  string
	ExpiresAt  string
	LastUsedAt string
}

func (q *Queries) UpsertContentsCache(ctx context.Context, arg UpsertContentsCacheParams) error {
	_, err := q.db.ExecContext(ctx, upsertContentsCache,
		arg.Actor,
		arg.Owner,
		arg.Repo,
		arg.Path,
		arg.Ref,
		arg.Kind,
		arg.Name,
		arg.Sha,
		arg.Size,
		arg.Encoding,
		arg.Content,
		arg.Entries,
		arg.Message,
		arg.FetchedAt,
		arg.ExpiresAt,
		arg.LastUsedAt,
	)
	return err
}

const upsertGitCommitCache = `-- name: UpsertGitCommitCache :exec
INSERT INTO git_commits_cache (actor, owner, repo, sha, message, author_name, author_email, author_date, committer_name, committer_email, committer_date, tree_sha, parents, fetched_at, last_used_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT (actor, owner, repo, sha) DO UPDATE SET
    message = excluded.message,
    author_name = excluded.author_name,
    author_email = excluded.author_email,
    author_date = excluded.author_date,
    committer_name = excluded.committer_name,
    committer_email = excluded.committer_email,
    committer_date = excluded.committer_date,
    tree_sha = excluded.tree_sha,
    parents = excluded.parents,
    fetched_at = excluded.fetched_at,
    last_used_at = excluded.last_used_at
`

type UpsertGitCommitCacheParams struct {
	Actor          string
	Owner          string
	Repo           string
	Sha            string
	Message        string
	AuthorName     string
	AuthorEmail    string
	AuthorDate     string
	CommitterName  string
	CommitterEmail string
	CommitterDate  string
	TreeSha        string
	Parents        string
	FetchedAt      string
	LastUsedAt     string
}

func (q *Queries) UpsertGitCommitCache(ctx context.Context, arg UpsertGitCommitCacheParams) error {
	_, err := q.db.ExecContext(ctx, upsertGitCommitCache,
		arg.Actor,
		arg.Owner,
		arg.Repo,
		arg.Sha,
		arg.Message,
		arg.AuthorName,
		arg.AuthorEmail,
		arg.AuthorDate,
		arg.CommitterName,
		arg.CommitterEmail,
		arg.CommitterDate,
		arg.TreeSha,
		arg.Parents,
		arg.FetchedAt,
		arg.LastUsedAt,
	)
	return err
}

const upsertInstallTokenCache = `-- name: UpsertInstallTokenCache :exec
INSERT INTO install_token_cache (actor, installation_id, body_hash, token, token_expires_at, permissions, repository_selection, fetched_at, expires_at, last_used_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT (actor, installation_id, body_hash) DO UPDATE SET
    token = excluded.token,
    token_expires_at = excluded.token_expires_at,
    permissions = excluded.permissions,
    repository_selection = excluded.repository_selection,
    fetched_at = excluded.fetched_at,
    expires_at = excluded.expires_at,
    last_used_at = excluded.last_used_at
`

type UpsertInstallTokenCacheParams struct {
	Actor               string
	InstallationID      string
	BodyHash            string
	Token               string
	TokenExpiresAt      string
	Permissions         string
	RepositorySelection string
	FetchedAt           string
	ExpiresAt           string
	LastUsedAt          string
}

func (q *Queries) UpsertInstallTokenCache(ctx context.Context, arg UpsertInstallTokenCacheParams) error {
	_, err := q.db.ExecContext(ctx, upsertInstallTokenCache,
		arg.Actor,
		arg.InstallationID,
		arg.BodyHash,
		arg.Token,
		arg.TokenExpiresAt,
		arg.Permissions,
		arg.RepositorySelection,
		arg.FetchedAt,
		arg.ExpiresAt,
		arg.LastUsedAt,
	)
	return err
}
