// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: respcache.sql

package dbgen

import (
	"context"
	"strings"
)

const countWorkflowRuns = `-- name: CountWorkflowRuns :one
SELECT COUNT(*) FROM workflow_runs
WHERE owner = ?1 AND repo = ?2
  AND (?3 = '' OR status = ?3 OR conclusion = ?3)
  AND (?4 = '' OR head_branch = ?4)
  AND (?5 = '' OR head_sha = ?5)
`

type CountWorkflowRunsParams struct {
	Owner      string
	Repo       string
	Status     interface{}
	HeadBranch interface{}
	HeadSha    interface{}
}

// CountWorkflowRuns is the same filter without pagination -- the listing's
// total_count, exact because the completeness marker vouches for the set.
func (q *Queries) CountWorkflowRuns(ctx context.Context, arg CountWorkflowRunsParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countWorkflowRuns,
		arg.Owner,
		arg.Repo,
		arg.Status,
		arg.HeadBranch,
		arg.HeadSha,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteAbsentRepoInstallationCache = `-- name: DeleteAbsentRepoInstallationCache :exec
DELETE FROM repo_installation_cache WHERE status <> 200
`

// DeleteAbsentRepoInstallationCache drops every "not installed" VERDICT row.
// Those carry installation_id 0, so the by-id flush above cannot reach them,
// and an installation event means some account gained (or lost) an install --
// exactly what a verdict claims is absent.
func (q *Queries) DeleteAbsentRepoInstallationCache(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteAbsentRepoInstallationCache)
	return err
}

const deleteAllInstallationReposCache = `-- name: DeleteAllInstallationReposCache :exec
DELETE FROM installation_repos_cache
`

// DeleteAllInstallationReposCache is the installation-event flush. Rows key a
// credential, not an installation id, so there is nothing finer to match on --
// and these deliveries are rare while the table holds one row per live token.
func (q *Queries) DeleteAllInstallationReposCache(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteAllInstallationReposCache)
	return err
}

const deleteBranchesListCacheByRepo = `-- name: DeleteBranchesListCacheByRepo :exec
DELETE FROM branches_list_cache WHERE owner = ? AND repo = ?
`

type DeleteBranchesListCacheByRepoParams struct {
	Owner string
	Repo  string
}

// DeleteBranchesListCacheByRepo drops a repo's branches snapshots -- the
// push/repository webhook flush (branch create, delete, and tip-move all
// arrive as pushes).
func (q *Queries) DeleteBranchesListCacheByRepo(ctx context.Context, arg DeleteBranchesListCacheByRepoParams) error {
	_, err := q.db.ExecContext(ctx, deleteBranchesListCacheByRepo, arg.Owner, arg.Repo)
	return err
}

const deleteClosedPullCacheByPR = `-- name: DeleteClosedPullCacheByPR :exec
DELETE FROM closed_pull_cache WHERE owner = ? AND repo = ? AND number = ?
`

type DeleteClosedPullCacheByPRParams struct {
	Owner  string
	Repo   string
	Number int64
}

// DeleteClosedPullCacheByPR drops one PR's closed doc -- the pull_request
// event flush (reopened/edited/relabeled), and the reopened-race safety
// after an open absorb.
func (q *Queries) DeleteClosedPullCacheByPR(ctx context.Context, arg DeleteClosedPullCacheByPRParams) error {
	_, err := q.db.ExecContext(ctx, deleteClosedPullCacheByPR, arg.Owner, arg.Repo, arg.Number)
	return err
}

const deleteClosedPullCacheByRepo = `-- name: DeleteClosedPullCacheByRepo :exec
DELETE FROM closed_pull_cache WHERE owner = ? AND repo = ?
`

type DeleteClosedPullCacheByRepoParams struct {
	Owner string
	Repo  string
}

// DeleteClosedPullCacheByRepo drops a repo's closed-PR docs -- the repository
// webhook flush. A push is deliberately NOT a flush: it cannot mutate a
// closed PR.
func (q *Queries) DeleteClosedPullCacheByRepo(ctx context.Context, arg DeleteClosedPullCacheByRepoParams) error {
	_, err := q.db.ExecContext(ctx, deleteClosedPullCacheByRepo, arg.Owner, arg.Repo)
	return err
}

const deleteCodeQualitySetupCacheByRepo = `-- name: DeleteCodeQualitySetupCacheByRepo :exec
DELETE FROM code_quality_setup_cache WHERE owner = ? AND repo = ?
`

type DeleteCodeQualitySetupCacheByRepoParams struct {
	Owner string
	Repo  string
}

func (q *Queries) DeleteCodeQualitySetupCacheByRepo(ctx context.Context, arg DeleteCodeQualitySetupCacheByRepoParams) error {
	_, err := q.db.ExecContext(ctx, deleteCodeQualitySetupCacheByRepo, arg.Owner, arg.Repo)
	return err
}

const deleteCommitCICacheByRepo = `-- name: DeleteCommitCICacheByRepo :exec
DELETE FROM commit_ci_cache WHERE owner = ? AND repo = ?
`

type DeleteCommitCICacheByRepoParams struct {
	Owner string
	Repo  string
}

// DeleteCommitCICacheByRepo drops ALL of a repo's commit-CI snapshots (every
// kind, every ref, every page) -- the repository webhook flush and the
// no-per-ref-signal fallbacks (unparseable push/check payloads).
func (q *Queries) DeleteCommitCICacheByRepo(ctx context.Context, arg DeleteCommitCICacheByRepoParams) error {
	_, err := q.db.ExecContext(ctx, deleteCommitCICacheByRepo, arg.Owner, arg.Repo)
	return err
}

const deleteCommitCICacheForRef = `-- name: DeleteCommitCICacheForRef :exec
DELETE FROM commit_ci_cache WHERE owner = ? AND repo = ? AND ref = ?
`

type DeleteCommitCICacheForRefParams struct {
	Owner string
	Repo  string
	Ref   string
}

// DeleteCommitCICacheForRef drops one verbatim ref spelling's snapshots (all
// kinds, all pages) -- the per-ref status/check_run/check_suite/push flush.
// Other refs' snapshots survive: each spelling is its own row and the
// payload names exactly which spellings moved.
func (q *Queries) DeleteCommitCICacheForRef(ctx context.Context, arg DeleteCommitCICacheForRefParams) error {
	_, err := q.db.ExecContext(ctx, deleteCommitCICacheForRef, arg.Owner, arg.Repo, arg.Ref)
	return err
}

const deleteCommitsListCacheByRepo = `-- name: DeleteCommitsListCacheByRepo :exec
DELETE FROM commits_list_cache WHERE owner = ? AND repo = ?
`

type DeleteCommitsListCacheByRepoParams struct {
	Owner string
	Repo  string
}

// DeleteCommitsListCacheByRepo drops a repo's snapshots -- the repository
// webhook flush and the unparseable-push fallback (a push moves every
// ref-relative listing). The absorbed git_commits_cache rows are immutable
// and stay.
func (q *Queries) DeleteCommitsListCacheByRepo(ctx context.Context, arg DeleteCommitsListCacheByRepoParams) error {
	_, err := q.db.ExecContext(ctx, deleteCommitsListCacheByRepo, arg.Owner, arg.Repo)
	return err
}

const deleteCommitsListCacheForRef = `-- name: DeleteCommitsListCacheForRef :exec
DELETE FROM commits_list_cache WHERE owner = ? AND repo = ? AND ref_param = ?
`

type DeleteCommitsListCacheForRefParams struct {
	Owner    string
	Repo     string
	RefParam string
}

// DeleteCommitsListCacheForRef drops one requested ref spelling's snapshots
// (an empty ref = the default-branch listing) -- the per-ref push flush. The
// absorbed git_commits_cache rows are immutable and stay.
func (q *Queries) DeleteCommitsListCacheForRef(ctx context.Context, arg DeleteCommitsListCacheForRefParams) error {
	_, err := q.db.ExecContext(ctx, deleteCommitsListCacheForRef, arg.Owner, arg.Repo, arg.RefParam)
	return err
}

const deleteCommitsListCachePullSnapshots = `-- name: DeleteCommitsListCachePullSnapshots :exec
DELETE FROM commits_list_cache
WHERE owner = ? AND repo = ? AND ref_param LIKE 'pull/%'
`

type DeleteCommitsListCachePullSnapshotsParams struct {
	Owner string
	Repo  string
}

// DeleteCommitsListCachePullSnapshots drops a repo's PR-commit snapshots --
// the rows whose ref key is the synthetic "pull/<number>/commits" (see
// internal/api/respcache_pullcommits.go). A push moves a PR's commit list
// with no per-PR signal, exactly as it does the PR-files pages, so it flushes
// these repo-wide as the belt behind the per-PR pull_request flush.
func (q *Queries) DeleteCommitsListCachePullSnapshots(ctx context.Context, arg DeleteCommitsListCachePullSnapshotsParams) error {
	_, err := q.db.ExecContext(ctx, deleteCommitsListCachePullSnapshots, arg.Owner, arg.Repo)
	return err
}

const deleteCompareCacheByRepo = `-- name: DeleteCompareCacheByRepo :exec
DELETE FROM compare_cache WHERE owner = ? AND repo = ?
`

type DeleteCompareCacheByRepoParams struct {
	Owner string
	Repo  string
}

// DeleteCompareCacheByRepo drops a repo's compare docs -- the repository
// webhook flush and the unparseable-push fallback (a push to either side of
// any basehead can change the comparison).
func (q *Queries) DeleteCompareCacheByRepo(ctx context.Context, arg DeleteCompareCacheByRepoParams) error {
	_, err := q.db.ExecContext(ctx, deleteCompareCacheByRepo, arg.Owner, arg.Repo)
	return err
}

const deleteCompareCacheForRef = `-- name: DeleteCompareCacheForRef :exec
DELETE FROM compare_cache WHERE owner = ? AND repo = ? AND (base_ref = ? OR head_ref = ?)
`

type DeleteCompareCacheForRefParams struct {
	Owner   string
	Repo    string
	BaseRef string
	HeadRef string
}

// DeleteCompareCacheForRef drops every comparison naming one ref on EITHER
// side -- the per-ref push flush (callers pass the pushed ref twice, once
// per side). Comparisons not touching the pushed ref survive.
func (q *Queries) DeleteCompareCacheForRef(ctx context.Context, arg DeleteCompareCacheForRefParams) error {
	_, err := q.db.ExecContext(ctx, deleteCompareCacheForRef,
		arg.Owner,
		arg.Repo,
		arg.BaseRef,
		arg.HeadRef,
	)
	return err
}

const deleteContentsCacheByRepo = `-- name: DeleteContentsCacheByRepo :exec
DELETE FROM contents_cache WHERE owner = ? AND repo = ?
`

type DeleteContentsCacheByRepoParams struct {
	Owner string
	Repo  string
}

func (q *Queries) DeleteContentsCacheByRepo(ctx context.Context, arg DeleteContentsCacheByRepoParams) error {
	_, err := q.db.ExecContext(ctx, deleteContentsCacheByRepo, arg.Owner, arg.Repo)
	return err
}

const deleteContentsCacheForRef = `-- name: DeleteContentsCacheForRef :exec
DELETE FROM contents_cache WHERE owner = ? AND repo = ? AND ref = ?
`

type DeleteContentsCacheForRefParams struct {
	Owner string
	Repo  string
	Ref   string
}

// DeleteContentsCacheForRef drops one requested ref spelling's rows (an
// empty ref = the default-branch rows) -- the per-ref push flush. A push to
// branch X only moves X-relative answers, so other refs' rows survive.
func (q *Queries) DeleteContentsCacheForRef(ctx context.Context, arg DeleteContentsCacheForRefParams) error {
	_, err := q.db.ExecContext(ctx, deleteContentsCacheForRef, arg.Owner, arg.Repo, arg.Ref)
	return err
}

const deleteExpiredBranchesListCache = `-- name: DeleteExpiredBranchesListCache :exec
DELETE FROM branches_list_cache WHERE expires_at <= ?
`

func (q *Queries) DeleteExpiredBranchesListCache(ctx context.Context, expiresAt string) error {
	_, err := q.db.ExecContext(ctx, deleteExpiredBranchesListCache, expiresAt)
	return err
}

const deleteExpiredClosedPullCache = `-- name: DeleteExpiredClosedPullCache :exec
DELETE FROM closed_pull_cache WHERE expires_at <= ?
`

func (q *Queries) DeleteExpiredClosedPullCache(ctx context.Context, expiresAt string) error {
	_, err := q.db.ExecContext(ctx, deleteExpiredClosedPullCache, expiresAt)
	return err
}

const deleteExpiredCodeQualitySetupCache = `-- name: DeleteExpiredCodeQualitySetupCache :exec
DELETE FROM code_quality_setup_cache WHERE expires_at <= ?
`

func (q *Queries) DeleteExpiredCodeQualitySetupCache(ctx context.Context, expiresAt string) error {
	_, err := q.db.ExecContext(ctx, deleteExpiredCodeQualitySetupCache, expiresAt)
	return err
}

const deleteExpiredCommitCICache = `-- name: DeleteExpiredCommitCICache :exec
DELETE FROM commit_ci_cache WHERE expires_at <= ?
`

func (q *Queries) DeleteExpiredCommitCICache(ctx context.Context, expiresAt string) error {
	_, err := q.db.ExecContext(ctx, deleteExpiredCommitCICache, expiresAt)
	return err
}

const deleteExpiredCommitsListCache = `-- name: DeleteExpiredCommitsListCache :exec
DELETE FROM commits_list_cache WHERE expires_at <= ?
`

func (q *Queries) DeleteExpiredCommitsListCache(ctx context.Context, expiresAt string) error {
	_, err := q.db.ExecContext(ctx, deleteExpiredCommitsListCache, expiresAt)
	return err
}

const deleteExpiredCompareCache = `-- name: DeleteExpiredCompareCache :exec
DELETE FROM compare_cache WHERE expires_at <= ?
`

func (q *Queries) DeleteExpiredCompareCache(ctx context.Context, expiresAt string) error {
	_, err := q.db.ExecContext(ctx, deleteExpiredCompareCache, expiresAt)
	return err
}

const deleteExpiredContentsCache = `-- name: DeleteExpiredContentsCache :exec
DELETE FROM contents_cache WHERE expires_at <= ?
`

func (q *Queries) DeleteExpiredContentsCache(ctx context.Context, expiresAt string) error {
	_, err := q.db.ExecContext(ctx, deleteExpiredContentsCache, expiresAt)
	return err
}

const deleteExpiredGitCommitMissCache = `-- name: DeleteExpiredGitCommitMissCache :exec
DELETE FROM git_commit_miss_cache WHERE expires_at <= ?
`

func (q *Queries) DeleteExpiredGitCommitMissCache(ctx context.Context, expiresAt string) error {
	_, err := q.db.ExecContext(ctx, deleteExpiredGitCommitMissCache, expiresAt)
	return err
}

const deleteExpiredGitRefCache = `-- name: DeleteExpiredGitRefCache :exec
DELETE FROM git_ref_cache WHERE expires_at <= ?
`

func (q *Queries) DeleteExpiredGitRefCache(ctx context.Context, expiresAt string) error {
	_, err := q.db.ExecContext(ctx, deleteExpiredGitRefCache, expiresAt)
	return err
}

const deleteExpiredInstallTokenCache = `-- name: DeleteExpiredInstallTokenCache :exec
DELETE FROM install_token_cache WHERE expires_at <= ?
`

func (q *Queries) DeleteExpiredInstallTokenCache(ctx context.Context, expiresAt string) error {
	_, err := q.db.ExecContext(ctx, deleteExpiredInstallTokenCache, expiresAt)
	return err
}

const deleteExpiredInstallationReposCache = `-- name: DeleteExpiredInstallationReposCache :exec
DELETE FROM installation_repos_cache WHERE expires_at <= ?
`

func (q *Queries) DeleteExpiredInstallationReposCache(ctx context.Context, expiresAt string) error {
	_, err := q.db.ExecContext(ctx, deleteExpiredInstallationReposCache, expiresAt)
	return err
}

const deleteExpiredLabelCache = `-- name: DeleteExpiredLabelCache :exec
DELETE FROM label_cache WHERE expires_at <= ?
`

func (q *Queries) DeleteExpiredLabelCache(ctx context.Context, expiresAt string) error {
	_, err := q.db.ExecContext(ctx, deleteExpiredLabelCache, expiresAt)
	return err
}

const deleteExpiredPullDiff406Cache = `-- name: DeleteExpiredPullDiff406Cache :exec
DELETE FROM pull_diff406_cache WHERE expires_at <= ?
`

func (q *Queries) DeleteExpiredPullDiff406Cache(ctx context.Context, expiresAt string) error {
	_, err := q.db.ExecContext(ctx, deleteExpiredPullDiff406Cache, expiresAt)
	return err
}

const deleteExpiredPullFilesCache = `-- name: DeleteExpiredPullFilesCache :exec
DELETE FROM pull_files_cache WHERE expires_at <= ?
`

func (q *Queries) DeleteExpiredPullFilesCache(ctx context.Context, expiresAt string) error {
	_, err := q.db.ExecContext(ctx, deleteExpiredPullFilesCache, expiresAt)
	return err
}

const deleteExpiredPullsListMarkers = `-- name: DeleteExpiredPullsListMarkers :exec
DELETE FROM pulls_list_cache WHERE expires_at <= ?
`

func (q *Queries) DeleteExpiredPullsListMarkers(ctx context.Context, expiresAt string) error {
	_, err := q.db.ExecContext(ctx, deleteExpiredPullsListMarkers, expiresAt)
	return err
}

const deleteExpiredRepoInstallationCache = `-- name: DeleteExpiredRepoInstallationCache :exec
DELETE FROM repo_installation_cache WHERE expires_at <= ?
`

func (q *Queries) DeleteExpiredRepoInstallationCache(ctx context.Context, expiresAt string) error {
	_, err := q.db.ExecContext(ctx, deleteExpiredRepoInstallationCache, expiresAt)
	return err
}

const deleteExpiredWorkflowJobsCache = `-- name: DeleteExpiredWorkflowJobsCache :exec
DELETE FROM workflow_jobs_cache WHERE expires_at <= ?
`

func (q *Queries) DeleteExpiredWorkflowJobsCache(ctx context.Context, expiresAt string) error {
	_, err := q.db.ExecContext(ctx, deleteExpiredWorkflowJobsCache, expiresAt)
	return err
}

const deleteExpiredWorkflowRunsCache = `-- name: DeleteExpiredWorkflowRunsCache :exec
DELETE FROM workflow_runs_cache WHERE expires_at <= ?
`

func (q *Queries) DeleteExpiredWorkflowRunsCache(ctx context.Context, expiresAt string) error {
	_, err := q.db.ExecContext(ctx, deleteExpiredWorkflowRunsCache, expiresAt)
	return err
}

const deleteExpiredWorkflowRunsListMarkers = `-- name: DeleteExpiredWorkflowRunsListMarkers :exec
DELETE FROM workflow_runs_list_cache WHERE expires_at <= ?
`

func (q *Queries) DeleteExpiredWorkflowRunsListMarkers(ctx context.Context, expiresAt string) error {
	_, err := q.db.ExecContext(ctx, deleteExpiredWorkflowRunsListMarkers, expiresAt)
	return err
}

const deleteGitCommitMiss = `-- name: DeleteGitCommitMiss :exec
DELETE FROM git_commit_miss_cache WHERE owner = ? AND repo = ? AND sha = ?
`

type DeleteGitCommitMissParams struct {
	Owner string
	Repo  string
	Sha   string
}

// DeleteGitCommitMiss un-misses one sha. Every real git-commit upsert runs
// it (ghdata.upsertGitCommit), so a sha that materializes -- pushed, listed,
// or compared into git_commits_cache -- stops answering 404 immediately.
func (q *Queries) DeleteGitCommitMiss(ctx context.Context, arg DeleteGitCommitMissParams) error {
	_, err := q.db.ExecContext(ctx, deleteGitCommitMiss, arg.Owner, arg.Repo, arg.Sha)
	return err
}

const deleteGitCommitMissCacheByRepo = `-- name: DeleteGitCommitMissCacheByRepo :exec
DELETE FROM git_commit_miss_cache WHERE owner = ? AND repo = ?
`

type DeleteGitCommitMissCacheByRepoParams struct {
	Owner string
	Repo  string
}

func (q *Queries) DeleteGitCommitMissCacheByRepo(ctx context.Context, arg DeleteGitCommitMissCacheByRepoParams) error {
	_, err := q.db.ExecContext(ctx, deleteGitCommitMissCacheByRepo, arg.Owner, arg.Repo)
	return err
}

const deleteGitRefCacheByRepo = `-- name: DeleteGitRefCacheByRepo :exec
DELETE FROM git_ref_cache WHERE owner = ? AND repo = ?
`

type DeleteGitRefCacheByRepoParams struct {
	Owner string
	Repo  string
}

func (q *Queries) DeleteGitRefCacheByRepo(ctx context.Context, arg DeleteGitRefCacheByRepoParams) error {
	_, err := q.db.ExecContext(ctx, deleteGitRefCacheByRepo, arg.Owner, arg.Repo)
	return err
}

const deleteGitRefCacheForRef = `-- name: DeleteGitRefCacheForRef :exec
DELETE FROM git_ref_cache WHERE owner = ? AND repo = ? AND ref = ?
`

type DeleteGitRefCacheForRefParams struct {
	Owner string
	Repo  string
	Ref   string
}

// DeleteGitRefCacheForRef drops ONE requested spelling of a ref -- the
// per-ref push flush (a push moves, creates, or deletes exactly one ref).
func (q *Queries) DeleteGitRefCacheForRef(ctx context.Context, arg DeleteGitRefCacheForRefParams) error {
	_, err := q.db.ExecContext(ctx, deleteGitRefCacheForRef, arg.Owner, arg.Repo, arg.Ref)
	return err
}

const deleteInstallTokenCacheByInstallation = `-- name: DeleteInstallTokenCacheByInstallation :exec
DELETE FROM install_token_cache WHERE installation_id = ?
`

func (q *Queries) DeleteInstallTokenCacheByInstallation(ctx context.Context, installationID string) error {
	_, err := q.db.ExecContext(ctx, deleteInstallTokenCacheByInstallation, installationID)
	return err
}

const deleteInstallTokenCacheByToken = `-- name: DeleteInstallTokenCacheByToken :exec
DELETE FROM install_token_cache WHERE token = ?
`

// DeleteInstallTokenCacheByToken drops the cached mint(s) that issued one
// exact token -- the upstream-auth-failure invalidation: a proxied call
// carrying this token came back 401/403, so the mint behind it must not
// keep serving (its grants no longer match GitHub's).
func (q *Queries) DeleteInstallTokenCacheByToken(ctx context.Context, token string) error {
	_, err := q.db.ExecContext(ctx, deleteInstallTokenCacheByToken, token)
	return err
}

const deleteLabelCacheByRepo = `-- name: DeleteLabelCacheByRepo :exec
DELETE FROM label_cache WHERE owner = ? AND repo = ?
`

type DeleteLabelCacheByRepoParams struct {
	Owner string
	Repo  string
}

// DeleteLabelCacheByRepo is the ONLY flush grain: a label event names one
// label, but a rename names two, and every requested spelling of a name is
// its own row. Label events are rare and a repo holds few labels.
func (q *Queries) DeleteLabelCacheByRepo(ctx context.Context, arg DeleteLabelCacheByRepoParams) error {
	_, err := q.db.ExecContext(ctx, deleteLabelCacheByRepo, arg.Owner, arg.Repo)
	return err
}

const deletePullDiff406CacheByRepo = `-- name: DeletePullDiff406CacheByRepo :exec
DELETE FROM pull_diff406_cache WHERE owner = ? AND repo = ?
`

type DeletePullDiff406CacheByRepoParams struct {
	Owner string
	Repo  string
}

// DeletePullDiff406CacheByRepo drops a repo's 406 verdicts -- the
// push/repository webhook flush (a base push can move a PR's three-dot diff
// across the 406 size boundary in either direction).
func (q *Queries) DeletePullDiff406CacheByRepo(ctx context.Context, arg DeletePullDiff406CacheByRepoParams) error {
	_, err := q.db.ExecContext(ctx, deletePullDiff406CacheByRepo, arg.Owner, arg.Repo)
	return err
}

const deletePullDiff406CacheForPR = `-- name: DeletePullDiff406CacheForPR :exec
DELETE FROM pull_diff406_cache WHERE owner = ? AND repo = ? AND number = ?
`

type DeletePullDiff406CacheForPRParams struct {
	Owner  string
	Repo   string
	Number int64
}

// DeletePullDiff406CacheForPR drops one PR's 406 verdict -- the
// pull_request/pull_request_review event flush (a head push or retarget can
// shrink the diff back under the boundary).
func (q *Queries) DeletePullDiff406CacheForPR(ctx context.Context, arg DeletePullDiff406CacheForPRParams) error {
	_, err := q.db.ExecContext(ctx, deletePullDiff406CacheForPR, arg.Owner, arg.Repo, arg.Number)
	return err
}

const deletePullFilesCacheByPR = `-- name: DeletePullFilesCacheByPR :exec
DELETE FROM pull_files_cache WHERE owner = ? AND repo = ? AND number = ?
`

type DeletePullFilesCacheByPRParams struct {
	Owner  string
	Repo   string
	Number int64
}

// DeletePullFilesCacheByPR drops one PR's snapshots -- the pull_request event
// flush (head pushed/synchronize -- including fork heads whose pushes we
// never see -- base retargets, reopens).
func (q *Queries) DeletePullFilesCacheByPR(ctx context.Context, arg DeletePullFilesCacheByPRParams) error {
	_, err := q.db.ExecContext(ctx, deletePullFilesCacheByPR, arg.Owner, arg.Repo, arg.Number)
	return err
}

const deletePullFilesCacheByRepo = `-- name: DeletePullFilesCacheByRepo :exec
DELETE FROM pull_files_cache WHERE owner = ? AND repo = ?
`

type DeletePullFilesCacheByRepoParams struct {
	Owner string
	Repo  string
}

// DeletePullFilesCacheByRepo drops a repo's PR-files snapshots -- the
// push/repository webhook flush (a push may have moved any same-repo PR's
// head; the belt for missed pull_request deliveries).
func (q *Queries) DeletePullFilesCacheByRepo(ctx context.Context, arg DeletePullFilesCacheByRepoParams) error {
	_, err := q.db.ExecContext(ctx, deletePullFilesCacheByRepo, arg.Owner, arg.Repo)
	return err
}

const deletePullsListMarkersByRepo = `-- name: DeletePullsListMarkersByRepo :exec
DELETE FROM pulls_list_cache WHERE owner = ? AND repo = ?
`

type DeletePullsListMarkersByRepoParams struct {
	Owner string
	Repo  string
}

// DeletePullsListMarkersByRepo drops the marker on structural events
// (repository renamed/deleted/etc.), NOT on pull_request events (those
// maintain rows and leave the marker).
func (q *Queries) DeletePullsListMarkersByRepo(ctx context.Context, arg DeletePullsListMarkersByRepoParams) error {
	_, err := q.db.ExecContext(ctx, deletePullsListMarkersByRepo, arg.Owner, arg.Repo)
	return err
}

const deleteRepoInstallationCacheByInstallation = `-- name: DeleteRepoInstallationCacheByInstallation :exec
DELETE FROM repo_installation_cache WHERE installation_id = ?
`

func (q *Queries) DeleteRepoInstallationCacheByInstallation(ctx context.Context, installationID int64) error {
	_, err := q.db.ExecContext(ctx, deleteRepoInstallationCacheByInstallation, installationID)
	return err
}

const deleteWorkflowJobsCacheByRepo = `-- name: DeleteWorkflowJobsCacheByRepo :exec
DELETE FROM workflow_jobs_cache WHERE owner = ? AND repo = ?
`

type DeleteWorkflowJobsCacheByRepoParams struct {
	Owner string
	Repo  string
}

func (q *Queries) DeleteWorkflowJobsCacheByRepo(ctx context.Context, arg DeleteWorkflowJobsCacheByRepoParams) error {
	_, err := q.db.ExecContext(ctx, deleteWorkflowJobsCacheByRepo, arg.Owner, arg.Repo)
	return err
}

const deleteWorkflowJobsCacheForRun = `-- name: DeleteWorkflowJobsCacheForRun :exec
DELETE FROM workflow_jobs_cache WHERE owner = ? AND repo = ? AND run_id = ?
`

type DeleteWorkflowJobsCacheForRunParams struct {
	Owner string
	Repo  string
	RunID int64
}

// DeleteWorkflowJobsCacheForRun drops every row a run's jobs back -- both the
// run's own jobs pages and the single-job rows under it. A re-run replaces a
// run's jobs under the SAME run id, so this is the flush that matters.
func (q *Queries) DeleteWorkflowJobsCacheForRun(ctx context.Context, arg DeleteWorkflowJobsCacheForRunParams) error {
	_, err := q.db.ExecContext(ctx, deleteWorkflowJobsCacheForRun, arg.Owner, arg.Repo, arg.RunID)
	return err
}

const deleteWorkflowRunsByRepo = `-- name: DeleteWorkflowRunsByRepo :exec
DELETE FROM workflow_runs WHERE owner = ? AND repo = ?
`

type DeleteWorkflowRunsByRepoParams struct {
	Owner string
	Repo  string
}

func (q *Queries) DeleteWorkflowRunsByRepo(ctx context.Context, arg DeleteWorkflowRunsByRepoParams) error {
	_, err := q.db.ExecContext(ctx, deleteWorkflowRunsByRepo, arg.Owner, arg.Repo)
	return err
}

const deleteWorkflowRunsCacheByRepo = `-- name: DeleteWorkflowRunsCacheByRepo :exec
DELETE FROM workflow_runs_cache WHERE owner = ? AND repo = ?
`

type DeleteWorkflowRunsCacheByRepoParams struct {
	Owner string
	Repo  string
}

// DeleteWorkflowRunsCacheByRepo drops a repo's workflow-runs snapshots --
// the repository webhook flush and the sha-less payload fallback.
func (q *Queries) DeleteWorkflowRunsCacheByRepo(ctx context.Context, arg DeleteWorkflowRunsCacheByRepoParams) error {
	_, err := q.db.ExecContext(ctx, deleteWorkflowRunsCacheByRepo, arg.Owner, arg.Repo)
	return err
}

const deleteWorkflowRunsCacheForHeadSHA = `-- name: DeleteWorkflowRunsCacheForHeadSHA :exec
DELETE FROM workflow_runs_cache WHERE owner = ? AND repo = ? AND head_sha = ?
`

type DeleteWorkflowRunsCacheForHeadSHAParams struct {
	Owner   string
	Repo    string
	HeadSha string
}

// DeleteWorkflowRunsCacheForHeadSHA drops one sha's snapshots (all pages) --
// the per-sha status/check_run/check_suite/workflow_job flush. Other shas'
// snapshots survive.
func (q *Queries) DeleteWorkflowRunsCacheForHeadSHA(ctx context.Context, arg DeleteWorkflowRunsCacheForHeadSHAParams) error {
	_, err := q.db.ExecContext(ctx, deleteWorkflowRunsCacheForHeadSHA, arg.Owner, arg.Repo, arg.HeadSha)
	return err
}

const deleteWorkflowRunsListMarkers = `-- name: DeleteWorkflowRunsListMarkers :exec
DELETE FROM workflow_runs_list_cache WHERE owner = ? AND repo = ?
`

type DeleteWorkflowRunsListMarkersParams struct {
	Owner string
	Repo  string
}

// DeleteWorkflowRunsListMarkers clears a repo's completeness proofs. Only
// repository events (and the expiry) do this -- a run delivery MAINTAINS the
// rows the marker vouches for, so it must never clear the marker.
func (q *Queries) DeleteWorkflowRunsListMarkers(ctx context.Context, arg DeleteWorkflowRunsListMarkersParams) error {
	_, err := q.db.ExecContext(ctx, deleteWorkflowRunsListMarkers, arg.Owner, arg.Repo)
	return err
}

const deleteWorkflowRunsNotIn = `-- name: DeleteWorkflowRunsNotIn :exec
DELETE FROM workflow_runs
WHERE owner = ?1 AND repo = ?2
  AND (?3 = '' OR status = ?3 OR conclusion = ?3)
  AND (?4 = '' OR head_branch = ?4)
  AND (?5 = '' OR head_sha = ?5)
  AND run_id NOT IN (/*SLICE:kept*/?)
`

type DeleteWorkflowRunsNotInParams struct {
	Owner      string
	Repo       string
	Status     interface{}
	HeadBranch interface{}
	HeadSha    interface{}
	Kept       []int64
}

// DeleteWorkflowRunsNotIn drops the rows a reconciling absorb proved stale:
// runs that still MATCH the filter in truth but were absent from a short
// page-1 response for that same filter. Their state provably moved and the
// response did not say where to, so the row goes and the next read re-absorbs
// it. sqlc.slice expands to the run ids the response did contain.
func (q *Queries) DeleteWorkflowRunsNotIn(ctx context.Context, arg DeleteWorkflowRunsNotInParams) error {
	query := deleteWorkflowRunsNotIn
	var queryParams []interface{}
	queryParams = append(queryParams, arg.Owner)
	queryParams = append(queryParams, arg.Repo)
	queryParams = append(queryParams, arg.Status)
	queryParams = append(queryParams, arg.HeadBranch)
	queryParams = append(queryParams, arg.HeadSha)
	if len(arg.Kept) > 0 {
		for _, v := range arg.Kept {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:kept*/?", strings.Repeat(",?", len(arg.Kept))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:kept*/?", "NULL", 1)
	}
	_, err := q.db.ExecContext(ctx, query, queryParams...)
	return err
}

const getBranchesListCache = `-- name: GetBranchesListCache :one

SELECT id, owner, repo, per_page, page, doc, fetched_at, expires_at, last_used_at FROM branches_list_cache
WHERE owner = ? AND repo = ? AND per_page = ? AND page = ?
`

type GetBranchesListCacheParams struct {
	Owner   string
	Repo    string
	PerPage int64
	Page    int64
}

// ---- branches_list_cache (GET /repos/{owner}/{repo}/branches) ----
func (q *Queries) GetBranchesListCache(ctx context.Context, arg GetBranchesListCacheParams) (BranchesListCache, error) {
	row := q.db.QueryRowContext(ctx, getBranchesListCache,
		arg.Owner,
		arg.Repo,
		arg.PerPage,
		arg.Page,
	)
	var i BranchesListCache
	err := row.Scan(
		&i.ID,
		&i.Owner,
		&i.Repo,
		&i.PerPage,
		&i.Page,
		&i.Doc,
		&i.FetchedAt,
		&i.ExpiresAt,
		&i.LastUsedAt,
	)
	return i, err
}

const getClosedPullCache = `-- name: GetClosedPullCache :one

SELECT id, owner, repo, number, doc, fetched_at, expires_at, last_used_at FROM closed_pull_cache
WHERE owner = ? AND repo = ? AND number = ?
`

type GetClosedPullCacheParams struct {
	Owner  string
	Repo   string
	Number int64
}

// ---- closed_pull_cache (closed answers for GET /repos/{owner}/{repo}/pulls/{number}) ----
func (q *Queries) GetClosedPullCache(ctx context.Context, arg GetClosedPullCacheParams) (ClosedPullCache, error) {
	row := q.db.QueryRowContext(ctx, getClosedPullCache, arg.Owner, arg.Repo, arg.Number)
	var i ClosedPullCache
	err := row.Scan(
		&i.ID,
		&i.Owner,
		&i.Repo,
		&i.Number,
		&i.Doc,
		&i.FetchedAt,
		&i.ExpiresAt,
		&i.LastUsedAt,
	)
	return i, err
}

const getCodeQualitySetupCache = `-- name: GetCodeQualitySetupCache :one

SELECT id, owner, repo, doc, fetched_at, expires_at, last_used_at FROM code_quality_setup_cache WHERE owner = ? AND repo = ?
`

type GetCodeQualitySetupCacheParams struct {
	Owner string
	Repo  string
}

// ---- code_quality_setup_cache (GET /repos/{owner}/{repo}/code-quality/setup) ----
func (q *Queries) GetCodeQualitySetupCache(ctx context.Context, arg GetCodeQualitySetupCacheParams) (CodeQualitySetupCache, error) {
	row := q.db.QueryRowContext(ctx, getCodeQualitySetupCache, arg.Owner, arg.Repo)
	var i CodeQualitySetupCache
	err := row.Scan(
		&i.ID,
		&i.Owner,
		&i.Repo,
		&i.Doc,
		&i.FetchedAt,
		&i.ExpiresAt,
		&i.LastUsedAt,
	)
	return i, err
}

const getCommitCICache = `-- name: GetCommitCICache :one

SELECT id, owner, repo, ref, kind, per_page, page, doc, fetched_at, expires_at, last_used_at FROM commit_ci_cache
WHERE owner = ? AND repo = ? AND ref = ? AND kind = ? AND per_page = ? AND page = ?
`

type GetCommitCICacheParams struct {
	Owner   string
	Repo    string
	Ref     string
	Kind    string
	PerPage int64
	Page    int64
}

// ---- commit_ci_cache (GET /repos/{owner}/{repo}/commits/{ref}/status,
// ---- GET .../commits/{ref}/check-runs, and GET .../commits/{ref}/statuses) ----
func (q *Queries) GetCommitCICache(ctx context.Context, arg GetCommitCICacheParams) (CommitCiCache, error) {
	row := q.db.QueryRowContext(ctx, getCommitCICache,
		arg.Owner,
		arg.Repo,
		arg.Ref,
		arg.Kind,
		arg.PerPage,
		arg.Page,
	)
	var i CommitCiCache
	err := row.Scan(
		&i.ID,
		&i.Owner,
		&i.Repo,
		&i.Ref,
		&i.Kind,
		&i.PerPage,
		&i.Page,
		&i.Doc,
		&i.FetchedAt,
		&i.ExpiresAt,
		&i.LastUsedAt,
	)
	return i, err
}

const getCommitsListCache = `-- name: GetCommitsListCache :one

SELECT id, owner, repo, ref_param, per_page, page, shas, fetched_at, expires_at, last_used_at FROM commits_list_cache
WHERE owner = ? AND repo = ? AND ref_param = ? AND per_page = ? AND page = ?
`

type GetCommitsListCacheParams struct {
	Owner    string
	Repo     string
	RefParam string
	PerPage  int64
	Page     int64
}

// ---- commits_list_cache (per-page snapshots for the commits LIST route) ----
func (q *Queries) GetCommitsListCache(ctx context.Context, arg GetCommitsListCacheParams) (CommitsListCache, error) {
	row := q.db.QueryRowContext(ctx, getCommitsListCache,
		arg.Owner,
		arg.Repo,
		arg.RefParam,
		arg.PerPage,
		arg.Page,
	)
	var i CommitsListCache
	err := row.Scan(
		&i.ID,
		&i.Owner,
		&i.Repo,
		&i.RefParam,
		&i.PerPage,
		&i.Page,
		&i.Shas,
		&i.FetchedAt,
		&i.ExpiresAt,
		&i.LastUsedAt,
	)
	return i, err
}

const getCompareCache = `-- name: GetCompareCache :one

SELECT id, owner, repo, basehead, base_ref, head_ref, status, doc, fetched_at, expires_at, last_used_at FROM compare_cache
WHERE owner = ? AND repo = ? AND basehead = ?
`

type GetCompareCacheParams struct {
	Owner    string
	Repo     string
	Basehead string
}

// ---- compare_cache (GET /repos/{owner}/{repo}/compare/{basehead}) ----
func (q *Queries) GetCompareCache(ctx context.Context, arg GetCompareCacheParams) (CompareCache, error) {
	row := q.db.QueryRowContext(ctx, getCompareCache, arg.Owner, arg.Repo, arg.Basehead)
	var i CompareCache
	err := row.Scan(
		&i.ID,
		&i.Owner,
		&i.Repo,
		&i.Basehead,
		&i.BaseRef,
		&i.HeadRef,
		&i.Status,
		&i.Doc,
		&i.FetchedAt,
		&i.ExpiresAt,
		&i.LastUsedAt,
	)
	return i, err
}

const getContentsCache = `-- name: GetContentsCache :one


SELECT id, owner, repo, path, ref, kind, name, sha, size, encoding, content, entries, message, fetched_at, expires_at, last_used_at FROM contents_cache
WHERE owner = ? AND repo = ? AND path = ? AND ref = ?
`

type GetContentsCacheParams struct {
	Owner string
	Repo  string
	Path  string
	Ref   string
}

// ============================================================================
// Cached-route response state (contents / git commits / installation tokens)
// ============================================================================
//
// contents_cache and git_commits_cache are GLOBAL truth (one row per resource);
// whether a caller may read a row is the reveal layer's job (see the
// access_grants queries in ghdata.sql). install_token_cache and
// repo_installations stay keyed by the verified app identity: they cache
// app-specific answers (a minted credential; which installation covers a
// repo), not shared GitHub state.
// ---- contents_cache ----
func (q *Queries) GetContentsCache(ctx context.Context, arg GetContentsCacheParams) (ContentsCache, error) {
	row := q.db.QueryRowContext(ctx, getContentsCache,
		arg.Owner,
		arg.Repo,
		arg.Path,
		arg.Ref,
	)
	var i ContentsCache
	err := row.Scan(
		&i.ID,
		&i.Owner,
		&i.Repo,
		&i.Path,
		&i.Ref,
		&i.Kind,
		&i.Name,
		&i.Sha,
		&i.Size,
		&i.Encoding,
		&i.Content,
		&i.Entries,
		&i.Message,
		&i.FetchedAt,
		&i.ExpiresAt,
		&i.LastUsedAt,
	)
	return i, err
}

const getGitCommitCache = `-- name: GetGitCommitCache :one

SELECT id, owner, repo, sha, message, author_name, author_email, author_date, committer_name, committer_email, committer_date, tree_sha, parents, fetched_at, last_used_at FROM git_commits_cache
WHERE owner = ? AND repo = ? AND sha = ?
`

type GetGitCommitCacheParams struct {
	Owner string
	Repo  string
	Sha   string
}

// ---- git_commits_cache ----
func (q *Queries) GetGitCommitCache(ctx context.Context, arg GetGitCommitCacheParams) (GitCommitsCache, error) {
	row := q.db.QueryRowContext(ctx, getGitCommitCache, arg.Owner, arg.Repo, arg.Sha)
	var i GitCommitsCache
	err := row.Scan(
		&i.ID,
		&i.Owner,
		&i.Repo,
		&i.Sha,
		&i.Message,
		&i.AuthorName,
		&i.AuthorEmail,
		&i.AuthorDate,
		&i.CommitterName,
		&i.CommitterEmail,
		&i.CommitterDate,
		&i.TreeSha,
		&i.Parents,
		&i.FetchedAt,
		&i.LastUsedAt,
	)
	return i, err
}

const getGitCommitMissCache = `-- name: GetGitCommitMissCache :one

SELECT id, owner, repo, sha, doc, fetched_at, expires_at, last_used_at FROM git_commit_miss_cache
WHERE owner = ? AND repo = ? AND sha = ?
`

type GetGitCommitMissCacheParams struct {
	Owner string
	Repo  string
	Sha   string
}

// ---- git_commit_miss_cache (expiring 404s for GET /repos/{owner}/{repo}/git/commits/{sha}) ----
func (q *Queries) GetGitCommitMissCache(ctx context.Context, arg GetGitCommitMissCacheParams) (GitCommitMissCache, error) {
	row := q.db.QueryRowContext(ctx, getGitCommitMissCache, arg.Owner, arg.Repo, arg.Sha)
	var i GitCommitMissCache
	err := row.Scan(
		&i.ID,
		&i.Owner,
		&i.Repo,
		&i.Sha,
		&i.Doc,
		&i.FetchedAt,
		&i.ExpiresAt,
		&i.LastUsedAt,
	)
	return i, err
}

const getGitRefCache = `-- name: GetGitRefCache :one

SELECT id, owner, repo, ref, status, doc, fetched_at, expires_at, last_used_at FROM git_ref_cache
WHERE owner = ? AND repo = ? AND ref = ?
`

type GetGitRefCacheParams struct {
	Owner string
	Repo  string
	Ref   string
}

// ---- git_ref_cache (GET /repos/{owner}/{repo}/git/ref/{ref}) ----
func (q *Queries) GetGitRefCache(ctx context.Context, arg GetGitRefCacheParams) (GitRefCache, error) {
	row := q.db.QueryRowContext(ctx, getGitRefCache, arg.Owner, arg.Repo, arg.Ref)
	var i GitRefCache
	err := row.Scan(
		&i.ID,
		&i.Owner,
		&i.Repo,
		&i.Ref,
		&i.Status,
		&i.Doc,
		&i.FetchedAt,
		&i.ExpiresAt,
		&i.LastUsedAt,
	)
	return i, err
}

const getInstallTokenCache = `-- name: GetInstallTokenCache :one

SELECT id, actor, installation_id, body_hash, token, token_expires_at, permissions, repository_selection, fetched_at, expires_at, last_used_at FROM install_token_cache
WHERE actor = ? AND installation_id = ? AND body_hash = ?
`

type GetInstallTokenCacheParams struct {
	Actor          string
	InstallationID string
	BodyHash       string
}

// ---- install_token_cache ----
func (q *Queries) GetInstallTokenCache(ctx context.Context, arg GetInstallTokenCacheParams) (InstallTokenCache, error) {
	row := q.db.QueryRowContext(ctx, getInstallTokenCache, arg.Actor, arg.InstallationID, arg.BodyHash)
	var i InstallTokenCache
	err := row.Scan(
		&i.ID,
		&i.Actor,
		&i.InstallationID,
		&i.BodyHash,
		&i.Token,
		&i.TokenExpiresAt,
		&i.Permissions,
		&i.RepositorySelection,
		&i.FetchedAt,
		&i.ExpiresAt,
		&i.LastUsedAt,
	)
	return i, err
}

const getInstallationReposCache = `-- name: GetInstallationReposCache :one

SELECT id, token_fp, per_page, page, doc, fetched_at, expires_at, last_used_at FROM installation_repos_cache
WHERE token_fp = ? AND per_page = ? AND page = ?
`

type GetInstallationReposCacheParams struct {
	TokenFp string
	PerPage int64
	Page    int64
}

// ---- installation_repos_cache (GET /installation/repositories) ----
func (q *Queries) GetInstallationReposCache(ctx context.Context, arg GetInstallationReposCacheParams) (InstallationReposCache, error) {
	row := q.db.QueryRowContext(ctx, getInstallationReposCache, arg.TokenFp, arg.PerPage, arg.Page)
	var i InstallationReposCache
	err := row.Scan(
		&i.ID,
		&i.TokenFp,
		&i.PerPage,
		&i.Page,
		&i.Doc,
		&i.FetchedAt,
		&i.ExpiresAt,
		&i.LastUsedAt,
	)
	return i, err
}

const getLabelCache = `-- name: GetLabelCache :one

SELECT id, owner, repo, name, doc, fetched_at, expires_at, last_used_at FROM label_cache WHERE owner = ? AND repo = ? AND name = ?
`

type GetLabelCacheParams struct {
	Owner string
	Repo  string
	Name  string
}

// ---- label_cache (GET /repos/{owner}/{repo}/labels/{name}) ----
func (q *Queries) GetLabelCache(ctx context.Context, arg GetLabelCacheParams) (LabelCache, error) {
	row := q.db.QueryRowContext(ctx, getLabelCache, arg.Owner, arg.Repo, arg.Name)
	var i LabelCache
	err := row.Scan(
		&i.ID,
		&i.Owner,
		&i.Repo,
		&i.Name,
		&i.Doc,
		&i.FetchedAt,
		&i.ExpiresAt,
		&i.LastUsedAt,
	)
	return i, err
}

const getPullDiff406Cache = `-- name: GetPullDiff406Cache :one

SELECT id, owner, repo, number, doc, fetched_at, expires_at, last_used_at FROM pull_diff406_cache
WHERE owner = ? AND repo = ? AND number = ?
`

type GetPullDiff406CacheParams struct {
	Owner  string
	Repo   string
	Number int64
}

// ---- pull_diff406_cache (406 verdicts for the single-PR diff read) ----
func (q *Queries) GetPullDiff406Cache(ctx context.Context, arg GetPullDiff406CacheParams) (PullDiff406Cache, error) {
	row := q.db.QueryRowContext(ctx, getPullDiff406Cache, arg.Owner, arg.Repo, arg.Number)
	var i PullDiff406Cache
	err := row.Scan(
		&i.ID,
		&i.Owner,
		&i.Repo,
		&i.Number,
		&i.Doc,
		&i.FetchedAt,
		&i.ExpiresAt,
		&i.LastUsedAt,
	)
	return i, err
}

const getPullFilesCache = `-- name: GetPullFilesCache :one

SELECT id, owner, repo, number, per_page, page, doc, fetched_at, expires_at, last_used_at FROM pull_files_cache
WHERE owner = ? AND repo = ? AND number = ? AND per_page = ? AND page = ?
`

type GetPullFilesCacheParams struct {
	Owner   string
	Repo    string
	Number  int64
	PerPage int64
	Page    int64
}

// ---- pull_files_cache (GET /repos/{owner}/{repo}/pulls/{number}/files) ----
func (q *Queries) GetPullFilesCache(ctx context.Context, arg GetPullFilesCacheParams) (PullFilesCache, error) {
	row := q.db.QueryRowContext(ctx, getPullFilesCache,
		arg.Owner,
		arg.Repo,
		arg.Number,
		arg.PerPage,
		arg.Page,
	)
	var i PullFilesCache
	err := row.Scan(
		&i.ID,
		&i.Owner,
		&i.Repo,
		&i.Number,
		&i.PerPage,
		&i.Page,
		&i.Doc,
		&i.FetchedAt,
		&i.ExpiresAt,
		&i.LastUsedAt,
	)
	return i, err
}

const getPullsListMarker = `-- name: GetPullsListMarker :one

SELECT id, owner, repo, fetched_at, expires_at, last_used_at FROM pulls_list_cache
WHERE owner = ? AND repo = ?
`

type GetPullsListMarkerParams struct {
	Owner string
	Repo  string
}

// ---- pulls_list_cache (the "open-PR list complete" markers) ----
func (q *Queries) GetPullsListMarker(ctx context.Context, arg GetPullsListMarkerParams) (PullsListCache, error) {
	row := q.db.QueryRowContext(ctx, getPullsListMarker, arg.Owner, arg.Repo)
	var i PullsListCache
	err := row.Scan(
		&i.ID,
		&i.Owner,
		&i.Repo,
		&i.FetchedAt,
		&i.ExpiresAt,
		&i.LastUsedAt,
	)
	return i, err
}

const getRepoInstallationCache = `-- name: GetRepoInstallationCache :one

SELECT id, actor, owner, repo, status, message, installation_id, account_login, account_type, repository_selection, app_id, app_slug, target_type, fetched_at, expires_at, last_used_at FROM repo_installation_cache
WHERE actor = ? AND owner = ? AND repo = ?
`

type GetRepoInstallationCacheParams struct {
	Actor string
	Owner string
	Repo  string
}

// ---- repo_installation_cache (GET /repos/{owner}/{repo}/installation) ----
func (q *Queries) GetRepoInstallationCache(ctx context.Context, arg GetRepoInstallationCacheParams) (RepoInstallationCache, error) {
	row := q.db.QueryRowContext(ctx, getRepoInstallationCache, arg.Actor, arg.Owner, arg.Repo)
	var i RepoInstallationCache
	err := row.Scan(
		&i.ID,
		&i.Actor,
		&i.Owner,
		&i.Repo,
		&i.Status,
		&i.Message,
		&i.InstallationID,
		&i.AccountLogin,
		&i.AccountType,
		&i.RepositorySelection,
		&i.AppID,
		&i.AppSlug,
		&i.TargetType,
		&i.FetchedAt,
		&i.ExpiresAt,
		&i.LastUsedAt,
	)
	return i, err
}

const getWorkflowJobsCache = `-- name: GetWorkflowJobsCache :one

SELECT id, owner, repo, kind, ref_id, run_id, per_page, page, doc, fetched_at, expires_at, last_used_at FROM workflow_jobs_cache
WHERE owner = ? AND repo = ? AND kind = ? AND ref_id = ? AND per_page = ? AND page = ?
`

type GetWorkflowJobsCacheParams struct {
	Owner   string
	Repo    string
	Kind    string
	RefID   int64
	PerPage int64
	Page    int64
}

// ---- workflow_jobs_cache (Actions job reads) ----
func (q *Queries) GetWorkflowJobsCache(ctx context.Context, arg GetWorkflowJobsCacheParams) (WorkflowJobsCache, error) {
	row := q.db.QueryRowContext(ctx, getWorkflowJobsCache,
		arg.Owner,
		arg.Repo,
		arg.Kind,
		arg.RefID,
		arg.PerPage,
		arg.Page,
	)
	var i WorkflowJobsCache
	err := row.Scan(
		&i.ID,
		&i.Owner,
		&i.Repo,
		&i.Kind,
		&i.RefID,
		&i.RunID,
		&i.PerPage,
		&i.Page,
		&i.Doc,
		&i.FetchedAt,
		&i.ExpiresAt,
		&i.LastUsedAt,
	)
	return i, err
}

const getWorkflowRunsCache = `-- name: GetWorkflowRunsCache :one

SELECT id, owner, repo, head_sha, per_page, page, doc, fetched_at, expires_at, last_used_at FROM workflow_runs_cache
WHERE owner = ? AND repo = ? AND head_sha = ? AND per_page = ? AND page = ?
`

type GetWorkflowRunsCacheParams struct {
	Owner   string
	Repo    string
	HeadSha string
	PerPage int64
	Page    int64
}

// ---- workflow_runs_cache (GET /repos/{owner}/{repo}/actions/runs?head_sha=) ----
func (q *Queries) GetWorkflowRunsCache(ctx context.Context, arg GetWorkflowRunsCacheParams) (WorkflowRunsCache, error) {
	row := q.db.QueryRowContext(ctx, getWorkflowRunsCache,
		arg.Owner,
		arg.Repo,
		arg.HeadSha,
		arg.PerPage,
		arg.Page,
	)
	var i WorkflowRunsCache
	err := row.Scan(
		&i.ID,
		&i.Owner,
		&i.Repo,
		&i.HeadSha,
		&i.PerPage,
		&i.Page,
		&i.Doc,
		&i.FetchedAt,
		&i.ExpiresAt,
		&i.LastUsedAt,
	)
	return i, err
}

const getWorkflowRunsListMarker = `-- name: GetWorkflowRunsListMarker :one
SELECT owner, repo, filters, fetched_at, expires_at FROM workflow_runs_list_cache WHERE owner = ? AND repo = ? AND filters = ?
`

type GetWorkflowRunsListMarkerParams struct {
	Owner   string
	Repo    string
	Filters string
}

func (q *Queries) GetWorkflowRunsListMarker(ctx context.Context, arg GetWorkflowRunsListMarkerParams) (WorkflowRunsListCache, error) {
	row := q.db.QueryRowContext(ctx, getWorkflowRunsListMarker, arg.Owner, arg.Repo, arg.Filters)
	var i WorkflowRunsListCache
	err := row.Scan(
		&i.Owner,
		&i.Repo,
		&i.Filters,
		&i.FetchedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const listWorkflowRuns = `-- name: ListWorkflowRuns :many
SELECT owner, repo, run_id, run_attempt, name, head_sha, head_branch, status, conclusion, html_url, created_at, updated_at, run_started_at, touched_at FROM workflow_runs
WHERE owner = ?1 AND repo = ?2
  AND (?3 = '' OR status = ?3 OR conclusion = ?3)
  AND (?4 = '' OR head_branch = ?4)
  AND (?5 = '' OR head_sha = ?5)
ORDER BY created_at DESC, run_id DESC
LIMIT ?7 OFFSET ?6
`

type ListWorkflowRunsParams struct {
	Owner      string
	Repo       string
	Status     interface{}
	HeadBranch interface{}
	HeadSha    interface{}
	PageOffset int64
	PageSize   int64
}

// ListWorkflowRuns returns one page of a repo's runs, newest first (GitHub's
// own ordering), optionally filtered by status and/or head branch and/or head
// sha. An empty filter argument means "no filter on this field".
// The `status` filter matches a run's status OR its CONCLUSION, because
// GitHub's own filter does: ?status=success selects completed runs that
// succeeded, while ?status=queued selects by status. Matching only the status
// column would answer ?status=success with nothing.
//
// Every parameter here is NAMED on purpose: sqlc numbers `?` placeholders and
// sqlc.arg() references in one shared sequence, so mixing the two silently
// misaligns the bindings ("missing argument with index N" at run time).
func (q *Queries) ListWorkflowRuns(ctx context.Context, arg ListWorkflowRunsParams) ([]WorkflowRun, error) {
	rows, err := q.db.QueryContext(ctx, listWorkflowRuns,
		arg.Owner,
		arg.Repo,
		arg.Status,
		arg.HeadBranch,
		arg.HeadSha,
		arg.PageOffset,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WorkflowRun
	for rows.Next() {
		var i WorkflowRun
		if err := rows.Scan(
			&i.Owner,
			&i.Repo,
			&i.RunID,
			&i.RunAttempt,
			&i.Name,
			&i.HeadSha,
			&i.HeadBranch,
			&i.Status,
			&i.Conclusion,
			&i.HtmlUrl,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.RunStartedAt,
			&i.TouchedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const pruneBranchesListCacheLRU = `-- name: PruneBranchesListCacheLRU :exec
DELETE FROM branches_list_cache WHERE id IN (
    SELECT id FROM branches_list_cache ORDER BY last_used_at DESC LIMIT -1 OFFSET ?
)
`

func (q *Queries) PruneBranchesListCacheLRU(ctx context.Context, offset int64) error {
	_, err := q.db.ExecContext(ctx, pruneBranchesListCacheLRU, offset)
	return err
}

const pruneClosedPullCacheLRU = `-- name: PruneClosedPullCacheLRU :exec
DELETE FROM closed_pull_cache WHERE id IN (
    SELECT id FROM closed_pull_cache ORDER BY last_used_at DESC LIMIT -1 OFFSET ?
)
`

func (q *Queries) PruneClosedPullCacheLRU(ctx context.Context, offset int64) error {
	_, err := q.db.ExecContext(ctx, pruneClosedPullCacheLRU, offset)
	return err
}

const pruneCodeQualitySetupCacheLRU = `-- name: PruneCodeQualitySetupCacheLRU :exec
DELETE FROM code_quality_setup_cache WHERE id IN (
    SELECT id FROM code_quality_setup_cache ORDER BY last_used_at DESC LIMIT -1 OFFSET ?
)
`

func (q *Queries) PruneCodeQualitySetupCacheLRU(ctx context.Context, offset int64) error {
	_, err := q.db.ExecContext(ctx, pruneCodeQualitySetupCacheLRU, offset)
	return err
}

const pruneCommitCICacheLRU = `-- name: PruneCommitCICacheLRU :exec
DELETE FROM commit_ci_cache WHERE id IN (
    SELECT id FROM commit_ci_cache ORDER BY last_used_at DESC LIMIT -1 OFFSET ?
)
`

func (q *Queries) PruneCommitCICacheLRU(ctx context.Context, offset int64) error {
	_, err := q.db.ExecContext(ctx, pruneCommitCICacheLRU, offset)
	return err
}

const pruneCommitsListCacheLRU = `-- name: PruneCommitsListCacheLRU :exec
DELETE FROM commits_list_cache WHERE id IN (
    SELECT id FROM commits_list_cache ORDER BY last_used_at DESC LIMIT -1 OFFSET ?
)
`

func (q *Queries) PruneCommitsListCacheLRU(ctx context.Context, offset int64) error {
	_, err := q.db.ExecContext(ctx, pruneCommitsListCacheLRU, offset)
	return err
}

const pruneCompareCacheLRU = `-- name: PruneCompareCacheLRU :exec
DELETE FROM compare_cache WHERE id IN (
    SELECT id FROM compare_cache ORDER BY last_used_at DESC LIMIT -1 OFFSET ?
)
`

func (q *Queries) PruneCompareCacheLRU(ctx context.Context, offset int64) error {
	_, err := q.db.ExecContext(ctx, pruneCompareCacheLRU, offset)
	return err
}

const pruneContentsCacheLRU = `-- name: PruneContentsCacheLRU :exec
DELETE FROM contents_cache WHERE id IN (
    SELECT id FROM contents_cache ORDER BY last_used_at DESC LIMIT -1 OFFSET ?
)
`

// PruneContentsCacheLRU keeps only the most recently used rows. The subquery
// selects everything beyond the newest `offset` rows by last_used_at; LIMIT -1
// means "no limit" in SQLite, so OFFSET skips the keepers.
func (q *Queries) PruneContentsCacheLRU(ctx context.Context, offset int64) error {
	_, err := q.db.ExecContext(ctx, pruneContentsCacheLRU, offset)
	return err
}

const pruneGitCommitMissCacheLRU = `-- name: PruneGitCommitMissCacheLRU :exec
DELETE FROM git_commit_miss_cache WHERE id IN (
    SELECT id FROM git_commit_miss_cache ORDER BY last_used_at DESC LIMIT -1 OFFSET ?
)
`

func (q *Queries) PruneGitCommitMissCacheLRU(ctx context.Context, offset int64) error {
	_, err := q.db.ExecContext(ctx, pruneGitCommitMissCacheLRU, offset)
	return err
}

const pruneGitCommitsCacheLRU = `-- name: PruneGitCommitsCacheLRU :exec
DELETE FROM git_commits_cache WHERE id IN (
    SELECT id FROM git_commits_cache ORDER BY last_used_at DESC LIMIT -1 OFFSET ?
)
`

func (q *Queries) PruneGitCommitsCacheLRU(ctx context.Context, offset int64) error {
	_, err := q.db.ExecContext(ctx, pruneGitCommitsCacheLRU, offset)
	return err
}

const pruneGitRefCacheLRU = `-- name: PruneGitRefCacheLRU :exec
DELETE FROM git_ref_cache WHERE id IN (
    SELECT id FROM git_ref_cache ORDER BY last_used_at DESC LIMIT -1 OFFSET ?
)
`

func (q *Queries) PruneGitRefCacheLRU(ctx context.Context, offset int64) error {
	_, err := q.db.ExecContext(ctx, pruneGitRefCacheLRU, offset)
	return err
}

const pruneInstallTokenCacheLRU = `-- name: PruneInstallTokenCacheLRU :exec
DELETE FROM install_token_cache WHERE id IN (
    SELECT id FROM install_token_cache ORDER BY last_used_at DESC LIMIT -1 OFFSET ?
)
`

func (q *Queries) PruneInstallTokenCacheLRU(ctx context.Context, offset int64) error {
	_, err := q.db.ExecContext(ctx, pruneInstallTokenCacheLRU, offset)
	return err
}

const pruneInstallationReposCacheLRU = `-- name: PruneInstallationReposCacheLRU :exec
DELETE FROM installation_repos_cache WHERE id IN (
    SELECT id FROM installation_repos_cache ORDER BY last_used_at DESC LIMIT -1 OFFSET ?
)
`

func (q *Queries) PruneInstallationReposCacheLRU(ctx context.Context, offset int64) error {
	_, err := q.db.ExecContext(ctx, pruneInstallationReposCacheLRU, offset)
	return err
}

const pruneLabelCacheLRU = `-- name: PruneLabelCacheLRU :exec
DELETE FROM label_cache WHERE id IN (
    SELECT id FROM label_cache ORDER BY last_used_at DESC LIMIT -1 OFFSET ?
)
`

func (q *Queries) PruneLabelCacheLRU(ctx context.Context, offset int64) error {
	_, err := q.db.ExecContext(ctx, pruneLabelCacheLRU, offset)
	return err
}

const prunePullDiff406CacheLRU = `-- name: PrunePullDiff406CacheLRU :exec
DELETE FROM pull_diff406_cache WHERE id IN (
    SELECT id FROM pull_diff406_cache ORDER BY last_used_at DESC LIMIT -1 OFFSET ?
)
`

func (q *Queries) PrunePullDiff406CacheLRU(ctx context.Context, offset int64) error {
	_, err := q.db.ExecContext(ctx, prunePullDiff406CacheLRU, offset)
	return err
}

const prunePullFilesCacheLRU = `-- name: PrunePullFilesCacheLRU :exec
DELETE FROM pull_files_cache WHERE id IN (
    SELECT id FROM pull_files_cache ORDER BY last_used_at DESC LIMIT -1 OFFSET ?
)
`

func (q *Queries) PrunePullFilesCacheLRU(ctx context.Context, offset int64) error {
	_, err := q.db.ExecContext(ctx, prunePullFilesCacheLRU, offset)
	return err
}

const prunePullsListMarkersLRU = `-- name: PrunePullsListMarkersLRU :exec
DELETE FROM pulls_list_cache WHERE id IN (
    SELECT id FROM pulls_list_cache ORDER BY last_used_at DESC LIMIT -1 OFFSET ?
)
`

func (q *Queries) PrunePullsListMarkersLRU(ctx context.Context, offset int64) error {
	_, err := q.db.ExecContext(ctx, prunePullsListMarkersLRU, offset)
	return err
}

const pruneRepoInstallationCacheLRU = `-- name: PruneRepoInstallationCacheLRU :exec
DELETE FROM repo_installation_cache WHERE id IN (
    SELECT id FROM repo_installation_cache ORDER BY last_used_at DESC LIMIT -1 OFFSET ?
)
`

func (q *Queries) PruneRepoInstallationCacheLRU(ctx context.Context, offset int64) error {
	_, err := q.db.ExecContext(ctx, pruneRepoInstallationCacheLRU, offset)
	return err
}

const pruneSettledWorkflowRuns = `-- name: PruneSettledWorkflowRuns :exec
DELETE FROM workflow_runs WHERE status = 'completed' AND touched_at < ?
`

// PruneSettledWorkflowRuns bounds the table: completed runs the mirror has
// not touched within the retention window are dropped. Runs still queued or
// in progress are never pruned.
func (q *Queries) PruneSettledWorkflowRuns(ctx context.Context, touchedAt string) error {
	_, err := q.db.ExecContext(ctx, pruneSettledWorkflowRuns, touchedAt)
	return err
}

const pruneWorkflowJobsCacheLRU = `-- name: PruneWorkflowJobsCacheLRU :exec
DELETE FROM workflow_jobs_cache WHERE id IN (
    SELECT id FROM workflow_jobs_cache ORDER BY last_used_at DESC LIMIT -1 OFFSET ?
)
`

func (q *Queries) PruneWorkflowJobsCacheLRU(ctx context.Context, offset int64) error {
	_, err := q.db.ExecContext(ctx, pruneWorkflowJobsCacheLRU, offset)
	return err
}

const pruneWorkflowRunsCacheLRU = `-- name: PruneWorkflowRunsCacheLRU :exec
DELETE FROM workflow_runs_cache WHERE id IN (
    SELECT id FROM workflow_runs_cache ORDER BY last_used_at DESC LIMIT -1 OFFSET ?
)
`

func (q *Queries) PruneWorkflowRunsCacheLRU(ctx context.Context, offset int64) error {
	_, err := q.db.ExecContext(ctx, pruneWorkflowRunsCacheLRU, offset)
	return err
}

const touchBranchesListCache = `-- name: TouchBranchesListCache :exec
UPDATE branches_list_cache SET last_used_at = ?
WHERE owner = ? AND repo = ? AND per_page = ? AND page = ?
`

type TouchBranchesListCacheParams struct {
	LastUsedAt string
	Owner      string
	Repo       string
	PerPage    int64
	Page       int64
}

func (q *Queries) TouchBranchesListCache(ctx context.Context, arg TouchBranchesListCacheParams) error {
	_, err := q.db.ExecContext(ctx, touchBranchesListCache,
		arg.LastUsedAt,
		arg.Owner,
		arg.Repo,
		arg.PerPage,
		arg.Page,
	)
	return err
}

const touchClosedPullCache = `-- name: TouchClosedPullCache :exec
UPDATE closed_pull_cache SET last_used_at = ?
WHERE owner = ? AND repo = ? AND number = ?
`

type TouchClosedPullCacheParams struct {
	LastUsedAt string
	Owner      string
	Repo       string
	Number     int64
}

func (q *Queries) TouchClosedPullCache(ctx context.Context, arg TouchClosedPullCacheParams) error {
	_, err := q.db.ExecContext(ctx, touchClosedPullCache,
		arg.LastUsedAt,
		arg.Owner,
		arg.Repo,
		arg.Number,
	)
	return err
}

const touchCodeQualitySetupCache = `-- name: TouchCodeQualitySetupCache :exec
UPDATE code_quality_setup_cache SET last_used_at = ? WHERE owner = ? AND repo = ?
`

type TouchCodeQualitySetupCacheParams struct {
	LastUsedAt string
	Owner      string
	Repo       string
}

func (q *Queries) TouchCodeQualitySetupCache(ctx context.Context, arg TouchCodeQualitySetupCacheParams) error {
	_, err := q.db.ExecContext(ctx, touchCodeQualitySetupCache, arg.LastUsedAt, arg.Owner, arg.Repo)
	return err
}

const touchCommitCICache = `-- name: TouchCommitCICache :exec
UPDATE commit_ci_cache SET last_used_at = ?
WHERE owner = ? AND repo = ? AND ref = ? AND kind = ? AND per_page = ? AND page = ?
`

type TouchCommitCICacheParams struct {
	LastUsedAt string
	Owner      string
	Repo       string
	Ref        string
	Kind       string
	PerPage    int64
	Page       int64
}

func (q *Queries) TouchCommitCICache(ctx context.Context, arg TouchCommitCICacheParams) error {
	_, err := q.db.ExecContext(ctx, touchCommitCICache,
		arg.LastUsedAt,
		arg.Owner,
		arg.Repo,
		arg.Ref,
		arg.Kind,
		arg.PerPage,
		arg.Page,
	)
	return err
}

const touchCommitsListCache = `-- name: TouchCommitsListCache :exec
UPDATE commits_list_cache SET last_used_at = ?
WHERE owner = ? AND repo = ? AND ref_param = ? AND per_page = ? AND page = ?
`

type TouchCommitsListCacheParams struct {
	LastUsedAt string
	Owner      string
	Repo       string
	RefParam   string
	PerPage    int64
	Page       int64
}

func (q *Queries) TouchCommitsListCache(ctx context.Context, arg TouchCommitsListCacheParams) error {
	_, err := q.db.ExecContext(ctx, touchCommitsListCache,
		arg.LastUsedAt,
		arg.Owner,
		arg.Repo,
		arg.RefParam,
		arg.PerPage,
		arg.Page,
	)
	return err
}

const touchCompareCache = `-- name: TouchCompareCache :exec
UPDATE compare_cache SET last_used_at = ?
WHERE owner = ? AND repo = ? AND basehead = ?
`

type TouchCompareCacheParams struct {
	LastUsedAt string
	Owner      string
	Repo       string
	Basehead   string
}

func (q *Queries) TouchCompareCache(ctx context.Context, arg TouchCompareCacheParams) error {
	_, err := q.db.ExecContext(ctx, touchCompareCache,
		arg.LastUsedAt,
		arg.Owner,
		arg.Repo,
		arg.Basehead,
	)
	return err
}

const touchContentsCache = `-- name: TouchContentsCache :exec
UPDATE contents_cache SET last_used_at = ?
WHERE owner = ? AND repo = ? AND path = ? AND ref = ?
`

type TouchContentsCacheParams struct {
	LastUsedAt string
	Owner      string
	Repo       string
	Path       string
	Ref        string
}

func (q *Queries) TouchContentsCache(ctx context.Context, arg TouchContentsCacheParams) error {
	_, err := q.db.ExecContext(ctx, touchContentsCache,
		arg.LastUsedAt,
		arg.Owner,
		arg.Repo,
		arg.Path,
		arg.Ref,
	)
	return err
}

const touchGitCommitCache = `-- name: TouchGitCommitCache :exec
UPDATE git_commits_cache SET last_used_at = ?
WHERE owner = ? AND repo = ? AND sha = ?
`

type TouchGitCommitCacheParams struct {
	LastUsedAt string
	Owner      string
	Repo       string
	Sha        string
}

func (q *Queries) TouchGitCommitCache(ctx context.Context, arg TouchGitCommitCacheParams) error {
	_, err := q.db.ExecContext(ctx, touchGitCommitCache,
		arg.LastUsedAt,
		arg.Owner,
		arg.Repo,
		arg.Sha,
	)
	return err
}

const touchGitCommitMissCache = `-- name: TouchGitCommitMissCache :exec
UPDATE git_commit_miss_cache SET last_used_at = ?
WHERE owner = ? AND repo = ? AND sha = ?
`

type TouchGitCommitMissCacheParams struct {
	LastUsedAt string
	Owner      string
	Repo       string
	Sha        string
}

func (q *Queries) TouchGitCommitMissCache(ctx context.Context, arg TouchGitCommitMissCacheParams) error {
	_, err := q.db.ExecContext(ctx, touchGitCommitMissCache,
		arg.LastUsedAt,
		arg.Owner,
		arg.Repo,
		arg.Sha,
	)
	return err
}

const touchGitRefCache = `-- name: TouchGitRefCache :exec
UPDATE git_ref_cache SET last_used_at = ?
WHERE owner = ? AND repo = ? AND ref = ?
`

type TouchGitRefCacheParams struct {
	LastUsedAt string
	Owner      string
	Repo       string
	Ref        string
}

func (q *Queries) TouchGitRefCache(ctx context.Context, arg TouchGitRefCacheParams) error {
	_, err := q.db.ExecContext(ctx, touchGitRefCache,
		arg.LastUsedAt,
		arg.Owner,
		arg.Repo,
		arg.Ref,
	)
	return err
}

const touchInstallationReposCache = `-- name: TouchInstallationReposCache :exec
UPDATE installation_repos_cache SET last_used_at = ?
WHERE token_fp = ? AND per_page = ? AND page = ?
`

type TouchInstallationReposCacheParams struct {
	LastUsedAt string
	TokenFp    string
	PerPage    int64
	Page       int64
}

func (q *Queries) TouchInstallationReposCache(ctx context.Context, arg TouchInstallationReposCacheParams) error {
	_, err := q.db.ExecContext(ctx, touchInstallationReposCache,
		arg.LastUsedAt,
		arg.TokenFp,
		arg.PerPage,
		arg.Page,
	)
	return err
}

const touchLabelCache = `-- name: TouchLabelCache :exec
UPDATE label_cache SET last_used_at = ? WHERE owner = ? AND repo = ? AND name = ?
`

type TouchLabelCacheParams struct {
	LastUsedAt string
	Owner      string
	Repo       string
	Name       string
}

func (q *Queries) TouchLabelCache(ctx context.Context, arg TouchLabelCacheParams) error {
	_, err := q.db.ExecContext(ctx, touchLabelCache,
		arg.LastUsedAt,
		arg.Owner,
		arg.Repo,
		arg.Name,
	)
	return err
}

const touchPullDiff406Cache = `-- name: TouchPullDiff406Cache :exec
UPDATE pull_diff406_cache SET last_used_at = ?
WHERE owner = ? AND repo = ? AND number = ?
`

type TouchPullDiff406CacheParams struct {
	LastUsedAt string
	Owner      string
	Repo       string
	Number     int64
}

func (q *Queries) TouchPullDiff406Cache(ctx context.Context, arg TouchPullDiff406CacheParams) error {
	_, err := q.db.ExecContext(ctx, touchPullDiff406Cache,
		arg.LastUsedAt,
		arg.Owner,
		arg.Repo,
		arg.Number,
	)
	return err
}

const touchPullFilesCache = `-- name: TouchPullFilesCache :exec
UPDATE pull_files_cache SET last_used_at = ?
WHERE owner = ? AND repo = ? AND number = ? AND per_page = ? AND page = ?
`

type TouchPullFilesCacheParams struct {
	LastUsedAt string
	Owner      string
	Repo       string
	Number     int64
	PerPage    int64
	Page       int64
}

func (q *Queries) TouchPullFilesCache(ctx context.Context, arg TouchPullFilesCacheParams) error {
	_, err := q.db.ExecContext(ctx, touchPullFilesCache,
		arg.LastUsedAt,
		arg.Owner,
		arg.Repo,
		arg.Number,
		arg.PerPage,
		arg.Page,
	)
	return err
}

const touchPullsListMarker = `-- name: TouchPullsListMarker :exec
UPDATE pulls_list_cache SET last_used_at = ?
WHERE owner = ? AND repo = ?
`

type TouchPullsListMarkerParams struct {
	LastUsedAt string
	Owner      string
	Repo       string
}

func (q *Queries) TouchPullsListMarker(ctx context.Context, arg TouchPullsListMarkerParams) error {
	_, err := q.db.ExecContext(ctx, touchPullsListMarker, arg.LastUsedAt, arg.Owner, arg.Repo)
	return err
}

const touchRepoInstallationCache = `-- name: TouchRepoInstallationCache :exec
UPDATE repo_installation_cache SET last_used_at = ?
WHERE actor = ? AND owner = ? AND repo = ?
`

type TouchRepoInstallationCacheParams struct {
	LastUsedAt string
	Actor      string
	Owner      string
	Repo       string
}

func (q *Queries) TouchRepoInstallationCache(ctx context.Context, arg TouchRepoInstallationCacheParams) error {
	_, err := q.db.ExecContext(ctx, touchRepoInstallationCache,
		arg.LastUsedAt,
		arg.Actor,
		arg.Owner,
		arg.Repo,
	)
	return err
}

const touchWorkflowJobsCache = `-- name: TouchWorkflowJobsCache :exec
UPDATE workflow_jobs_cache SET last_used_at = ?
WHERE owner = ? AND repo = ? AND kind = ? AND ref_id = ? AND per_page = ? AND page = ?
`

type TouchWorkflowJobsCacheParams struct {
	LastUsedAt string
	Owner      string
	Repo       string
	Kind       string
	RefID      int64
	PerPage    int64
	Page       int64
}

func (q *Queries) TouchWorkflowJobsCache(ctx context.Context, arg TouchWorkflowJobsCacheParams) error {
	_, err := q.db.ExecContext(ctx, touchWorkflowJobsCache,
		arg.LastUsedAt,
		arg.Owner,
		arg.Repo,
		arg.Kind,
		arg.RefID,
		arg.PerPage,
		arg.Page,
	)
	return err
}

const touchWorkflowRunsCache = `-- name: TouchWorkflowRunsCache :exec
UPDATE workflow_runs_cache SET last_used_at = ?
WHERE owner = ? AND repo = ? AND head_sha = ? AND per_page = ? AND page = ?
`

type TouchWorkflowRunsCacheParams struct {
	LastUsedAt string
	Owner      string
	Repo       string
	HeadSha    string
	PerPage    int64
	Page       int64
}

func (q *Queries) TouchWorkflowRunsCache(ctx context.Context, arg TouchWorkflowRunsCacheParams) error {
	_, err := q.db.ExecContext(ctx, touchWorkflowRunsCache,
		arg.LastUsedAt,
		arg.Owner,
		arg.Repo,
		arg.HeadSha,
		arg.PerPage,
		arg.Page,
	)
	return err
}

const upsertBranchesListCache = `-- name: UpsertBranchesListCache :exec
INSERT INTO branches_list_cache (owner, repo, per_page, page, doc, fetched_at, expires_at, last_used_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT (owner, repo, per_page, page) DO UPDATE SET
    doc = excluded.doc,
    fetched_at = excluded.fetched_at,
    expires_at = excluded.expires_at,
    last_used_at = excluded.last_used_at
`

type UpsertBranchesListCacheParams struct {
	Owner      string
	Repo       string
	PerPage    int64
	Page       int64
	Doc        string
	FetchedAt  string
	ExpiresAt  string
	LastUsedAt string
}

func (q *Queries) UpsertBranchesListCache(ctx context.Context, arg UpsertBranchesListCacheParams) error {
	_, err := q.db.ExecContext(ctx, upsertBranchesListCache,
		arg.Owner,
		arg.Repo,
		arg.PerPage,
		arg.Page,
		arg.Doc,
		arg.FetchedAt,
		arg.ExpiresAt,
		arg.LastUsedAt,
	)
	return err
}

const upsertClosedPullCache = `-- name: UpsertClosedPullCache :exec
INSERT INTO closed_pull_cache (owner, repo, number, doc, fetched_at, expires_at, last_used_at)
VALUES (?, ?, ?, ?, ?, ?, ?)
ON CONFLICT (owner, repo, number) DO UPDATE SET
    doc = excluded.doc,
    fetched_at = excluded.fetched_at,
    expires_at = excluded.expires_at,
    last_used_at = excluded.last_used_at
`

type UpsertClosedPullCacheParams struct {
	Owner      string
	Repo       string
	Number     int64
	Doc        string
	FetchedAt  string
	ExpiresAt  string
	LastUsedAt string
}

func (q *Queries) UpsertClosedPullCache(ctx context.Context, arg UpsertClosedPullCacheParams) error {
	_, err := q.db.ExecContext(ctx, upsertClosedPullCache,
		arg.Owner,
		arg.Repo,
		arg.Number,
		arg.Doc,
		arg.FetchedAt,
		arg.ExpiresAt,
		arg.LastUsedAt,
	)
	return err
}

const upsertCodeQualitySetupCache = `-- name: UpsertCodeQualitySetupCache :exec
INSERT INTO code_quality_setup_cache (owner, repo, doc, fetched_at, expires_at, last_used_at)
VALUES (?, ?, ?, ?, ?, ?)
ON CONFLICT (owner, repo) DO UPDATE SET
    doc = excluded.doc,
    fetched_at = excluded.fetched_at,
    expires_at = excluded.expires_at,
    last_used_at = excluded.last_used_at
`

type UpsertCodeQualitySetupCacheParams struct {
	Owner      string
	Repo       string
	Doc        string
	FetchedAt  string
	ExpiresAt  string
	LastUsedAt string
}

func (q *Queries) UpsertCodeQualitySetupCache(ctx context.Context, arg UpsertCodeQualitySetupCacheParams) error {
	_, err := q.db.ExecContext(ctx, upsertCodeQualitySetupCache,
		arg.Owner,
		arg.Repo,
		arg.Doc,
		arg.FetchedAt,
		arg.ExpiresAt,
		arg.LastUsedAt,
	)
	return err
}

const upsertCommitCICache = `-- name: UpsertCommitCICache :exec
INSERT INTO commit_ci_cache (owner, repo, ref, kind, per_page, page, doc, fetched_at, expires_at, last_used_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT (owner, repo, ref, kind, per_page, page) DO UPDATE SET
    doc = excluded.doc,
    fetched_at = excluded.fetched_at,
    expires_at = excluded.expires_at,
    last_used_at = excluded.last_used_at
`

type UpsertCommitCICacheParams struct {
	Owner      string
	Repo       string
	Ref        string
	Kind       string
	PerPage    int64
	Page       int64
	Doc        string
	FetchedAt  string
	ExpiresAt  string
	LastUsedAt string
}

func (q *Queries) UpsertCommitCICache(ctx context.Context, arg UpsertCommitCICacheParams) error {
	_, err := q.db.ExecContext(ctx, upsertCommitCICache,
		arg.Owner,
		arg.Repo,
		arg.Ref,
		arg.Kind,
		arg.PerPage,
		arg.Page,
		arg.Doc,
		arg.FetchedAt,
		arg.ExpiresAt,
		arg.LastUsedAt,
	)
	return err
}

const upsertCommitsListCache = `-- name: UpsertCommitsListCache :exec
INSERT INTO commits_list_cache (owner, repo, ref_param, per_page, page, shas, fetched_at, expires_at, last_used_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT (owner, repo, ref_param, per_page, page) DO UPDATE SET
    shas = excluded.shas,
    fetched_at = excluded.fetched_at,
    expires_at = excluded.expires_at,
    last_used_at = excluded.last_used_at
`

type UpsertCommitsListCacheParams struct {
	Owner      string
	Repo       string
	RefParam   string
	PerPage    int64
	Page       int64
	Shas       string
	FetchedAt  string
	ExpiresAt  string
	LastUsedAt string
}

func (q *Queries) UpsertCommitsListCache(ctx context.Context, arg UpsertCommitsListCacheParams) error {
	_, err := q.db.ExecContext(ctx, upsertCommitsListCache,
		arg.Owner,
		arg.Repo,
		arg.RefParam,
		arg.PerPage,
		arg.Page,
		arg.Shas,
		arg.FetchedAt,
		arg.ExpiresAt,
		arg.LastUsedAt,
	)
	return err
}

const upsertCompareCache = `-- name: UpsertCompareCache :exec
INSERT INTO compare_cache (owner, repo, basehead, base_ref, head_ref, status, doc, fetched_at, expires_at, last_used_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT (owner, repo, basehead) DO UPDATE SET
    base_ref = excluded.base_ref,
    head_ref = excluded.head_ref,
    status = excluded.status,
    doc = excluded.doc,
    fetched_at = excluded.fetched_at,
    expires_at = excluded.expires_at,
    last_used_at = excluded.last_used_at
`

type UpsertCompareCacheParams struct {
	Owner      string
	Repo       string
	Basehead   string
	BaseRef    string
	HeadRef    string
	Status     int64
	Doc        string
	FetchedAt  string
	ExpiresAt  string
	LastUsedAt string
}

func (q *Queries) UpsertCompareCache(ctx context.Context, arg UpsertCompareCacheParams) error {
	_, err := q.db.ExecContext(ctx, upsertCompareCache,
		arg.Owner,
		arg.Repo,
		arg.Basehead,
		arg.BaseRef,
		arg.HeadRef,
		arg.Status,
		arg.Doc,
		arg.FetchedAt,
		arg.ExpiresAt,
		arg.LastUsedAt,
	)
	return err
}

const upsertContentsCache = `-- name: UpsertContentsCache :exec
INSERT INTO contents_cache (owner, repo, path, ref, kind, name, sha, size, encoding, content, entries, message, fetched_at, expires_at, last_used_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT (owner, repo, path, ref) DO UPDATE SET
    kind = excluded.kind,
    name = excluded.name,
    sha = excluded.sha,
    size = excluded.size,
    encoding = excluded.encoding,
    content = excluded.content,
    entries = excluded.entries,
    message = excluded.message,
    fetched_at = excluded.fetched_at,
    expires_at = excluded.expires_at,
    last_used_at = excluded.last_used_at
`

type UpsertContentsCacheParams struct {
	Owner      string
	Repo       string
	Path       string
	Ref        string
	Kind       string
	Name       string
	Sha        string
	Size       int64
	Encoding   string
	Content    string
	Entries    string
	Message    string
	FetchedAt  string
	ExpiresAt  string
	LastUsedAt string
}

func (q *Queries) UpsertContentsCache(ctx context.Context, arg UpsertContentsCacheParams) error {
	_, err := q.db.ExecContext(ctx, upsertContentsCache,
		arg.Owner,
		arg.Repo,
		arg.Path,
		arg.Ref,
		arg.Kind,
		arg.Name,
		arg.Sha,
		arg.Size,
		arg.Encoding,
		arg.Content,
		arg.Entries,
		arg.Message,
		arg.FetchedAt,
		arg.ExpiresAt,
		arg.LastUsedAt,
	)
	return err
}

const upsertGitCommitCache = `-- name: UpsertGitCommitCache :exec
INSERT INTO git_commits_cache (owner, repo, sha, message, author_name, author_email, author_date, committer_name, committer_email, committer_date, tree_sha, parents, fetched_at, last_used_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT (owner, repo, sha) DO UPDATE SET
    message = excluded.message,
    author_name = excluded.author_name,
    author_email = excluded.author_email,
    author_date = excluded.author_date,
    committer_name = excluded.committer_name,
    committer_email = excluded.committer_email,
    committer_date = excluded.committer_date,
    tree_sha = excluded.tree_sha,
    parents = excluded.parents,
    fetched_at = excluded.fetched_at,
    last_used_at = excluded.last_used_at
`

type UpsertGitCommitCacheParams struct {
	Owner          string
	Repo           string
	Sha            string
	Message        string
	AuthorName     string
	AuthorEmail    string
	AuthorDate     string
	CommitterName  string
	CommitterEmail string
	CommitterDate  string
	TreeSha        string
	Parents        string
	FetchedAt      string
	LastUsedAt     string
}

func (q *Queries) UpsertGitCommitCache(ctx context.Context, arg UpsertGitCommitCacheParams) error {
	_, err := q.db.ExecContext(ctx, upsertGitCommitCache,
		arg.Owner,
		arg.Repo,
		arg.Sha,
		arg.Message,
		arg.AuthorName,
		arg.AuthorEmail,
		arg.AuthorDate,
		arg.CommitterName,
		arg.CommitterEmail,
		arg.CommitterDate,
		arg.TreeSha,
		arg.Parents,
		arg.FetchedAt,
		arg.LastUsedAt,
	)
	return err
}

const upsertGitCommitMissCache = `-- name: UpsertGitCommitMissCache :exec
INSERT INTO git_commit_miss_cache (owner, repo, sha, doc, fetched_at, expires_at, last_used_at)
VALUES (?, ?, ?, ?, ?, ?, ?)
ON CONFLICT (owner, repo, sha) DO UPDATE SET
    doc = excluded.doc,
    fetched_at = excluded.fetched_at,
    expires_at = excluded.expires_at,
    last_used_at = excluded.last_used_at
`

type UpsertGitCommitMissCacheParams struct {
	Owner      string
	Repo       string
	Sha        string
	Doc        string
	FetchedAt  string
	ExpiresAt  string
	LastUsedAt string
}

func (q *Queries) UpsertGitCommitMissCache(ctx context.Context, arg UpsertGitCommitMissCacheParams) error {
	_, err := q.db.ExecContext(ctx, upsertGitCommitMissCache,
		arg.Owner,
		arg.Repo,
		arg.Sha,
		arg.Doc,
		arg.FetchedAt,
		arg.ExpiresAt,
		arg.LastUsedAt,
	)
	return err
}

const upsertGitRefCache = `-- name: UpsertGitRefCache :exec
INSERT INTO git_ref_cache (owner, repo, ref, status, doc, fetched_at, expires_at, last_used_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT (owner, repo, ref) DO UPDATE SET
    status = excluded.status,
    doc = excluded.doc,
    fetched_at = excluded.fetched_at,
    expires_at = excluded.expires_at,
    last_used_at = excluded.last_used_at
`

type UpsertGitRefCacheParams struct {
	Owner      string
	Repo       string
	Ref        string
	Status     int64
	Doc        string
	FetchedAt  string
	ExpiresAt  string
	LastUsedAt string
}

func (q *Queries) UpsertGitRefCache(ctx context.Context, arg UpsertGitRefCacheParams) error {
	_, err := q.db.ExecContext(ctx, upsertGitRefCache,
		arg.Owner,
		arg.Repo,
		arg.Ref,
		arg.Status,
		arg.Doc,
		arg.FetchedAt,
		arg.ExpiresAt,
		arg.LastUsedAt,
	)
	return err
}

const upsertInstallTokenCache = `-- name: UpsertInstallTokenCache :exec
INSERT INTO install_token_cache (actor, installation_id, body_hash, token, token_expires_at, permissions, repository_selection, fetched_at, expires_at, last_used_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT (actor, installation_id, body_hash) DO UPDATE SET
    token = excluded.token,
    token_expires_at = excluded.token_expires_at,
    permissions = excluded.permissions,
    repository_selection = excluded.repository_selection,
    fetched_at = excluded.fetched_at,
    expires_at = excluded.expires_at,
    last_used_at = excluded.last_used_at
`

type UpsertInstallTokenCacheParams struct {
	Actor               string
	InstallationID      string
	BodyHash            string
	Token               string
	TokenExpiresAt      string
	Permissions         string
	RepositorySelection string
	FetchedAt           string
	ExpiresAt           string
	LastUsedAt          string
}

func (q *Queries) UpsertInstallTokenCache(ctx context.Context, arg UpsertInstallTokenCacheParams) error {
	_, err := q.db.ExecContext(ctx, upsertInstallTokenCache,
		arg.Actor,
		arg.InstallationID,
		arg.BodyHash,
		arg.Token,
		arg.TokenExpiresAt,
		arg.Permissions,
		arg.RepositorySelection,
		arg.FetchedAt,
		arg.ExpiresAt,
		arg.LastUsedAt,
	)
	return err
}

const upsertInstallationReposCache = `-- name: UpsertInstallationReposCache :exec
INSERT INTO installation_repos_cache (token_fp, per_page, page, doc, fetched_at, expires_at, last_used_at)
VALUES (?, ?, ?, ?, ?, ?, ?)
ON CONFLICT (token_fp, per_page, page) DO UPDATE SET
    doc = excluded.doc,
    fetched_at = excluded.fetched_at,
    expires_at = excluded.expires_at,
    last_used_at = excluded.last_used_at
`

type UpsertInstallationReposCacheParams struct {
	TokenFp    string
	PerPage    int64
	Page       int64
	Doc        string
	FetchedAt  string
	ExpiresAt  string
	LastUsedAt string
}

func (q *Queries) UpsertInstallationReposCache(ctx context.Context, arg UpsertInstallationReposCacheParams) error {
	_, err := q.db.ExecContext(ctx, upsertInstallationReposCache,
		arg.TokenFp,
		arg.PerPage,
		arg.Page,
		arg.Doc,
		arg.FetchedAt,
		arg.ExpiresAt,
		arg.LastUsedAt,
	)
	return err
}

const upsertLabelCache = `-- name: UpsertLabelCache :exec
INSERT INTO label_cache (owner, repo, name, doc, fetched_at, expires_at, last_used_at)
VALUES (?, ?, ?, ?, ?, ?, ?)
ON CONFLICT (owner, repo, name) DO UPDATE SET
    doc = excluded.doc,
    fetched_at = excluded.fetched_at,
    expires_at = excluded.expires_at,
    last_used_at = excluded.last_used_at
`

type UpsertLabelCacheParams struct {
	Owner      string
	Repo       string
	Name       string
	Doc        string
	FetchedAt  string
	ExpiresAt  string
	LastUsedAt string
}

func (q *Queries) UpsertLabelCache(ctx context.Context, arg UpsertLabelCacheParams) error {
	_, err := q.db.ExecContext(ctx, upsertLabelCache,
		arg.Owner,
		arg.Repo,
		arg.Name,
		arg.Doc,
		arg.FetchedAt,
		arg.ExpiresAt,
		arg.LastUsedAt,
	)
	return err
}

const upsertPullDiff406Cache = `-- name: UpsertPullDiff406Cache :exec
INSERT INTO pull_diff406_cache (owner, repo, number, doc, fetched_at, expires_at, last_used_at)
VALUES (?, ?, ?, ?, ?, ?, ?)
ON CONFLICT (owner, repo, number) DO UPDATE SET
    doc = excluded.doc,
    fetched_at = excluded.fetched_at,
    expires_at = excluded.expires_at,
    last_used_at = excluded.last_used_at
`

type UpsertPullDiff406CacheParams struct {
	Owner      string
	Repo       string
	Number     int64
	Doc        string
	FetchedAt  string
	ExpiresAt  string
	LastUsedAt string
}

func (q *Queries) UpsertPullDiff406Cache(ctx context.Context, arg UpsertPullDiff406CacheParams) error {
	_, err := q.db.ExecContext(ctx, upsertPullDiff406Cache,
		arg.Owner,
		arg.Repo,
		arg.Number,
		arg.Doc,
		arg.FetchedAt,
		arg.ExpiresAt,
		arg.LastUsedAt,
	)
	return err
}

const upsertPullFilesCache = `-- name: UpsertPullFilesCache :exec
INSERT INTO pull_files_cache (owner, repo, number, per_page, page, doc, fetched_at, expires_at, last_used_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT (owner, repo, number, per_page, page) DO UPDATE SET
    doc = excluded.doc,
    fetched_at = excluded.fetched_at,
    expires_at = excluded.expires_at,
    last_used_at = excluded.last_used_at
`

type UpsertPullFilesCacheParams struct {
	Owner      string
	Repo       string
	Number     int64
	PerPage    int64
	Page       int64
	Doc        string
	FetchedAt  string
	ExpiresAt  string
	LastUsedAt string
}

func (q *Queries) UpsertPullFilesCache(ctx context.Context, arg UpsertPullFilesCacheParams) error {
	_, err := q.db.ExecContext(ctx, upsertPullFilesCache,
		arg.Owner,
		arg.Repo,
		arg.Number,
		arg.PerPage,
		arg.Page,
		arg.Doc,
		arg.FetchedAt,
		arg.ExpiresAt,
		arg.LastUsedAt,
	)
	return err
}

const upsertPullsListMarker = `-- name: UpsertPullsListMarker :exec
INSERT INTO pulls_list_cache (owner, repo, fetched_at, expires_at, last_used_at)
VALUES (?, ?, ?, ?, ?)
ON CONFLICT (owner, repo) DO UPDATE SET
    fetched_at = excluded.fetched_at,
    expires_at = excluded.expires_at,
    last_used_at = excluded.last_used_at
`

type UpsertPullsListMarkerParams struct {
	Owner      string
	Repo       string
	FetchedAt  string
	ExpiresAt  string
	LastUsedAt string
}

func (q *Queries) UpsertPullsListMarker(ctx context.Context, arg UpsertPullsListMarkerParams) error {
	_, err := q.db.ExecContext(ctx, upsertPullsListMarker,
		arg.Owner,
		arg.Repo,
		arg.FetchedAt,
		arg.ExpiresAt,
		arg.LastUsedAt,
	)
	return err
}

const upsertRepoInstallationCache = `-- name: UpsertRepoInstallationCache :exec
INSERT INTO repo_installation_cache (actor, owner, repo, status, message, installation_id, account_login, account_type, repository_selection, app_id, app_slug, target_type, fetched_at, expires_at, last_used_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT (actor, owner, repo) DO UPDATE SET
    status = excluded.status,
    message = excluded.message,
    installation_id = excluded.installation_id,
    account_login = excluded.account_login,
    account_type = excluded.account_type,
    repository_selection = excluded.repository_selection,
    app_id = excluded.app_id,
    app_slug = excluded.app_slug,
    target_type = excluded.target_type,
    fetched_at = excluded.fetched_at,
    expires_at = excluded.expires_at,
    last_used_at = excluded.last_used_at
`

type UpsertRepoInstallationCacheParams struct {
	Actor               string
	Owner               string
	Repo                string
	Status              int64
	Message             string
	InstallationID      int64
	AccountLogin        string
	AccountType         string
	RepositorySelection string
	AppID               int64
	AppSlug             string
	TargetType          string
	FetchedAt           string
	ExpiresAt           string
	LastUsedAt          string
}

func (q *Queries) UpsertRepoInstallationCache(ctx context.Context, arg UpsertRepoInstallationCacheParams) error {
	_, err := q.db.ExecContext(ctx, upsertRepoInstallationCache,
		arg.Actor,
		arg.Owner,
		arg.Repo,
		arg.Status,
		arg.Message,
		arg.InstallationID,
		arg.AccountLogin,
		arg.AccountType,
		arg.RepositorySelection,
		arg.AppID,
		arg.AppSlug,
		arg.TargetType,
		arg.FetchedAt,
		arg.ExpiresAt,
		arg.LastUsedAt,
	)
	return err
}

const upsertWorkflowJobsCache = `-- name: UpsertWorkflowJobsCache :exec
INSERT INTO workflow_jobs_cache (owner, repo, kind, ref_id, run_id, per_page, page, doc, fetched_at, expires_at, last_used_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT (owner, repo, kind, ref_id, per_page, page) DO UPDATE SET
    run_id = excluded.run_id,
    doc = excluded.doc,
    fetched_at = excluded.fetched_at,
    expires_at = excluded.expires_at,
    last_used_at = excluded.last_used_at
`

type UpsertWorkflowJobsCacheParams struct {
	Owner      string
	Repo       string
	Kind       string
	RefID      int64
	RunID      int64
	PerPage    int64
	Page       int64
	Doc        string
	FetchedAt  string
	ExpiresAt  string
	LastUsedAt string
}

func (q *Queries) UpsertWorkflowJobsCache(ctx context.Context, arg UpsertWorkflowJobsCacheParams) error {
	_, err := q.db.ExecContext(ctx, upsertWorkflowJobsCache,
		arg.Owner,
		arg.Repo,
		arg.Kind,
		arg.RefID,
		arg.RunID,
		arg.PerPage,
		arg.Page,
		arg.Doc,
		arg.FetchedAt,
		arg.ExpiresAt,
		arg.LastUsedAt,
	)
	return err
}

const upsertWorkflowRunFromJob = `-- name: UpsertWorkflowRunFromJob :exec
INSERT INTO workflow_runs (
    owner, repo, run_id, run_attempt, name, head_sha, head_branch,
    status, conclusion, html_url, created_at, updated_at, run_started_at, touched_at
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, '', '', '', '', '', ?)
ON CONFLICT (owner, repo, run_id) DO UPDATE SET
    run_attempt = MAX(excluded.run_attempt, workflow_runs.run_attempt),
    name        = CASE WHEN workflow_runs.name = '' THEN excluded.name ELSE workflow_runs.name END,
    head_sha    = CASE WHEN workflow_runs.head_sha = '' THEN excluded.head_sha ELSE workflow_runs.head_sha END,
    head_branch = CASE WHEN workflow_runs.head_branch = '' THEN excluded.head_branch ELSE workflow_runs.head_branch END,
    status      = CASE WHEN workflow_runs.status = 'queued' AND workflow_runs.conclusion = '' AND excluded.status = 'in_progress'
                       THEN 'in_progress' ELSE workflow_runs.status END,
    touched_at  = excluded.touched_at
`

type UpsertWorkflowRunFromJobParams struct {
	Owner      string
	Repo       string
	RunID      int64
	RunAttempt int64
	Name       string
	HeadSha    string
	HeadBranch string
	Status     string
	TouchedAt  string
}

// UpsertWorkflowRunFromJob records what a workflow_job delivery can prove
// about its RUN. A job payload names the run's identity but carries no
// run-level status, so this may only ever CREATE the row or RAISE its status
// floor: a job that is in_progress proves the run is in_progress. It must
// never conclude a run (the job set may be incomplete) and never regress one
// that a workflow_run delivery or a REST absorb already settled -- hence the
// status clause fires only when the stored status is 'queued' and the row was
// never given a conclusion.
func (q *Queries) UpsertWorkflowRunFromJob(ctx context.Context, arg UpsertWorkflowRunFromJobParams) error {
	_, err := q.db.ExecContext(ctx, upsertWorkflowRunFromJob,
		arg.Owner,
		arg.Repo,
		arg.RunID,
		arg.RunAttempt,
		arg.Name,
		arg.HeadSha,
		arg.HeadBranch,
		arg.Status,
		arg.TouchedAt,
	)
	return err
}

const upsertWorkflowRunFull = `-- name: UpsertWorkflowRunFull :exec

INSERT INTO workflow_runs (
    owner, repo, run_id, run_attempt, name, head_sha, head_branch,
    status, conclusion, html_url, created_at, updated_at, run_started_at, touched_at
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT (owner, repo, run_id) DO UPDATE SET
    run_attempt    = MAX(excluded.run_attempt, workflow_runs.run_attempt),
    name           = CASE WHEN excluded.name <> '' THEN excluded.name ELSE workflow_runs.name END,
    head_sha       = CASE WHEN excluded.head_sha <> '' THEN excluded.head_sha ELSE workflow_runs.head_sha END,
    head_branch    = CASE WHEN excluded.head_branch <> '' THEN excluded.head_branch ELSE workflow_runs.head_branch END,
    status         = CASE WHEN excluded.updated_at >= workflow_runs.updated_at THEN excluded.status ELSE workflow_runs.status END,
    conclusion     = CASE WHEN excluded.updated_at >= workflow_runs.updated_at THEN excluded.conclusion ELSE workflow_runs.conclusion END,
    html_url       = CASE WHEN excluded.html_url <> '' THEN excluded.html_url ELSE workflow_runs.html_url END,
    created_at     = CASE WHEN excluded.created_at <> '' THEN excluded.created_at ELSE workflow_runs.created_at END,
    updated_at     = MAX(excluded.updated_at, workflow_runs.updated_at),
    run_started_at = CASE WHEN excluded.run_started_at <> '' THEN excluded.run_started_at ELSE workflow_runs.run_started_at END,
    touched_at     = excluded.touched_at
`

type UpsertWorkflowRunFullParams struct {
	Owner        string
	Repo         string
	RunID        int64
	RunAttempt   int64
	Name         string
	HeadSha      string
	HeadBranch   string
	Status       string
	Conclusion   string
	HtmlUrl      string
	CreatedAt    string
	UpdatedAt    string
	RunStartedAt string
	TouchedAt    string
}

// ---- workflow_runs (truth) + workflow_runs_list_cache (completeness) ----
// UpsertWorkflowRunFull records a run from an AUTHORITATIVE source -- a
// workflow_run delivery or a REST absorb -- both of which carry the run's own
// status and conclusion. Out-of-order tolerant on the run's own updated_at:
// an older event never overwrites a newer one (a delivery replay, or a
// listing absorbed while a fresher delivery was in flight).
func (q *Queries) UpsertWorkflowRunFull(ctx context.Context, arg UpsertWorkflowRunFullParams) error {
	_, err := q.db.ExecContext(ctx, upsertWorkflowRunFull,
		arg.Owner,
		arg.Repo,
		arg.RunID,
		arg.RunAttempt,
		arg.Name,
		arg.HeadSha,
		arg.HeadBranch,
		arg.Status,
		arg.Conclusion,
		arg.HtmlUrl,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.RunStartedAt,
		arg.TouchedAt,
	)
	return err
}

const upsertWorkflowRunsCache = `-- name: UpsertWorkflowRunsCache :exec
INSERT INTO workflow_runs_cache (owner, repo, head_sha, per_page, page, doc, fetched_at, expires_at, last_used_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT (owner, repo, head_sha, per_page, page) DO UPDATE SET
    doc = excluded.doc,
    fetched_at = excluded.fetched_at,
    expires_at = excluded.expires_at,
    last_used_at = excluded.last_used_at
`

type UpsertWorkflowRunsCacheParams struct {
	Owner      string
	Repo       string
	HeadSha    string
	PerPage    int64
	Page       int64
	Doc        string
	FetchedAt  string
	ExpiresAt  string
	LastUsedAt string
}

func (q *Queries) UpsertWorkflowRunsCache(ctx context.Context, arg UpsertWorkflowRunsCacheParams) error {
	_, err := q.db.ExecContext(ctx, upsertWorkflowRunsCache,
		arg.Owner,
		arg.Repo,
		arg.HeadSha,
		arg.PerPage,
		arg.Page,
		arg.Doc,
		arg.FetchedAt,
		arg.ExpiresAt,
		arg.LastUsedAt,
	)
	return err
}

const upsertWorkflowRunsListMarker = `-- name: UpsertWorkflowRunsListMarker :exec
INSERT INTO workflow_runs_list_cache (owner, repo, filters, fetched_at, expires_at)
VALUES (?, ?, ?, ?, ?)
ON CONFLICT (owner, repo, filters) DO UPDATE SET
    fetched_at = excluded.fetched_at,
    expires_at = excluded.expires_at
`

type UpsertWorkflowRunsListMarkerParams struct {
	Owner     string
	Repo      string
	Filters   string
	FetchedAt string
	ExpiresAt string
}

func (q *Queries) UpsertWorkflowRunsListMarker(ctx context.Context, arg UpsertWorkflowRunsListMarkerParams) error {
	_, err := q.db.ExecContext(ctx, upsertWorkflowRunsListMarker,
		arg.Owner,
		arg.Repo,
		arg.Filters,
		arg.FetchedAt,
		arg.ExpiresAt,
	)
	return err
}
