// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: rest_responses.sql

package dbgen

import (
	"context"
	"database/sql"
)

const getRESTResponse = `-- name: GetRESTResponse :one
SELECT actor, resource_kind, resource_key, status_code, content_type, body, updated_at FROM rest_responses
WHERE actor = ? AND resource_kind = ? AND resource_key = ?
`

type GetRESTResponseParams struct {
	Actor        string
	ResourceKind string
	ResourceKey  string
}

func (q *Queries) GetRESTResponse(ctx context.Context, arg GetRESTResponseParams) (RestResponse, error) {
	row := q.db.QueryRowContext(ctx, getRESTResponse, arg.Actor, arg.ResourceKind, arg.ResourceKey)
	var i RestResponse
	err := row.Scan(
		&i.Actor,
		&i.ResourceKind,
		&i.ResourceKey,
		&i.StatusCode,
		&i.ContentType,
		&i.Body,
		&i.UpdatedAt,
	)
	return i, err
}

const markRESTResponsesStaleByKeyPrefix = `-- name: MarkRESTResponsesStaleByKeyPrefix :exec
UPDATE cache_metadata
SET fetch_state = 'stale'
WHERE resource_kind = ?1 AND substr(resource_key, 1, length(?2)) = ?2
`

type MarkRESTResponsesStaleByKeyPrefixParams struct {
	ResourceKind string
	KeyPrefix    interface{}
}

func (q *Queries) MarkRESTResponsesStaleByKeyPrefix(ctx context.Context, arg MarkRESTResponsesStaleByKeyPrefixParams) error {
	_, err := q.db.ExecContext(ctx, markRESTResponsesStaleByKeyPrefix, arg.ResourceKind, arg.KeyPrefix)
	return err
}

const upsertRESTResponse = `-- name: UpsertRESTResponse :exec
INSERT INTO rest_responses (actor, resource_kind, resource_key, status_code, content_type, body, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?)
ON CONFLICT (actor, resource_kind, resource_key) DO UPDATE SET
    status_code = excluded.status_code,
    content_type = excluded.content_type,
    body = excluded.body,
    updated_at = excluded.updated_at
`

type UpsertRESTResponseParams struct {
	Actor        string
	ResourceKind string
	ResourceKey  string
	StatusCode   int64
	ContentType  sql.NullString
	Body         []byte
	UpdatedAt    string
}

func (q *Queries) UpsertRESTResponse(ctx context.Context, arg UpsertRESTResponseParams) error {
	_, err := q.db.ExecContext(ctx, upsertRESTResponse,
		arg.Actor,
		arg.ResourceKind,
		arg.ResourceKey,
		arg.StatusCode,
		arg.ContentType,
		arg.Body,
		arg.UpdatedAt,
	)
	return err
}
