// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: webhook.sql

package dbgen

import (
	"context"
)

const distinctWebhookEventTypes = `-- name: DistinctWebhookEventTypes :many
SELECT DISTINCT event_type FROM webhook_deliveries WHERE event_type <> ''
`

// DistinctWebhookEventTypes lists the event types present in the RETAINED
// delivery log. The mirror's correctness depends on being subscribed to a
// specific set of events, and a missing subscription is otherwise invisible:
// the affected caches just quietly re-fetch forever. This is what turns that
// silence into something the dashboard can show. Bounded by the log's own
// prune, so absence means "not in the retained window", not "never sent".
func (q *Queries) DistinctWebhookEventTypes(ctx context.Context) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, distinctWebhookEventTypes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var event_type string
		if err := rows.Scan(&event_type); err != nil {
			return nil, err
		}
		items = append(items, event_type)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertWebhookDelivery = `-- name: InsertWebhookDelivery :exec

INSERT INTO webhook_deliveries (delivery_id, event_type, action, repo, received_at, disposition, detail)
VALUES (?, ?, ?, ?, ?, ?, ?)
`

type InsertWebhookDeliveryParams struct {
	DeliveryID  string
	EventType   string
	Action      string
	Repo        string
	ReceivedAt  string
	Disposition string
	Detail      string
}

// ============================================================================
// Webhook delivery log (dashboard observability)
// ============================================================================
func (q *Queries) InsertWebhookDelivery(ctx context.Context, arg InsertWebhookDeliveryParams) error {
	_, err := q.db.ExecContext(ctx, insertWebhookDelivery,
		arg.DeliveryID,
		arg.EventType,
		arg.Action,
		arg.Repo,
		arg.ReceivedAt,
		arg.Disposition,
		arg.Detail,
	)
	return err
}

const listRecentWebhookDeliveries = `-- name: ListRecentWebhookDeliveries :many
SELECT id, delivery_id, event_type, "action", repo, received_at, disposition, detail FROM webhook_deliveries
ORDER BY id DESC
LIMIT ?
`

func (q *Queries) ListRecentWebhookDeliveries(ctx context.Context, limit int64) ([]WebhookDelivery, error) {
	rows, err := q.db.QueryContext(ctx, listRecentWebhookDeliveries, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WebhookDelivery
	for rows.Next() {
		var i WebhookDelivery
		if err := rows.Scan(
			&i.ID,
			&i.DeliveryID,
			&i.EventType,
			&i.Action,
			&i.Repo,
			&i.ReceivedAt,
			&i.Disposition,
			&i.Detail,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const pruneWebhookDeliveries = `-- name: PruneWebhookDeliveries :exec
DELETE FROM webhook_deliveries
WHERE id <= (
    SELECT id FROM webhook_deliveries
    ORDER BY id DESC
    LIMIT 1 OFFSET ?
)
`

// PruneWebhookDeliveries keeps only the most recent rows. The subquery finds the
// id of the (keep+1)th newest delivery; everything at or below it is deleted. If
// there are fewer than keep+1 rows the subquery is NULL and nothing is removed.
func (q *Queries) PruneWebhookDeliveries(ctx context.Context, offset int64) error {
	_, err := q.db.ExecContext(ctx, pruneWebhookDeliveries, offset)
	return err
}
